limit_posts: 10
search:
  script-mode: "direct"
  host: "http://localhost:8080"

exclude:
  - _versions/2.13
  - _versions/2.16
  - _versions/3.2
  - _versions/3.8
  - _versions/3.15
  - _versions/3.20
  - _versions/3.27
  - _versions/3.33
  - _versions/3.34
