# Configuration for development

# We don't want to use the production instance of search.quarkus.io for development.
search:

# Use this to directly use the local instance of search.quarkus.io
  script: "http://localhost:8080/static/bundle/main.js"
  server: "http://localhost:8080"


# Use this to copy from the local instance of search.quarkus.io
#  script-copy: "http://localhost:8080/static/bundle/main.js"
#  server: "http://localhost:8080"


# Use this to copy from the production instance of search.quarkus.io
#  script-copy: "https://search.quarkus.io/static/bundle/main.js"
#  server: "https://search.quarkus.io/"
