services:
  jekyll:
    build: jekyll-container/
    command: [
      "bundle", "exec", "jekyll", "serve",
      "-H", "0.0.0.0", "-P", "4000",
      "--incremental", "--livereload",
      "--config", "_config.yml,_config_dev.yml,_config_dev_fast.yml"
    ]
    volumes:
      - .:/site:Z
    ports:
      - '4000:4000'
      - '35729:35729'
