# no version needed since 2020

services:
  jekyll:
    image: bretfisher/jekyll-serve
    # Add --incremental to the commandline
    # https://github.com/BretFisher/jekyll-serve/blob/2119a31476e1c6004a4bea4739b9160fc73e7bda/Dockerfile#L27C5-L27C94
    # Also, enable dev config
    command: [ "bundle", "exec", "jekyll", "serve", "--force_polling", "-H", "0.0.0.0", "-P", "4000", "--incremental", "--config", "_config.yml,_config_dev.yml" ]
    volumes:
      ## this Z handling needed to make things
      ## work on podman (see https://github.com/containers/podman/issues/19852)
      - .:/site #${_SELINUX_?_SELINUX_ variable is required and must be set to ':Z' if SELinux context is needed for volumes or run compose.sh to do it for you.}
    ports:
      - '4000:4000'
