= quarkus:add-extension

Allow adding an extension to an existing pom.xml file. Because you can add one or several extension in one go, there are 2 mojos: add-extensions and add-extension. Both supports the extension and extensions parameters.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-add-extension-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-add-extension-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extension-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extension-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extension-extension]] extension

[.description]
--
For usability reason, this parameter allows adding a single extension.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extension-extensions]] extensions

[.description]
--
The list of extensions to be added.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-add-extension-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-add-extension-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-add-extension-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-add-extension-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-add-extension-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:add-extensions

Allow adding extensions to an existing pom.xml file. Because you can add one or several extension in one go, there are 2 mojos: add-extensions and add-extension. Both supports the extension and extensions parameters.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-add-extensions-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-add-extensions-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extensions-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extensions-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extensions-extension]] extension

[.description]
--
For usability reason, this parameter allows adding a single extension.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-add-extensions-extensions]] extensions

[.description]
--
The list of extensions to be added.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-add-extensions-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-add-extensions-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-add-extensions-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-add-extensions-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-add-extensions-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:analyze-call-tree

Analyze call tree of a method or a class based on an existing report produced by Substrate when using -H:+PrintAnalysisCallTree, and does a more meaningful analysis of what is causing a type to be retained.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-analyze-call-tree-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-analyze-call-tree-className]] className
|`String`
|`${class}`

a| [[quarkus-maven-plugin-goal-analyze-call-tree-methodName]] methodName
|`String`
|`${method}`

a| [[quarkus-maven-plugin-goal-analyze-call-tree-reportsDir]] reportsDir
|`File`
|`${project.build.directory}/reports`

|===

= quarkus:build

Builds the Quarkus application.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-build-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-build-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-build-attachRunnerAsMainArtifact]] attachRunnerAsMainArtifact

[.description]
--
Whether to replace the original JAR with the Uber runner JAR as the main project artifact
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-build-attachSboms]] attachSboms

[.description]
--
Whether to attach SBOMs generated for Uber JARs as project artifacts
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-build-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-build-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-build-buildDirectory]] buildDirectory
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-build-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-build-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-build-generatedSourcesDirectory]] generatedSourcesDirectory

[.description]
--
The directory for generated source files.
--
|`File`
|`${project.build.directory}/generated-sources`

a| [[quarkus-maven-plugin-goal-build-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-build-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-build-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-build-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-build-pluginRepos]] pluginRepos

[.description]
--
The project's remote repositories to use for the resolution of plugins and their dependencies.
--
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-build-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-build-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-build-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-build-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-build-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-build-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-build-quarkus.build.skip]] quarkus.build.skip

[.description]
--
Skips the execution of this mojo
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-build-skipOriginalJarRename]] skipOriginalJarRename

[.description]
--
When the building an Uber JAR, the default JAR is renamed by adding .original suffix. Enabling this property will disable the renaming of the original JAR.
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-build-systemProperties]] systemProperties

[.description]
--
The list of system properties defined for the plugin.
--
|`Map`
|

|===

= quarkus:build-aot-enhanced-container-image

Takes the AOT file generated by the ITs and builds a container image that includes it

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-build-aot-enhanced-container-image-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:create

This goal helps in setting up Quarkus Maven project with quarkus-maven-plugin, with sensible defaults

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-create-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-create-appConfig]] appConfig
|`String`
|

a| [[quarkus-maven-plugin-goal-create-platformArtifactId]] platformArtifactId

[.description]
--
Artifact ID of the target platform BOM
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-platformGroupId]] platformGroupId

[.description]
--
Group ID of the target platform BOM
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-platformVersion]] platformVersion

[.description]
--
Version of the target platform BOM
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-buildTool]] buildTool
|`String`
|`MAVEN`

a| [[quarkus-maven-plugin-goal-create-className]] className

[.description]
--
The className will define the generated class names when picking only one of those extensions REST, RESTEasy Classic and Spring-Web. 
If more than one of those extensions are picked, then only the package name part will be used as packageName 
More info: https://github.com/quarkusio/quarkus/issues/14437 
By default, the projectGroupId is used as package for generated classes (you can also use packageName to have them different). 
className
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-data]] data
|`String`
|

a| [[quarkus-maven-plugin-goal-create-example]] example
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extensions]] extensions
|`Set`
|

a| [[quarkus-maven-plugin-goal-create-javaVersion]] javaVersion

[.description]
--
Version of Java used to build the project.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-noCode]] noCode

[.description]
--
When true, do not include any code in the generated Quarkus project.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-create-outputDirectory]] outputDirectory
|`File`
|`${basedir}`

a| [[quarkus-maven-plugin-goal-create-packageName]] packageName

[.description]
--
Set the package name of the generated classes. 
If not set, projectGroupId will be used as packageName 
packageName
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-path]] path

[.description]
--
The path will define the REST path of the generated code when picking only one of those extensions REST, RESTEasy Classic and Spring-Web. 
If more than one of those extensions are picked, this parameter will be ignored. 
More info: https://github.com/quarkusio/quarkus/issues/14437 
className
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-create-projectArtifactId]] projectArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-create-projectDescription]] projectDescription
|`String`
|

a| [[quarkus-maven-plugin-goal-create-projectGroupId]] projectGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-create-projectName]] projectName
|`String`
|

a| [[quarkus-maven-plugin-goal-create-projectVersion]] projectVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-create-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-create-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-create-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-create-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:create-extension

Creates the base of a Quarkus Extension <https://quarkus.io/guides/writing-extensions> in different layout depending on the options and environment. 


Create in the quarkus-parent project directory (or the extensions parent dir)

It will: 
* generate the new Quarkus extension in the extensions parent as a module (parent, runtime and deployment), with unit test and devmode test on option. 
* On option, generate the new integration test in the integration tests parent as a module. 
* add the dependencies to the bom/application/pom.xml. 

Creating a Quarkiverse extension

When using -DgroupId=io.quarkiverse.[featureId], the new extension will use the Quarkiverse layout. 


Creating a standalone extension


* generate the new Quarkus extension in the current directory (parent, runtime and deployment), with unit test and devmode test on option. 
* On option, generate the new integration test module in the current directory.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-create-extension-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-create-extension-artifactId]] artifactId

[.description]
--
Used to detect legacy command usage and display an error
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-basedir]] basedir

[.description]
--
Directory where the changes should be performed. 

Default: the current directory of the current Java process.
--
|`File`
|

a| [[quarkus-maven-plugin-goal-create-extension-extensionDescription]] extensionDescription

[.description]
--
The extensionDescription of the runtime module. 

This description is used on https://code.quarkus.io/.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-extensionId]] extensionId

[.description]
--
extensionId of this extension (REQUIRED). 

It will be used to generate the different extension modules artifactIds ([namespaceId][extensionId]-parent), runtime ([namespaceId][extensionId]) and deployment ([namespaceId][extensionId]-deployment).
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-extensionName]] extensionName

[.description]
--
The extensionName of the runtime module. The extensionNames of the extension parent and deployment modules will be based on this name too. 

Default: the formatted extensionId
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-groupId]] groupId

[.description]
--
The groupId for the newly created Maven modules (REQUIRED - INHERITED IN QUARKUS-CORE).
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-javaVersion]] javaVersion

[.description]
--
Version of Java used to build the project.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-namespaceId]] namespaceId

[.description]
--
A prefix common to all extension artifactIds in the current source tree. 

Default: "quarkus-" in quarkus Quarkus Core and Quarkiverse else ""
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-namespaceName]] namespaceName

[.description]
--
A prefix common to all extension names in the current source tree. 

Default: "quarkus-" in Quarkus Core and Quarkiverse else ""
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-packageName]] packageName

[.description]
--
Base package under which classes should be created in Runtime and Deployment modules. 

Default: auto-generated out of groupId, namespaceId and extensionId
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-create-extension-quarkusBomArtifactId]] quarkusBomArtifactId

[.description]
--
The artifactId of the Quarkus platform BOM. 

Default: io.quarkus.devtools.commands.CreateExtension.DEFAULT_BOM_ARTIFACT_ID
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-quarkusBomGroupId]] quarkusBomGroupId

[.description]
--
The groupId of the Quarkus platform BOM. 

Default: io.quarkus.devtools.commands.CreateExtension.DEFAULT_BOM_GROUP_ID
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-quarkusBomVersion]] quarkusBomVersion

[.description]
--
The version of the Quarkus platform BOM. 

Default: io.quarkus.devtools.commands.CreateExtension.DEFAULT_BOM_VERSION
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-quarkusVersion]] quarkusVersion

[.description]
--
Quarkus version the newly created extension should depend on (REQUIRED - INHERITED IN QUARKUS-CORE).
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-create-extension-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-create-extension-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-create-extension-version]] version

[.description]
--
The version for the newly created Maven modules. 

Default: automatic in Quarkus Core else io.quarkus.devtools.commands.CreateExtension.DEFAULT_VERSION
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-extension-withCodestart]] withCodestart

[.description]
--
Indicates whether to generate an extension codestart
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-create-extension-withoutDevModeTest]] withoutDevModeTest

[.description]
--
Indicates whether to generate a devmode test for the extension
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-create-extension-withoutIntegrationTests]] withoutIntegrationTests

[.description]
--
Indicates whether to generate an integration tests for the extension
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-create-extension-withoutTests]] withoutTests

[.description]
--
Indicates whether to generate any tests for the extension (same as -DwithoutUnitTest -DwithoutIntegrationTest -DwithoutDevModeTest)
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-create-extension-withoutUnitTest]] withoutUnitTest

[.description]
--
Indicates whether to generate a unit test class for the extension
--
|`boolean`
|

|===

= quarkus:create-jbang

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-create-jbang-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-create-jbang-platformArtifactId]] platformArtifactId

[.description]
--
Artifact ID of the target platform BOM
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-jbang-platformGroupId]] platformGroupId

[.description]
--
Group ID of the target platform BOM
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-jbang-platformVersion]] platformVersion

[.description]
--
Version of the target platform BOM
--
|`String`
|

a| [[quarkus-maven-plugin-goal-create-jbang-extensions]] extensions
|`Set`
|

a| [[quarkus-maven-plugin-goal-create-jbang-javaVersion]] javaVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-create-jbang-noJBangWrapper]] noJBangWrapper
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-create-jbang-outputDirectory]] outputDirectory
|`File`
|`${basedir}/jbang-with-quarkus`

a| [[quarkus-maven-plugin-goal-create-jbang-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-create-jbang-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

|===

= quarkus:dependency-list

Lists dependencies of a Quarkus application as resolved by the Quarkus bootstrap dependency resolver.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-dependency-list-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-dependency-list-appendOutput]] appendOutput

[.description]
--
Whether to append outputs into the output file or overwrite it.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-dependency-list-flags]] flags

[.description]
--
Comma-separated list of dependency flag names from io.quarkus.maven.dependency.DependencyFlags indicating which dependencies should be listed. Only dependencies that have all the specified flags set will be included. 
Accepted flag names (case-insensitive, both constant names and text names are supported): OPTIONAL, DIRECT, RUNTIME_CP (or runtime-cp), DEPLOYMENT_CP (or deployment-cp), RUNTIME_EXTENSION_ARTIFACT (or runtime-extension-artifact), WORKSPACE_MODULE (or workspace-module), RELOADABLE, TOP_LEVEL_RUNTIME_EXTENSION_ARTIFACT (or top-level-runtime-extension-artifact), CLASSLOADER_PARENT_FIRST (or classloader-parent-first), CLASSLOADER_RUNNER_PARENT_FIRST (or classloader-runner-parent-first), CLASSLOADER_LESSER_PRIORITY (or classloader-lesser-priority), COMPILE_ONLY (or compile-only).

If not specified, all dependencies returned by io.quarkus.bootstrap.model.ApplicationModel.getDependencies() are listed.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-dependency-list-mode]] mode

[.description]
--
Target launch mode corresponding to io.quarkus.runtime.LaunchMode for which the dependencies should be listed. io.quarkus.runtime.LaunchMode.NORMAL is the default.
--
|`String`
|`prod`

a| [[quarkus-maven-plugin-goal-dependency-list-outputFile]] outputFile

[.description]
--
If specified, this parameter will cause the dependency list to be written to the path specified, instead of writing to the console.
--
|`File`
|

a| [[quarkus-maven-plugin-goal-dependency-list-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-dependency-list-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-dependency-list-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-dependency-list-verbose]] verbose

[.description]
--
Whether to include dependency scope and flag names in the output for each dependency.
--
|`boolean`
|

|===

= quarkus:dependency-sbom

Quarkus application SBOM generator

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-dependency-sbom-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.format]] quarkus.dependency.sbom.format

[.description]
--
CycloneDX BOM format. Allowed values are json and xml. The default is json.
--
|`String`
|`json`

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.include-license-text]] quarkus.dependency.sbom.include-license-text

[.description]
--
Whether to include license text in the generated SBOM. The default is false
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.mode]] quarkus.dependency.sbom.mode

[.description]
--
Target launch mode corresponding to io.quarkus.runtime.LaunchMode for which the SBOM should be built. io.quarkus.runtime.LaunchMode.NORMAL is the default.
--
|`String`
|`prod`

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.output-file]] quarkus.dependency.sbom.output-file

[.description]
--
File to store the SBOM in. If not configured, the SBOM will be stored in the ${project.build.directory} directory.
--
|`File`
|

a| [[quarkus-maven-plugin-goal-dependency-sbom-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-dependency-sbom-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.runtime-only]] quarkus.dependency.sbom.runtime-only

[.description]
--
Whether to limit application dependencies to only those that are included in the runtime
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.schema-version]] quarkus.dependency.sbom.schema-version

[.description]
--
CycloneDX BOM schema version
--
|`String`
|

a| [[quarkus-maven-plugin-goal-dependency-sbom-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-dependency-sbom-quarkus.dependency.sbom.skip]] quarkus.dependency.sbom.skip

[.description]
--
Whether to skip the execution of the goal
--
|`boolean`
|`false`

|===

= quarkus:dependency-tree

Displays Quarkus application build dependency tree including the deployment ones.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-dependency-tree-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-dependency-tree-appendOutput]] appendOutput

[.description]
--
Whether to append outputs into the output file or overwrite it.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-dependency-tree-graph]] graph

[.description]
--
INCUBATING option, enabled with -Dquarkus.bootstrap.incubating-model-resolver system or project property. 
Whether to log all dependencies of each dependency node in a tree, adding [+] suffix to those whose dependencies are not expanded.
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-dependency-tree-mode]] mode

[.description]
--
Target launch mode corresponding to io.quarkus.runtime.LaunchMode for which the dependency tree should be built. io.quarkus.runtime.LaunchMode.NORMAL is the default.
--
|`String`
|`prod`

a| [[quarkus-maven-plugin-goal-dependency-tree-outputFile]] outputFile

[.description]
--
If specified, this parameter will cause the dependency tree to be written to the path specified, instead of writing to the console.
--
|`File`
|

a| [[quarkus-maven-plugin-goal-dependency-tree-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-dependency-tree-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-dependency-tree-runtimeOnly]] runtimeOnly

[.description]
--
Whether to log only the runtime dependencies of the Quarkus application
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-dependency-tree-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-dependency-tree-verbose]] verbose

[.description]
--
INCUBATING option, enabled with -Dquarkus.bootstrap.incubating-model-resolver system or project property. 
Whether to log dependency properties, such as on which classpath they belong, whether they are hot-reloadable in dev mode, etc.
--
|`boolean`
|

|===

= quarkus:deploy

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-deploy-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-deploy-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-deploy-attachRunnerAsMainArtifact]] attachRunnerAsMainArtifact

[.description]
--
Whether to replace the original JAR with the Uber runner JAR as the main project artifact
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-deploy-attachSboms]] attachSboms

[.description]
--
Whether to attach SBOMs generated for Uber JARs as project artifacts
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-deploy-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-deploy-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-deploy-buildDirectory]] buildDirectory
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-deploy-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-deploy-quarkus.deployment.dry-run]] quarkus.deployment.dry-run
|`boolean`
|

a| [[quarkus-maven-plugin-goal-deploy-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-deploy-generatedSourcesDirectory]] generatedSourcesDirectory

[.description]
--
The directory for generated source files.
--
|`File`
|`${project.build.directory}/generated-sources`

a| [[quarkus-maven-plugin-goal-deploy-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-deploy-quarkus.container-image.build]] quarkus.container-image.build
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-deploy-quarkus.container-image.builder]] quarkus.container-image.builder
|`String`
|

a| [[quarkus-maven-plugin-goal-deploy-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-deploy-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-deploy-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-deploy-pluginRepos]] pluginRepos

[.description]
--
The project's remote repositories to use for the resolution of plugins and their dependencies.
--
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-deploy-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-deploy-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-deploy-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-deploy-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-deploy-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-deploy-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-deploy-quarkus.build.skip]] quarkus.build.skip

[.description]
--
Skips the execution of this mojo
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-deploy-skipOriginalJarRename]] skipOriginalJarRename

[.description]
--
When the building an Uber JAR, the default JAR is renamed by adding .original suffix. Enabling this property will disable the renaming of the original JAR.
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-deploy-systemProperties]] systemProperties

[.description]
--
The list of system properties defined for the plugin.
--
|`Map`
|

|===

= quarkus:dev

The dev mojo, that runs a quarkus app in a forked process. A background compilation process is launched and any changes are automatically reflected in your running application. 
You can use this dev mode in a remote container environment with remote-dev.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-dev-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-dev-argsString]] argsString
|`String`
|`${quarkus.args}`

a| [[quarkus-maven-plugin-goal-dev-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-dev-compilerArgs]] compilerArgs

[.description]
--
Additional parameters to pass to javac when recompiling changed source files.
--
|`List`
|

a| [[quarkus-maven-plugin-goal-dev-compilerOptions]] compilerOptions

[.description]
--
Additional compiler arguments
--
|`List`
|

a| [[quarkus-maven-plugin-goal-dev-copySurefireVariables]] copySurefireVariables

[.description]
--
When enabled, the <environmentVariables> and <systemPropertyVariables> elements of the Maven Surefire plugin are copied to environment variables and system properties defined by this plugin. Note that no other Surefire configuration is used (notably <systemProperties>), only the 2 elements mentioned above. 
This plugin's <environmentVariables> and <systemProperties> have priority, so duplicate keys are not copied.

Since environment variables and system properties are global to the entire process, this also affects dev mode (when executed as quarkus:dev). Because of that, this copying action is disabled by default and requires opt-in.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-dev-debug]] debug

[.description]
--
If this server should be started in debug mode. The default is to start in debug mode and listen on port 5005. Whether the JVM is suspended waiting for a debugger to be attached, depends on the value of suspend. 
debug supports the following options: 
Value Effect 
false The JVM is not started in debug mode 
true The JVM is started in debug mode and will be listening on debugHost:debugPort 
client The JVM is started in client mode, and will attempt to connect to debugHost:debugPort 
{port} The JVM is started in debug mode and will be listening on debugHost:{port}. By default, debugHost has the value "localhost", and debugPort is 5005.
--
|`String`
|`${debug}`

a| [[quarkus-maven-plugin-goal-dev-debugHost]] debugHost
|`String`
|`${debugHost}`

a| [[quarkus-maven-plugin-goal-dev-debugPort]] debugPort
|`String`
|`${debugPort}`

a| [[quarkus-maven-plugin-goal-dev-deleteDevJar]] deleteDevJar
|`boolean`
|`TRUE`

a| [[quarkus-maven-plugin-goal-dev-enforceBuildGoal]] enforceBuildGoal

[.description]
--
Whether to enforce the quarkus-maven-plugin build goal to be configured. By default, a missing build goal is considered an inconsistency (although the build goal is not required technically). In this case a warning will be logged and the application will not be started.
--
|`boolean`
|`${quarkus.enforceBuildGoal}`

a| [[quarkus-maven-plugin-goal-dev-environmentVariables]] environmentVariables
|`Map`
|

a| [[quarkus-maven-plugin-goal-dev-extensionJvmOptions]] extensionJvmOptions

[.description]
--
Extension dev mode JVM option filter configuration. 
Allows disabling all JVM options configured by extensions, for example
<extensionJvmOptions> <!-- disable JVM options from all the extensions --> <disableAll>true</disableAll> </extensionJvmOptions>* or specifying a groupId:artifactId:classifier artifact pattern to disable options provided by the matching subset of extensions, for example <extensionJvmOptions> <disableFor> <!-- disable JVM options from all the extensions with groupId org.acme --> <extension>org.acme</extension> <!-- disable JVM options configured by io.quarkiverse:quarkus-magic --> <extension>io.quarkiverse:quarkus-magic</extension> </disableFor> </extensionJvmOptions>
--
|`ExtensionDevModeJvmOptionFilter`
|

a| [[quarkus-maven-plugin-goal-dev-forceC2]] forceC2

[.description]
--
This value is intended to be set to true when we want to require C2 compilation instead of preventing it from ever kicking in. Setting this will likely have a small negative effect on startup time and should only be done when it absolutely makes sense.
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-dev-jvmArgs]] jvmArgs

[.description]
--
Allows configuring arbitrary JVM arguments. Multiple arguments can be specified by delimiting them with a space character.
--
|`String`
|`${jvm.args}`

a| [[quarkus-maven-plugin-goal-dev-modules]] modules

[.description]
--
Allows configuring the modules to add to the application. The listed modules will be added using: --add-modules m1,m2....
--
|`List`
|`${add-modules}`

a| [[quarkus-maven-plugin-goal-dev-mojoExecution]] mojoExecution
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-dev-noDeps]] noDeps

[.description]
--
Whether changes in the projects that appear to be dependencies of the project containing the application to be launched should trigger hot-reload. By default, they do.
--
|`boolean`
|`${noDeps}`

a| [[quarkus-maven-plugin-goal-dev-openJavaLang]] openJavaLang
|`boolean`
|`${open-lang-package}`

a| [[quarkus-maven-plugin-goal-dev-outputDirectory]] outputDirectory

[.description]
--
The directory for compiled classes.
--
|`File` (required)
|`${project.build.outputDirectory}`

a| [[quarkus-maven-plugin-goal-dev-pluginRepos]] pluginRepos
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-dev-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-dev-release]] release

[.description]
--
The --release argument to javac.
--
|`String`
|`${maven.compiler.release}`

a| [[quarkus-maven-plugin-goal-dev-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-dev-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-dev-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-dev-skipPlugins]] skipPlugins

[.description]
--
A comma-separated list of Maven plugin keys in groupId:artifactId format (for example org.codehaus.mojo:flatten-maven-plugin and/or goal prefixes, (for example flatten) that should be skipped when quarkus:dev identifies Maven plugin goals that should be executed before the application is launched in dev mode. 
Only the flatten Maven plugin is skipped by default.
--
|`Set`
|`org.codehaus.mojo:flatten-maven-plugin`

a| [[quarkus-maven-plugin-goal-dev-source]] source

[.description]
--
The -source argument to javac.
--
|`String`
|`${maven.compiler.source}`

a| [[quarkus-maven-plugin-goal-dev-sourceDir]] sourceDir
|`File`
|`${project.build.sourceDirectory}`

a| [[quarkus-maven-plugin-goal-dev-suspend]] suspend

[.description]
--
Whether the JVM launch, in debug mode, should be suspended. This parameter is only relevant when the JVM is launched in debug mode. This parameter supports the following values (all the allowed values are case-insensitive): 
Value Effect 
y or true The debug mode JVM launch is suspended 
n or false The debug mode JVM is started without suspending
--
|`String`
|`${suspend}`

a| [[quarkus-maven-plugin-goal-dev-systemProperties]] systemProperties
|`Map`
|

a| [[quarkus-maven-plugin-goal-dev-target]] target

[.description]
--
The -target argument to javac.
--
|`String`
|`${maven.compiler.target}`

a| [[quarkus-maven-plugin-goal-dev-test]] test

[.description]
--
Selects given test(s) for continuous testing. This is an alternative to quarkus.test.include-pattern and quarkus.test.exclude-pattern; if set, the quarkus.test.[include\|exclude]-pattern configuration is ignored. 
The format of this configuration property is the same as the Maven Surefire -Dtest=... format <https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test>. Specifically: it is a comma (,) separated list of globs of class file paths and/or method names. Each glob can potentially be prefixed with an exclamation mark (!), which makes it an exclusion filter instead of an inclusion filter. Exclusions have higher priority than inclusions. The class file path glob is separated from the method name glob by the hash sign (#) and multiple method name globs may be present, separated by the plus sign (+).

For example:

* Basic*: all classes starting with Basic 
* ???Test: all classes named with 3 arbitrary characters followed by Test 
* !Unstable*: all classes except classes starting with Unstable 
* pkg/**/Ci*leTest: all classes in the package pkg and subpackages, starting with Ci and ending with leTest 
* *Test#test*One+testTwo?????: all classes ending with Test, and in them, only methods starting with test and ending with One, or starting with testTwo and followed by 5 arbitrary characters 
* #fast*+slowTest: all classes, and in them, only methods starting with fast or methods named slowTest Note that the syntax %regex[...] and %ant[...] is NOT supported.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-dev-quarkus.warnIfBuildGoalMissing]] quarkus.warnIfBuildGoalMissing
|`boolean`
|

a| [[quarkus-maven-plugin-goal-dev-watchedFiles]] watchedFiles

[.description]
--
Optional list of files to watch for changes that trigger a hot reload in dev mode. This is useful for extensions developers that can set this property to their extension's artifacts in their local repository.
--
|`List`
|

a| [[quarkus-maven-plugin-goal-dev-workingDir]] workingDir
|`File`
|

|===

= quarkus:generate-code

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-generate-code-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-generate-code-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-generate-code-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-generate-code-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-generate-code-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-generate-code-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-generate-code-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-generate-code-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-generate-code-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-generate-code-launchMode]] launchMode

[.description]
--
Application launch mode for which to generate the source code.
--
|`String`
|`NORMAL`

a| [[quarkus-maven-plugin-goal-generate-code-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-generate-code-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-generate-code-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-generate-code-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-generate-code-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-generate-code-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-generate-code-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-generate-code-quarkus.generate-code.skip]] quarkus.generate-code.skip

[.description]
--
Skip the execution of this mojo
--
|`boolean`
|`false`

|===

= quarkus:generate-code-tests

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-generate-code-tests-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-generate-code-tests-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-launchMode]] launchMode

[.description]
--
Application launch mode for which to generate the source code.
--
|`String`
|`NORMAL`

a| [[quarkus-maven-plugin-goal-generate-code-tests-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-generate-code-tests-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-quarkus.generate-code.serialize-test-model]] quarkus.generate-code.serialize-test-model

[.description]
--
A switch that enables or disables serialization of an io.quarkus.bootstrap.model.ApplicationModel to a file for tests. Deserializing an application model when bootstrapping Quarkus tests has a performance advantage in that the tests will not have to initialize a Maven resolver and re-resolve the application model, which may save, depending on a project, ~80-95% of time on io.quarkus.bootstrap.model.ApplicationModel resolution. 
Serialization of the test model is enabled by default.
--
|`boolean`
|`true`

a| [[quarkus-maven-plugin-goal-generate-code-tests-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-generate-code-tests-quarkus.generate-code.skip]] quarkus.generate-code.skip

[.description]
--
Skip the execution of this mojo
--
|`boolean`
|`false`

|===

= quarkus:go-offline

This goal downloads all the Maven artifact dependencies required to build, run, test and launch the application dev mode.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-go-offline-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-go-offline-mode]] mode

[.description]
--
Target launch mode corresponding to io.quarkus.runtime.LaunchMode for which the dependencies should be resolved. all is the default, since it includes both provided and test dependency scopes and also the dependencies required by dev mode.
--
|`String`
|`all`

a| [[quarkus-maven-plugin-goal-go-offline-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-go-offline-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-go-offline-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-go-offline-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:help

Display help information on quarkus-maven-plugin. 
Call mvn quarkus:help -Ddetail=true -Dgoal=<goal-name> to display parameter details.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-help-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-help-detail]] detail

[.description]
--
If true, display all settable properties for each goal.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-help-goal]] goal

[.description]
--
The name of the goal for which to show help. If unspecified, all goals will be displayed.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-help-indentSize]] indentSize

[.description]
--
The number of spaces per indentation level, should be positive.
--
|`int`
|`2`

a| [[quarkus-maven-plugin-goal-help-lineLength]] lineLength

[.description]
--
The maximum length of a display line, should be positive.
--
|`int`
|`80`

|===

= quarkus:image-build

Builds a container image.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-image-build-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-image-build-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-image-build-attachRunnerAsMainArtifact]] attachRunnerAsMainArtifact

[.description]
--
Whether to replace the original JAR with the Uber runner JAR as the main project artifact
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-build-attachSboms]] attachSboms

[.description]
--
Whether to attach SBOMs generated for Uber JARs as project artifacts
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-build-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-image-build-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-image-build-buildDirectory]] buildDirectory
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-image-build-quarkus.container-image.builder]] quarkus.container-image.builder
|`String`
|

a| [[quarkus-maven-plugin-goal-image-build-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-image-build-quarkus.container-image.dry-run]] quarkus.container-image.dry-run
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-build-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-image-build-generatedSourcesDirectory]] generatedSourcesDirectory

[.description]
--
The directory for generated source files.
--
|`File`
|`${project.build.directory}/generated-sources`

a| [[quarkus-maven-plugin-goal-image-build-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-image-build-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-image-build-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-image-build-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-image-build-pluginRepos]] pluginRepos

[.description]
--
The project's remote repositories to use for the resolution of plugins and their dependencies.
--
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-image-build-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-image-build-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-image-build-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-image-build-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-image-build-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-image-build-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-image-build-quarkus.build.skip]] quarkus.build.skip

[.description]
--
Skips the execution of this mojo
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-image-build-skipOriginalJarRename]] skipOriginalJarRename

[.description]
--
When the building an Uber JAR, the default JAR is renamed by adding .original suffix. Enabling this property will disable the renaming of the original JAR.
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-build-systemProperties]] systemProperties

[.description]
--
The list of system properties defined for the plugin.
--
|`Map`
|

|===

= quarkus:image-push

Pushes a container image.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-image-push-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-image-push-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-image-push-attachRunnerAsMainArtifact]] attachRunnerAsMainArtifact

[.description]
--
Whether to replace the original JAR with the Uber runner JAR as the main project artifact
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-push-attachSboms]] attachSboms

[.description]
--
Whether to attach SBOMs generated for Uber JARs as project artifacts
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-push-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-image-push-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-image-push-buildDirectory]] buildDirectory
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-image-push-quarkus.container-image.builder]] quarkus.container-image.builder
|`String`
|

a| [[quarkus-maven-plugin-goal-image-push-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-image-push-quarkus.container-image.dry-run]] quarkus.container-image.dry-run
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-push-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-image-push-generatedSourcesDirectory]] generatedSourcesDirectory

[.description]
--
The directory for generated source files.
--
|`File`
|`${project.build.directory}/generated-sources`

a| [[quarkus-maven-plugin-goal-image-push-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-image-push-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-image-push-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-image-push-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-image-push-pluginRepos]] pluginRepos

[.description]
--
The project's remote repositories to use for the resolution of plugins and their dependencies.
--
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-image-push-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-image-push-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-image-push-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-image-push-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-image-push-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-image-push-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-image-push-quarkus.build.skip]] quarkus.build.skip

[.description]
--
Skips the execution of this mojo
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-image-push-skipOriginalJarRename]] skipOriginalJarRename

[.description]
--
When the building an Uber JAR, the default JAR is renamed by adding .original suffix. Enabling this property will disable the renaming of the original JAR.
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-image-push-systemProperties]] systemProperties

[.description]
--
The list of system properties defined for the plugin.
--
|`Map`
|

|===

= quarkus:info

Log Quarkus-specific project information, such as imported Quarkus platform BOMs, Quarkus extensions found among the project dependencies, etc.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-info-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-info-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-info-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-info-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-info-perModule]] perModule

[.description]
--
If true, the information will be logged per each relevant module of the project instead of an overall summary
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-info-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-info-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-info-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-info-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-info-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:list-categories

List extension categories, which a user can use to filter extensions.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-list-categories-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-list-categories-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-list-categories-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-list-categories-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-list-categories-format]] format

[.description]
--
Select the output format among 'name' (display the name only) and 'full' (includes a verbose name and a description).
--
|`String`
|`concise`

a| [[quarkus-maven-plugin-goal-list-categories-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-list-categories-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-list-categories-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-list-categories-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-list-categories-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:list-extensions

List the available extensions. You can add one or several extensions in one go, with the 2 following mojos: add-extensions and add-extension. You can list all extension or just installable. Choose between 3 output formats: name, concise and full.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-list-extensions-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-list-extensions-all]] all

[.description]
--
List all extensions or just the installable.
--
|`boolean`
|`true`

a| [[quarkus-maven-plugin-goal-list-extensions-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-list-extensions-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-list-extensions-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-list-extensions-category]] category

[.description]
--
Only list extensions from given category.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-list-extensions-format]] format

[.description]
--
Select the output format among 'id' (display the artifactId only), 'concise' (display name and artifactId), 'origins' (display extension catalog IDs providing extension information), 'support-scope' (support scope associated with each extension, if any) and 'full' (concise format and version related columns).
--
|`String`
|`concise`

a| [[quarkus-maven-plugin-goal-list-extensions-installed]] installed

[.description]
--
List the already installed extensions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-list-extensions-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-list-extensions-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-list-extensions-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-list-extensions-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-list-extensions-searchPattern]] searchPattern

[.description]
--
Search filter on extension list. The format is based on Java Pattern.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-list-extensions-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:list-platforms

List imported and optionally other platforms available for the project.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-list-platforms-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-list-platforms-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-list-platforms-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-list-platforms-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-list-platforms-installed]] installed

[.description]
--
List the already installed extensions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-list-platforms-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-list-platforms-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-list-platforms-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-list-platforms-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-list-platforms-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:native-image-agent

Post-processes native image agent generated configuration to trim any unnecessary configuration.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-native-image-agent-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-native-image-agent-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-native-image-agent-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-native-image-agent-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-native-image-agent-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-native-image-agent-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-native-image-agent-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-native-image-agent-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-native-image-agent-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:prepare

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-prepare-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-prepare-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-prepare-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-prepare-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-prepare-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-prepare-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-prepare-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-prepare-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-prepare-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-prepare-launchMode]] launchMode

[.description]
--
Application launch mode for which to generate the source code.
--
|`String`
|`NORMAL`

a| [[quarkus-maven-plugin-goal-prepare-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-prepare-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-prepare-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-prepare-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-prepare-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-prepare-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-prepare-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-prepare-quarkus.generate-code.skip]] quarkus.generate-code.skip

[.description]
--
Skip the execution of this mojo
--
|`boolean`
|`false`

|===

= quarkus:prepare-tests

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-prepare-tests-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-prepare-tests-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-prepare-tests-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-prepare-tests-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-launchMode]] launchMode

[.description]
--
Application launch mode for which to generate the source code.
--
|`String`
|`NORMAL`

a| [[quarkus-maven-plugin-goal-prepare-tests-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-prepare-tests-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-prepare-tests-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-prepare-tests-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-prepare-tests-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-prepare-tests-quarkus.generate-code.serialize-test-model]] quarkus.generate-code.serialize-test-model

[.description]
--
A switch that enables or disables serialization of an io.quarkus.bootstrap.model.ApplicationModel to a file for tests. Deserializing an application model when bootstrapping Quarkus tests has a performance advantage in that the tests will not have to initialize a Maven resolver and re-resolve the application model, which may save, depending on a project, ~80-95% of time on io.quarkus.bootstrap.model.ApplicationModel resolution. 
Serialization of the test model is enabled by default.
--
|`boolean`
|`true`

a| [[quarkus-maven-plugin-goal-prepare-tests-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-prepare-tests-quarkus.generate-code.skip]] quarkus.generate-code.skip

[.description]
--
Skip the execution of this mojo
--
|`boolean`
|`false`

|===

= quarkus:remote-dev

The dev mojo, that connects to a remote host.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-remote-dev-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-remote-dev-argsString]] argsString
|`String`
|`${quarkus.args}`

a| [[quarkus-maven-plugin-goal-remote-dev-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-remote-dev-compilerArgs]] compilerArgs

[.description]
--
Additional parameters to pass to javac when recompiling changed source files.
--
|`List`
|

a| [[quarkus-maven-plugin-goal-remote-dev-compilerOptions]] compilerOptions

[.description]
--
Additional compiler arguments
--
|`List`
|

a| [[quarkus-maven-plugin-goal-remote-dev-copySurefireVariables]] copySurefireVariables

[.description]
--
When enabled, the <environmentVariables> and <systemPropertyVariables> elements of the Maven Surefire plugin are copied to environment variables and system properties defined by this plugin. Note that no other Surefire configuration is used (notably <systemProperties>), only the 2 elements mentioned above. 
This plugin's <environmentVariables> and <systemProperties> have priority, so duplicate keys are not copied.

Since environment variables and system properties are global to the entire process, this also affects dev mode (when executed as quarkus:dev). Because of that, this copying action is disabled by default and requires opt-in.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-remote-dev-debug]] debug

[.description]
--
If this server should be started in debug mode. The default is to start in debug mode and listen on port 5005. Whether the JVM is suspended waiting for a debugger to be attached, depends on the value of suspend. 
debug supports the following options: 
Value Effect 
false The JVM is not started in debug mode 
true The JVM is started in debug mode and will be listening on debugHost:debugPort 
client The JVM is started in client mode, and will attempt to connect to debugHost:debugPort 
{port} The JVM is started in debug mode and will be listening on debugHost:{port}. By default, debugHost has the value "localhost", and debugPort is 5005.
--
|`String`
|`${debug}`

a| [[quarkus-maven-plugin-goal-remote-dev-debugHost]] debugHost
|`String`
|`${debugHost}`

a| [[quarkus-maven-plugin-goal-remote-dev-debugPort]] debugPort
|`String`
|`${debugPort}`

a| [[quarkus-maven-plugin-goal-remote-dev-deleteDevJar]] deleteDevJar
|`boolean`
|`TRUE`

a| [[quarkus-maven-plugin-goal-remote-dev-enforceBuildGoal]] enforceBuildGoal

[.description]
--
Whether to enforce the quarkus-maven-plugin build goal to be configured. By default, a missing build goal is considered an inconsistency (although the build goal is not required technically). In this case a warning will be logged and the application will not be started.
--
|`boolean`
|`${quarkus.enforceBuildGoal}`

a| [[quarkus-maven-plugin-goal-remote-dev-environmentVariables]] environmentVariables
|`Map`
|

a| [[quarkus-maven-plugin-goal-remote-dev-extensionJvmOptions]] extensionJvmOptions

[.description]
--
Extension dev mode JVM option filter configuration. 
Allows disabling all JVM options configured by extensions, for example
<extensionJvmOptions> <!-- disable JVM options from all the extensions --> <disableAll>true</disableAll> </extensionJvmOptions>* or specifying a groupId:artifactId:classifier artifact pattern to disable options provided by the matching subset of extensions, for example <extensionJvmOptions> <disableFor> <!-- disable JVM options from all the extensions with groupId org.acme --> <extension>org.acme</extension> <!-- disable JVM options configured by io.quarkiverse:quarkus-magic --> <extension>io.quarkiverse:quarkus-magic</extension> </disableFor> </extensionJvmOptions>
--
|`ExtensionDevModeJvmOptionFilter`
|

a| [[quarkus-maven-plugin-goal-remote-dev-forceC2]] forceC2

[.description]
--
This value is intended to be set to true when we want to require C2 compilation instead of preventing it from ever kicking in. Setting this will likely have a small negative effect on startup time and should only be done when it absolutely makes sense.
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-remote-dev-jvmArgs]] jvmArgs

[.description]
--
Allows configuring arbitrary JVM arguments. Multiple arguments can be specified by delimiting them with a space character.
--
|`String`
|`${jvm.args}`

a| [[quarkus-maven-plugin-goal-remote-dev-modules]] modules

[.description]
--
Allows configuring the modules to add to the application. The listed modules will be added using: --add-modules m1,m2....
--
|`List`
|`${add-modules}`

a| [[quarkus-maven-plugin-goal-remote-dev-mojoExecution]] mojoExecution
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-remote-dev-noDeps]] noDeps

[.description]
--
Whether changes in the projects that appear to be dependencies of the project containing the application to be launched should trigger hot-reload. By default, they do.
--
|`boolean`
|`${noDeps}`

a| [[quarkus-maven-plugin-goal-remote-dev-openJavaLang]] openJavaLang
|`boolean`
|`${open-lang-package}`

a| [[quarkus-maven-plugin-goal-remote-dev-outputDirectory]] outputDirectory

[.description]
--
The directory for compiled classes.
--
|`File` (required)
|`${project.build.outputDirectory}`

a| [[quarkus-maven-plugin-goal-remote-dev-pluginRepos]] pluginRepos
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-remote-dev-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-remote-dev-release]] release

[.description]
--
The --release argument to javac.
--
|`String`
|`${maven.compiler.release}`

a| [[quarkus-maven-plugin-goal-remote-dev-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-remote-dev-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-remote-dev-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-remote-dev-skipPlugins]] skipPlugins

[.description]
--
A comma-separated list of Maven plugin keys in groupId:artifactId format (for example org.codehaus.mojo:flatten-maven-plugin and/or goal prefixes, (for example flatten) that should be skipped when quarkus:dev identifies Maven plugin goals that should be executed before the application is launched in dev mode. 
Only the flatten Maven plugin is skipped by default.
--
|`Set`
|`org.codehaus.mojo:flatten-maven-plugin`

a| [[quarkus-maven-plugin-goal-remote-dev-source]] source

[.description]
--
The -source argument to javac.
--
|`String`
|`${maven.compiler.source}`

a| [[quarkus-maven-plugin-goal-remote-dev-sourceDir]] sourceDir
|`File`
|`${project.build.sourceDirectory}`

a| [[quarkus-maven-plugin-goal-remote-dev-suspend]] suspend

[.description]
--
Whether the JVM launch, in debug mode, should be suspended. This parameter is only relevant when the JVM is launched in debug mode. This parameter supports the following values (all the allowed values are case-insensitive): 
Value Effect 
y or true The debug mode JVM launch is suspended 
n or false The debug mode JVM is started without suspending
--
|`String`
|`${suspend}`

a| [[quarkus-maven-plugin-goal-remote-dev-systemProperties]] systemProperties
|`Map`
|

a| [[quarkus-maven-plugin-goal-remote-dev-target]] target

[.description]
--
The -target argument to javac.
--
|`String`
|`${maven.compiler.target}`

a| [[quarkus-maven-plugin-goal-remote-dev-test]] test

[.description]
--
Selects given test(s) for continuous testing. This is an alternative to quarkus.test.include-pattern and quarkus.test.exclude-pattern; if set, the quarkus.test.[include\|exclude]-pattern configuration is ignored. 
The format of this configuration property is the same as the Maven Surefire -Dtest=... format <https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test>. Specifically: it is a comma (,) separated list of globs of class file paths and/or method names. Each glob can potentially be prefixed with an exclamation mark (!), which makes it an exclusion filter instead of an inclusion filter. Exclusions have higher priority than inclusions. The class file path glob is separated from the method name glob by the hash sign (#) and multiple method name globs may be present, separated by the plus sign (+).

For example:

* Basic*: all classes starting with Basic 
* ???Test: all classes named with 3 arbitrary characters followed by Test 
* !Unstable*: all classes except classes starting with Unstable 
* pkg/**/Ci*leTest: all classes in the package pkg and subpackages, starting with Ci and ending with leTest 
* *Test#test*One+testTwo?????: all classes ending with Test, and in them, only methods starting with test and ending with One, or starting with testTwo and followed by 5 arbitrary characters 
* #fast*+slowTest: all classes, and in them, only methods starting with fast or methods named slowTest Note that the syntax %regex[...] and %ant[...] is NOT supported.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-remote-dev-quarkus.warnIfBuildGoalMissing]] quarkus.warnIfBuildGoalMissing
|`boolean`
|

a| [[quarkus-maven-plugin-goal-remote-dev-watchedFiles]] watchedFiles

[.description]
--
Optional list of files to watch for changes that trigger a hot reload in dev mode. This is useful for extensions developers that can set this property to their extension's artifacts in their local repository.
--
|`List`
|

a| [[quarkus-maven-plugin-goal-remote-dev-workingDir]] workingDir
|`File`
|

|===

= quarkus:remove-extension

Allow removing an extension from an existing pom.xml file. Because you can remove one or several extension in one go, there are 2 mojos: remove-extensions and remove-extension. Both supports the extension and extensions parameters.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-remove-extension-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-remove-extension-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extension-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extension-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extension-extension]] extension

[.description]
--
For usability reason, this parameter allows removing a single extension.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extension-extensions]] extensions

[.description]
--
The list of extensions to be removed.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-remove-extension-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-remove-extension-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-remove-extension-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-remove-extension-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-remove-extension-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:remove-extensions

Allow removing extensions to an existing pom.xml file. Because you can remove one or several extension in one go, there are 2 mojos: remove-extensions and remove-extension. Both supports the extension and extensions parameters.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-remove-extensions-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-remove-extensions-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extensions-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extensions-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extensions-extension]] extension

[.description]
--
For usability reason, this parameter allows removing a single extension.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-remove-extensions-extensions]] extensions

[.description]
--
The list of extensions to be removed.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-remove-extensions-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-remove-extensions-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-remove-extensions-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-remove-extensions-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-remove-extensions-session]] session
|`MavenSession`
|`${session}`

|===

= quarkus:run

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-run-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-run-additionalSystemProperties]] additionalSystemProperties

[.description]
--
Additional system properties meant to be passed on the command line in a formal like -DsysProps=prop1=val1,prop2=val2
--
|`String`
|`${sysProps}`

a| [[quarkus-maven-plugin-goal-run-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-run-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-run-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-run-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-run-environmentVariables]] environmentVariables

[.description]
--
The list of environment variables with which the process will be launched. To be specified in a format like -DenvVars=VAR1=val1,VAR2=val2
--
|`String`
|`${envVars}`

a| [[quarkus-maven-plugin-goal-run-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-run-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-run-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-run-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-run-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-run-programArguments]] programArguments

[.description]
--
The list of program arguments with which the process will be launched. To be specified in a format like -Dargs=1,2,k=v
--
|`String`
|`${args}`

a| [[quarkus-maven-plugin-goal-run-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-run-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-run-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-run-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-run-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-run-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-run-systemProperties]] systemProperties

[.description]
--
The list of system properties defined for the plugin.
--
|`Map`
|

|===

= quarkus:test

The test mojo, that starts continuous testing outside of dev mode

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-test-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-test-argsString]] argsString
|`String`
|`${quarkus.args}`

a| [[quarkus-maven-plugin-goal-test-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-test-compilerArgs]] compilerArgs

[.description]
--
Additional parameters to pass to javac when recompiling changed source files.
--
|`List`
|

a| [[quarkus-maven-plugin-goal-test-compilerOptions]] compilerOptions

[.description]
--
Additional compiler arguments
--
|`List`
|

a| [[quarkus-maven-plugin-goal-test-copySurefireVariables]] copySurefireVariables

[.description]
--
When enabled, the <environmentVariables> and <systemPropertyVariables> elements of the Maven Surefire plugin are copied to environment variables and system properties defined by this plugin. Note that no other Surefire configuration is used (notably <systemProperties>), only the 2 elements mentioned above. 
This plugin's <environmentVariables> and <systemProperties> have priority, so duplicate keys are not copied.

Since environment variables and system properties are global to the entire process, this also affects dev mode (when executed as quarkus:dev). Because of that, this copying action is disabled by default and requires opt-in.
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-test-debug]] debug

[.description]
--
If this server should be started in debug mode. The default is to start in debug mode and listen on port 5005. Whether the JVM is suspended waiting for a debugger to be attached, depends on the value of suspend. 
debug supports the following options: 
Value Effect 
false The JVM is not started in debug mode 
true The JVM is started in debug mode and will be listening on debugHost:debugPort 
client The JVM is started in client mode, and will attempt to connect to debugHost:debugPort 
{port} The JVM is started in debug mode and will be listening on debugHost:{port}. By default, debugHost has the value "localhost", and debugPort is 5005.
--
|`String`
|`${debug}`

a| [[quarkus-maven-plugin-goal-test-debugHost]] debugHost
|`String`
|`${debugHost}`

a| [[quarkus-maven-plugin-goal-test-debugPort]] debugPort
|`String`
|`${debugPort}`

a| [[quarkus-maven-plugin-goal-test-deleteDevJar]] deleteDevJar
|`boolean`
|`TRUE`

a| [[quarkus-maven-plugin-goal-test-enforceBuildGoal]] enforceBuildGoal

[.description]
--
Whether to enforce the quarkus-maven-plugin build goal to be configured. By default, a missing build goal is considered an inconsistency (although the build goal is not required technically). In this case a warning will be logged and the application will not be started.
--
|`boolean`
|`${quarkus.enforceBuildGoal}`

a| [[quarkus-maven-plugin-goal-test-environmentVariables]] environmentVariables
|`Map`
|

a| [[quarkus-maven-plugin-goal-test-extensionJvmOptions]] extensionJvmOptions

[.description]
--
Extension dev mode JVM option filter configuration. 
Allows disabling all JVM options configured by extensions, for example
<extensionJvmOptions> <!-- disable JVM options from all the extensions --> <disableAll>true</disableAll> </extensionJvmOptions>* or specifying a groupId:artifactId:classifier artifact pattern to disable options provided by the matching subset of extensions, for example <extensionJvmOptions> <disableFor> <!-- disable JVM options from all the extensions with groupId org.acme --> <extension>org.acme</extension> <!-- disable JVM options configured by io.quarkiverse:quarkus-magic --> <extension>io.quarkiverse:quarkus-magic</extension> </disableFor> </extensionJvmOptions>
--
|`ExtensionDevModeJvmOptionFilter`
|

a| [[quarkus-maven-plugin-goal-test-forceC2]] forceC2

[.description]
--
This value is intended to be set to true when we want to require C2 compilation instead of preventing it from ever kicking in. Setting this will likely have a small negative effect on startup time and should only be done when it absolutely makes sense.
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-test-jvmArgs]] jvmArgs

[.description]
--
Allows configuring arbitrary JVM arguments. Multiple arguments can be specified by delimiting them with a space character.
--
|`String`
|`${jvm.args}`

a| [[quarkus-maven-plugin-goal-test-modules]] modules

[.description]
--
Allows configuring the modules to add to the application. The listed modules will be added using: --add-modules m1,m2....
--
|`List`
|`${add-modules}`

a| [[quarkus-maven-plugin-goal-test-mojoExecution]] mojoExecution
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-test-noDeps]] noDeps

[.description]
--
Whether changes in the projects that appear to be dependencies of the project containing the application to be launched should trigger hot-reload. By default, they do.
--
|`boolean`
|`${noDeps}`

a| [[quarkus-maven-plugin-goal-test-openJavaLang]] openJavaLang
|`boolean`
|`${open-lang-package}`

a| [[quarkus-maven-plugin-goal-test-outputDirectory]] outputDirectory

[.description]
--
The directory for compiled classes.
--
|`File` (required)
|`${project.build.outputDirectory}`

a| [[quarkus-maven-plugin-goal-test-pluginRepos]] pluginRepos
|`List` (required)
|`${project.remotePluginRepositories}`

a| [[quarkus-maven-plugin-goal-test-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-test-release]] release

[.description]
--
The --release argument to javac.
--
|`String`
|`${maven.compiler.release}`

a| [[quarkus-maven-plugin-goal-test-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-test-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-test-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-test-skipPlugins]] skipPlugins

[.description]
--
A comma-separated list of Maven plugin keys in groupId:artifactId format (for example org.codehaus.mojo:flatten-maven-plugin and/or goal prefixes, (for example flatten) that should be skipped when quarkus:dev identifies Maven plugin goals that should be executed before the application is launched in dev mode. 
Only the flatten Maven plugin is skipped by default.
--
|`Set`
|`org.codehaus.mojo:flatten-maven-plugin`

a| [[quarkus-maven-plugin-goal-test-source]] source

[.description]
--
The -source argument to javac.
--
|`String`
|`${maven.compiler.source}`

a| [[quarkus-maven-plugin-goal-test-sourceDir]] sourceDir
|`File`
|`${project.build.sourceDirectory}`

a| [[quarkus-maven-plugin-goal-test-suspend]] suspend

[.description]
--
Whether the JVM launch, in debug mode, should be suspended. This parameter is only relevant when the JVM is launched in debug mode. This parameter supports the following values (all the allowed values are case-insensitive): 
Value Effect 
y or true The debug mode JVM launch is suspended 
n or false The debug mode JVM is started without suspending
--
|`String`
|`${suspend}`

a| [[quarkus-maven-plugin-goal-test-systemProperties]] systemProperties
|`Map`
|

a| [[quarkus-maven-plugin-goal-test-target]] target

[.description]
--
The -target argument to javac.
--
|`String`
|`${maven.compiler.target}`

a| [[quarkus-maven-plugin-goal-test-test]] test

[.description]
--
Selects given test(s) for continuous testing. This is an alternative to quarkus.test.include-pattern and quarkus.test.exclude-pattern; if set, the quarkus.test.[include\|exclude]-pattern configuration is ignored. 
The format of this configuration property is the same as the Maven Surefire -Dtest=... format <https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test>. Specifically: it is a comma (,) separated list of globs of class file paths and/or method names. Each glob can potentially be prefixed with an exclamation mark (!), which makes it an exclusion filter instead of an inclusion filter. Exclusions have higher priority than inclusions. The class file path glob is separated from the method name glob by the hash sign (#) and multiple method name globs may be present, separated by the plus sign (+).

For example:

* Basic*: all classes starting with Basic 
* ???Test: all classes named with 3 arbitrary characters followed by Test 
* !Unstable*: all classes except classes starting with Unstable 
* pkg/**/Ci*leTest: all classes in the package pkg and subpackages, starting with Ci and ending with leTest 
* *Test#test*One+testTwo?????: all classes ending with Test, and in them, only methods starting with test and ending with One, or starting with testTwo and followed by 5 arbitrary characters 
* #fast*+slowTest: all classes, and in them, only methods starting with fast or methods named slowTest Note that the syntax %regex[...] and %ant[...] is NOT supported.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-test-quarkus.warnIfBuildGoalMissing]] quarkus.warnIfBuildGoalMissing
|`boolean`
|

a| [[quarkus-maven-plugin-goal-test-watchedFiles]] watchedFiles

[.description]
--
Optional list of files to watch for changes that trigger a hot reload in dev mode. This is useful for extensions developers that can set this property to their extension's artifacts in their local repository.
--
|`List`
|

a| [[quarkus-maven-plugin-goal-test-workingDir]] workingDir
|`File`
|

|===

= quarkus:track-config-changes

Maven goal that is executed before the BuildMojo. The goal looks for a file that contains build time configuration options read during the previous build. If that file exists, the goal will check whether the configuration options used during the previous build have changed in the current configuration and will persist their current values to another file, so that both configuration files could be compared by tools caching build goal outcomes to check whether the previous outcome of the BuildMojo needs to be rebuilt.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-track-config-changes-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-track-config-changes-appArtifact]] appArtifact

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format:

groupId:artifactId:classifier:type:version

With the classifier, type and version being optional.

If the type is missing, the artifact is assumed to be of type JAR.

If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates.

However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version.

If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-bootstrapId]] bootstrapId

[.description]
--
Application bootstrap provider ID. This parameter is not supposed to be configured by the user. To be able to re-use an application bootstrapped in one phase in a later phase, there needs to be a way to identify the correct instance of the bootstrapped application (in case there are more than one) in each Mojo. A bootstrap ID serves this purpose. This parameter is set in DevMojo invoking generate-code and generate-code-tests goals. If this parameter is not configured, a Mojo execution ID will be used as the bootstrap ID.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-buildDir]] buildDir
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkusCloseBootstrappedApp]] quarkusCloseBootstrappedApp

[.description]
--
Whether to close the bootstrapped applications after the execution
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.track-config-changes.dependencies-file]] quarkus.track-config-changes.dependencies-file

[.description]
--
Dependency dump file
--
|`File`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.track-config-changes.dump-current-when-recorded-unavailable]] quarkus.track-config-changes.dump-current-when-recorded-unavailable

[.description]
--
Whether to dump the current build configuration in case the configuration from the previous build isn't found
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.track-config-changes.dump-dependencies]] quarkus.track-config-changes.dump-dependencies

[.description]
--
Whether to dump Quarkus application dependencies along with their checksums
--
|`boolean`
|`true`

a| [[quarkus-maven-plugin-goal-track-config-changes-finalName]] finalName
|`String`
|`${project.build.finalName}`

a| [[quarkus-maven-plugin-goal-track-config-changes-ignoredEntries]] ignoredEntries

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: <configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration>
--
|`String[]`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-manifestEntries]] manifestEntries

[.description]
--
The list of main manifest attributes
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-manifestSections]] manifestSections

[.description]
--
The list of manifest sections
--
|`List`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-launchMode]] launchMode
|`String`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-mojoExecution]] mojoExecution

[.description]
--
The context of the execution of the plugin.
--
|`MojoExecution` (required)
|`${mojoExecution}`

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.track-config-changes.outputDirectory]] quarkus.track-config-changes.outputDirectory
|`File`
|`${project.build.directory}`

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.track-config-changes.outputFile]] quarkus.track-config-changes.outputFile
|`File`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-project]] project
|`MavenProject` (required)
|`${project}`

a| [[quarkus-maven-plugin-goal-track-config-changes-properties]] properties

[.description]
--
The properties of the plugin.
--
|`Map`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.recorded-build-config.directory]] quarkus.recorded-build-config.directory
|`File`
|`${basedir}/.quarkus`

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.recorded-build-config.file]] quarkus.recorded-build-config.file
|`String`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-reloadPoms]] reloadPoms

[.description]
--
POM files from the workspace that should be reloaded from the disk instead of taken from the Maven reactor. This parameter is not supposed to be configured by a user.
--
|`Set`
|

a| [[quarkus-maven-plugin-goal-track-config-changes-repoSession]] repoSession

[.description]
--
The current repository/network configuration of Maven.
--
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-track-config-changes-repos]] repos

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-track-config-changes-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-track-config-changes-quarkus.track-config-changes.skip]] quarkus.track-config-changes.skip

[.description]
--
Skip the execution of this mojo
--
|`boolean`
|`false`

|===

= quarkus:update

Suggest project updates and create a recipe with the possibility to apply it.

[.configuration-reference, cols="70,15,15"]
|===

h|[[quarkus-maven-plugin-goal-update-parameter-table]] Parameter
h|Type
h|Default value

a| [[quarkus-maven-plugin-goal-update-bomArtifactId]] bomArtifactId
|`String`
|

a| [[quarkus-maven-plugin-goal-update-bomGroupId]] bomGroupId
|`String`
|

a| [[quarkus-maven-plugin-goal-update-bomVersion]] bomVersion
|`String`
|

a| [[quarkus-maven-plugin-goal-update-noRewrite]] noRewrite

[.description]
--
Disable the rewrite feature. Deprecated: use -Drewrite=false instead
--
|`Boolean`
|`false`

a| [[quarkus-maven-plugin-goal-update-perModule]] perModule

[.description]
--
Deprecated: this option was unused
--
|`boolean`
|

a| [[quarkus-maven-plugin-goal-update-platformVersion]] platformVersion

[.description]
--
Version of the target platform (e.g: 2.0.0.Final) You may instead use stream to target the latest version of a specific platform stream.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-update-project]] project
|`MavenProject`
|`${project}`

a| [[quarkus-maven-plugin-goal-update-refresh]] refresh

[.description]
--
Whether to refresh the local extension catalog cache before searching for the recommended Quarkus extension versions
--
|`boolean`
|`false`

a| [[quarkus-maven-plugin-goal-update-repoSession]] repoSession
|`RepositorySystemSession`
|`${repositorySystemSession}`

a| [[quarkus-maven-plugin-goal-update-repos]] repos
|`List` (required)
|`${project.remoteProjectRepositories}`

a| [[quarkus-maven-plugin-goal-update-rewrite]] rewrite

[.description]
--
Run the suggested update recipe for this project.
--
|`Boolean`
|

a| [[quarkus-maven-plugin-goal-update-additionalUpdateRecipes]] additionalUpdateRecipes

[.description]
--
Specify a list of additional artifacts (GAV) containing rewrite recipes
--
|`String`
|

a| [[quarkus-maven-plugin-goal-update-rewriteDryRun]] rewriteDryRun

[.description]
--
Do a dry run the suggested update recipe for this project.
--
|`Boolean`
|`false`

a| [[quarkus-maven-plugin-goal-update-rewritePluginVersion]] rewritePluginVersion

[.description]
--
The OpenRewrite plugin version
--
|`String`
|

a| [[quarkus-maven-plugin-goal-update-quarkusUpdateRecipes]] quarkusUpdateRecipes

[.description]
--
Use custom io.quarkus:quarkus-update-recipes:LATEST coords (GAV) or just provide the version. This artifact should contain the base Quarkus update recipes to update a project.
--
|`String`
|

a| [[quarkus-maven-plugin-goal-update-session]] session
|`MavenSession`
|`${session}`

a| [[quarkus-maven-plugin-goal-update-stream]] stream

[.description]
--
Target stream (e.g: 2.0)
--
|`String`
|

|===

