---
layout: community
permalink: /publications/
---
include::../attributes.adoc[]
= {project-name} - Publications

Below is a list of articles, blogs, podcast and other tidbits published online around Quarkus.

[%header,format=csv]
|===
Date, Title,Author, Affiliation, Kind
2019-06-08, http://www.adam-bien.com/roller/abien/entry/quarkus_is_the_opposite_of[Quarkus is the opposite of WildFly], Adam Bien/Dimitris Andreadis, Adam Bien, Podcast
2019-09-03, http://adambien.blog/roller/abien/entry/the_first_line_of_quarkus[The First Line of Quarkuus], Adam Bien/Emmanuel Bernard, Adam Bien, Podcast
2019-07-30, https://www.instana.com/blog/quarkus-and-instana-lightspeed-monitoring-for-supersonic-java/[Quarkus and Instana: Lightspeed Monitoring for Supersonic Java], Chis Engelbert, Instana, Article 
2019-04-16, https://thenewstack.io/red-hats-quarkus-brings-natively-compiled-java-to-kubernetes[Red Hat's Quarkus Brings Natively Compiled Java to Kubernetes], Mike Melanson, TheNewStack, Article 
2019-09-13, https://www.youtube.com/watch?time_continue=42&v=oJx2Dd8yrG4[Turbocharged Java with Quarkus], Marcus Biel/Adam Bien, JakartaOne/Eclipse Foundation, Video
2019-09-19, https://www.youtube.com/watch?v=pqMIDJ58Fco[Getting started with Quarkus and Kogito], ??, ??, Video
2019-08-29, https://dzone.com/articles/quick-guide-to-microservices-with-quarkus-on-opens[Quick Guide to Microservices With Quarkus on OpenShift], Piotr Mińkowski, DZone, Article
2019-04-19, https://dzone.com/articles/thoughts-on-quarkus[Thoughts on Quarkus], Sebastian Daschner, Dzone, Article
2019-03-12, https://brunobat.com/2019/03/12/tomee-vs-spring-boot-vs-quarkus/[TomEE vs SpringBoot vs Quarkus], Bruno Baptista, Personal, Blog
2019-08-13, https://www.baeldung.com/quarkus-io[Guide to QuarkusIO], Rodrigo Graciano, Baeldung, Blog
2019-08-13, https://opensourceforu.com/2019/08/quarkus-supersonic-and-subatomic/[Quarkus Supersonic and Subatomic], Jaydeep Chakrabarty, opensourceforu.com, Article
2019-03-25, https://www.infoq.com/news/2019/03/redhat-release-quarkus/[Quarkus - a Kubernetes Native Java Framework], Diogo Carleto, InfoQ, Article
2019-07-03, https://developers.redhat.com/blog/2019/03/07/quarkus-next-generation-kubernetes-native-java-framework/[Introducing Quarkus: a next-generation Kubernetes  native Java Frameowrk], Jason Greene, Red Hat, Blog
|===
