---
layout: vision
permalink: /vision/standards
---
include::../attributes.adoc[]

= {project-name} - Our View on Standards

Let's go to the quark of things.
We don't want you to spend hours learning new technologies.
Instead, {project-name} provides leading frameworks and technologies from open source projects, such as
https://vertx.io[Vert.x], https://camel.apache.org[Camel], http://hibernate.org[Hibernate] and
https://resteasy.github.io[RESTEasy]. You can also find innovative community projects, such as
https://smallrye.io[SmallRye]. If you are looking for standards you can find https://microprofile.io[MicroProfile]
and selected specifications from https://jakarta.ee[Jakarta EE].

Our dependency injection solution is based on CDI with Arc.

You can use JAX-RS annotations to define the REST endpoints with https://resteasy.github.io[RESTEasy].

You can use JPA annotations to map your persistent entities and JTA annotations to declare the transaction boundaries
with http://hibernate.org[Hibernate]

You can use https://smallrye.io[SmallRye] to configure, secure, document and monitor your application.

You can use https://vertx.io[Vert.x] or https://camel.apache.org[Camel], and we support much more.

Of course, {project-name} is not a passive consumer. Our goal is to improve and innovate the technologies we use and
contribute back to the open source projects and standards we rely on.
