include::../attributes.adoc[]
= {project-name} - Our View on Standards

Let's go to the quark of things.
We don't want you to spend hours learning new technologies.
Instead, the {project-name} programming model builds on top of proven standards.
Be it official standards such as Eclipse MicroProfile or leading frameworks in a specific domain such as Eclipse Vert.x.

Our dependency injection solution is based on CDI.
You can use JAX-RS annotations to define the REST endpoints.
You can use JPA annotations to map your persistent entities and JTA annotations to declare the transaction boundaries.
You can use Eclipse MicroProfile to configure and monitor your application.
You can use Vert.x, Apache Camel and we support much more.

Since we're not limited to standards we can go beyond and extend your possibilities.
Of course, {project-name} is not a passive consumer.
Our goal is to improve and innovate the technologies we use and contribute back to the open source projects and standards we rely on.



