== What is GraalVM

link:https://www.graalvm.org/[GraalVM] GraalVM is a universal virtual machine for running applications written in
various different languages, as well as providing the ability to compile JVM bytecode to a native executable (this
native executable runs a special virtual machine called SubstrateVM). These native executable's start much faster
and can use a lot less memory that a traditional JVM, however not every JVM feature is supported, and some are more
limited than normal.

For example by default reflection in GraalVM will not work, unless a class/member has been explicitly registered for
reflection. This is normally achieved by listing every class, method, field and constructor in a JSON file, and passing
this as a parameter into the native image build. This obviously gets quite cumbersome for all but the most trivial projects.
Quarkus provides a framework that makes it easy to work around these annotations, and programmatically determine what should
be registered.