= quarkus:add-extension

Allow adding an extension to an existing pom.xml file. Because you can add one or several extension in one go, there are 2 mojos: `add-extensions` and `add-extension`. Both supports the `extension` and `extensions` parameters.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-add-extension-parameter-parameter]]link:#quarkus-maven-plugin-goal-add-extension-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-add-extension-bomartifactid]]`link:#quarkus-maven-plugin-goal-add-extension-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-add-extension-bomgroupid]]`link:#quarkus-maven-plugin-goal-add-extension-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-add-extension-bomversion]]`link:#quarkus-maven-plugin-goal-add-extension-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-add-extension-extension]]`link:#quarkus-maven-plugin-goal-add-extension-extension[extension]`

[.description]
--
For usability reason, this parameter allows adding a single extension.
--|String 
|


a| [[quarkus-maven-plugin-goal-add-extension-extensions]]`link:#quarkus-maven-plugin-goal-add-extension-extensions[extensions]`

[.description]
--
The list of extensions to be added.
--|Set 
|


a| [[quarkus-maven-plugin-goal-add-extension-project]]`link:#quarkus-maven-plugin-goal-add-extension-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-add-extension-reposession]]`link:#quarkus-maven-plugin-goal-add-extension-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-add-extension-repos]]`link:#quarkus-maven-plugin-goal-add-extension-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:add-extensions

Allow adding extensions to an existing pom.xml file. Because you can add one or several extension in one go, there are 2 mojos: `add-extensions` and `add-extension`. Both supports the `extension` and `extensions` parameters.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-add-extensions-parameter-parameter]]link:#quarkus-maven-plugin-goal-add-extensions-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-add-extensions-bomartifactid]]`link:#quarkus-maven-plugin-goal-add-extensions-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-add-extensions-bomgroupid]]`link:#quarkus-maven-plugin-goal-add-extensions-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-add-extensions-bomversion]]`link:#quarkus-maven-plugin-goal-add-extensions-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-add-extensions-extension]]`link:#quarkus-maven-plugin-goal-add-extensions-extension[extension]`

[.description]
--
For usability reason, this parameter allows adding a single extension.
--|String 
|


a| [[quarkus-maven-plugin-goal-add-extensions-extensions]]`link:#quarkus-maven-plugin-goal-add-extensions-extensions[extensions]`

[.description]
--
The list of extensions to be added.
--|Set 
|


a| [[quarkus-maven-plugin-goal-add-extensions-project]]`link:#quarkus-maven-plugin-goal-add-extensions-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-add-extensions-reposession]]`link:#quarkus-maven-plugin-goal-add-extensions-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-add-extensions-repos]]`link:#quarkus-maven-plugin-goal-add-extensions-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:analyze-call-tree

Analyze call tree of a method or a class based on an existing report produced by Substrate when using -H:{plus}PrintAnalysisCallTree, and does a more meaningful analysis of what is causing a type to be retained.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-analyze-call-tree-parameter-parameter]]link:#quarkus-maven-plugin-goal-analyze-call-tree-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-analyze-call-tree-classname]]`link:#quarkus-maven-plugin-goal-analyze-call-tree-classname[className]`

[.description]
--

--|String 
|`${class}`


a| [[quarkus-maven-plugin-goal-analyze-call-tree-methodname]]`link:#quarkus-maven-plugin-goal-analyze-call-tree-methodname[methodName]`

[.description]
--

--|String 
|`${method}`


a| [[quarkus-maven-plugin-goal-analyze-call-tree-reportsdir]]`link:#quarkus-maven-plugin-goal-analyze-call-tree-reportsdir[reportsDir]`

[.description]
--

--|File 
|`${project.build.directory}/reports`

|===
= quarkus:build

Builds the Quarkus application.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-build-parameter-parameter]]link:#quarkus-maven-plugin-goal-build-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-build-appartifact]]`link:#quarkus-maven-plugin-goal-build-appartifact[appArtifact]`

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format: 
groupId:artifactId:classifier:type:version 
With the classifier, type and version being optional. 
If the type is missing, the artifact is assumed to be of type JAR. 
If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates. 
However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version. 
If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--|String 
|


a| [[quarkus-maven-plugin-goal-build-builddir]]`link:#quarkus-maven-plugin-goal-build-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-build-closebootstrappedapp]]`link:#quarkus-maven-plugin-goal-build-closebootstrappedapp[closeBootstrappedApp]`

[.description]
--
Whether to close the bootstrapped applications after the execution
--|boolean 
|


a| [[quarkus-maven-plugin-goal-build-finalname]]`link:#quarkus-maven-plugin-goal-build-finalname[finalName]`

[.description]
--

--|String 
|`${project.build.finalName}`


a| [[quarkus-maven-plugin-goal-build-generatedsourcesdirectory]]`link:#quarkus-maven-plugin-goal-build-generatedsourcesdirectory[generatedSourcesDirectory]`

[.description]
--
The directory for generated source files.
--|File 
|`${project.build.directory}/generated-sources`


a| [[quarkus-maven-plugin-goal-build-ignoredentries]]`link:#quarkus-maven-plugin-goal-build-ignoredentries[ignoredEntries]`

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: `<configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration> `
--|java.lang.String[] 
|


a| [[quarkus-maven-plugin-goal-build-manifestentries]]`link:#quarkus-maven-plugin-goal-build-manifestentries[manifestEntries]`

[.description]
--
The list of main manifest attributes
--|Map 
|


a| [[quarkus-maven-plugin-goal-build-manifestsections]]`link:#quarkus-maven-plugin-goal-build-manifestsections[manifestSections]`

[.description]
--
The list of manifest sections
--|List 
|


a| [[quarkus-maven-plugin-goal-build-mojoexecution]]`link:#quarkus-maven-plugin-goal-build-mojoexecution[mojoExecution]`

[.description]
--
The context of the execution of the plugin.
--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-build-pluginrepos]]`link:#quarkus-maven-plugin-goal-build-pluginrepos[pluginRepos]`

[.description]
--
The project's remote repositories to use for the resolution of plugins and their dependencies.
--|List 
|`${project.remotePluginRepositories}`


a| [[quarkus-maven-plugin-goal-build-project]]`link:#quarkus-maven-plugin-goal-build-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-build-properties]]`link:#quarkus-maven-plugin-goal-build-properties[properties]`

[.description]
--
The properties of the plugin.
--|Map 
|


a| [[quarkus-maven-plugin-goal-build-reposession]]`link:#quarkus-maven-plugin-goal-build-reposession[repoSession]`

[.description]
--
The current repository/network configuration of Maven.
--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-build-repos]]`link:#quarkus-maven-plugin-goal-build-repos[repos]`

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-build-session]]`link:#quarkus-maven-plugin-goal-build-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-build-skip]]`link:#quarkus-maven-plugin-goal-build-skip[skip]`

[.description]
--
Skips the execution of this mojo
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-build-skiporiginaljarrename]]`link:#quarkus-maven-plugin-goal-build-skiporiginaljarrename[skipOriginalJarRename]`

[.description]
--

--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-build-systemproperties]]`link:#quarkus-maven-plugin-goal-build-systemproperties[systemProperties]`

[.description]
--
The list of system properties defined for the plugin.
--|Map 
|

|===
= quarkus:create

This goal helps in setting up Quarkus Maven project with quarkus-maven-plugin, with sensible defaults

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-create-parameter-parameter]]link:#quarkus-maven-plugin-goal-create-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-create-appconfig]]`link:#quarkus-maven-plugin-goal-create-appconfig[appConfig]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-bomartifactid]]`link:#quarkus-maven-plugin-goal-create-bomartifactid[bomArtifactId]`

[.description]
--
Artifact ID of the target platform BOM
--|String 
|


a| [[quarkus-maven-plugin-goal-create-bomgroupid]]`link:#quarkus-maven-plugin-goal-create-bomgroupid[bomGroupId]`

[.description]
--
Group ID of the target platform BOM
--|String 
|


a| [[quarkus-maven-plugin-goal-create-bomversion]]`link:#quarkus-maven-plugin-goal-create-bomversion[bomVersion]`

[.description]
--
Version of the target platform BOM
--|String 
|


a| [[quarkus-maven-plugin-goal-create-buildtool]]`link:#quarkus-maven-plugin-goal-create-buildtool[buildTool]`

[.description]
--

--|String 
|`MAVEN`


a| [[quarkus-maven-plugin-goal-create-classname]]`link:#quarkus-maven-plugin-goal-create-classname[className]`

[.description]
--
The `class-name` will define the generated class names when picking only one of those extensions resteasy, resteasy-reactive and spring-web. 
If more than one of those extensions are picked, then only the package name part will be used as `package-name` 
More info: https://github.com/quarkusio/quarkus/issues/14437 
By default, the `project-group-id` is used as package for generated classes (you can also use `package-name` to have them different). 
`className`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-example]]`link:#quarkus-maven-plugin-goal-create-example[example]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-extensions]]`link:#quarkus-maven-plugin-goal-create-extensions[extensions]`

[.description]
--

--|Set 
|


a| [[quarkus-maven-plugin-goal-create-javaversion]]`link:#quarkus-maven-plugin-goal-create-javaversion[javaVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-nocode]]`link:#quarkus-maven-plugin-goal-create-nocode[noCode]`

[.description]
--
When true, do not include any code in the generated Quarkus project.
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-create-outputdirectory]]`link:#quarkus-maven-plugin-goal-create-outputdirectory[outputDirectory]`

[.description]
--

--|File 
|`${basedir}`


a| [[quarkus-maven-plugin-goal-create-packagename]]`link:#quarkus-maven-plugin-goal-create-packagename[packageName]`

[.description]
--
Set the package name of the generated classes. 
If not set, `project-group-id` will be used as `package-name` 
`packageName`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-path]]`link:#quarkus-maven-plugin-goal-create-path[path]`

[.description]
--
The `path` will define the REST path of the generated code when picking only one of those extensions resteasy, resteasy-reactive and spring-web. 
If more than one of those extensions are picked, this parameter will be ignored. 
More info: https://github.com/quarkusio/quarkus/issues/14437 
`className`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-project]]`link:#quarkus-maven-plugin-goal-create-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-create-projectartifactid]]`link:#quarkus-maven-plugin-goal-create-projectartifactid[projectArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-projectgroupid]]`link:#quarkus-maven-plugin-goal-create-projectgroupid[projectGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-projectversion]]`link:#quarkus-maven-plugin-goal-create-projectversion[projectVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-reposession]]`link:#quarkus-maven-plugin-goal-create-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-create-repos]]`link:#quarkus-maven-plugin-goal-create-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-create-session]]`link:#quarkus-maven-plugin-goal-create-session[session]`

[.description]
--

--|MavenSession 
|`${session}`

|===
= quarkus:create-extension

Creates the base of a link:https://quarkus.io/guides/writing-extensions[Quarkus Extension] in different layout depending on the options and environment. 

Create in the quarkus-parent project directory (or the extensions parent dir) 
It will:  
 - generate the new Quarkus extension in the extensions parent as a module (parent, runtime and deployment), with unit test and devmode test on option. 
 - On option, generate the new integration test in the integration tests parent as a module. 
 - add the dependencies to the bom/application/pom.xml.  
Creating a Quarkiverse extension 
When using `-DgroupId=io.quarkiverse.++[++featureId++]++`, the new extension will use the Quarkiverse layout. 

Creating a standalone extension 

 - generate the new Quarkus extension in the current directory (parent, runtime and deployment), with unit test and devmode test on option. 
 - On option, generate the new integration test module in the current directory.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-create-extension-parameter-parameter]]link:#quarkus-maven-plugin-goal-create-extension-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-create-extension-artifactid]]`link:#quarkus-maven-plugin-goal-create-extension-artifactid[artifactId]`

[.description]
--
Used to detect legacy command usage and display an error
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-basedir]]`link:#quarkus-maven-plugin-goal-create-extension-basedir[basedir]`

[.description]
--
Directory where the changes should be performed. 

Default: the current directory of the current Java process.
--|File 
|


a| [[quarkus-maven-plugin-goal-create-extension-extensiondescription]]`link:#quarkus-maven-plugin-goal-create-extension-extensiondescription[extensionDescription]`

[.description]
--
The `extensionDescription` of the runtime module. 

This description is used on https://code.quarkus.io/.
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-extensionid]]`link:#quarkus-maven-plugin-goal-create-extension-extensionid[extensionId]`

[.description]
--
`extensionId` of this extension (REQUIRED). 

It will be used to generate the different extension modules artifactIds (`++[++namespaceId++][++extensionId++]++-parent`), runtime (`++[++namespaceId++][++extensionId++]++`) and deployment (`++[++namespaceId++][++extensionId++]++-deployment`).
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-extensionname]]`link:#quarkus-maven-plugin-goal-create-extension-extensionname[extensionName]`

[.description]
--
The `extensionName` of the runtime module. The `extensionName`s of the extension parent and deployment modules will be based on this `name` too. 

Default: the formatted `extensionId`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-groupid]]`link:#quarkus-maven-plugin-goal-create-extension-groupid[groupId]`

[.description]
--
The `groupId` for the newly created Maven modules (REQUIRED - INHERITED IN QUARKUS-CORE).
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-namespaceid]]`link:#quarkus-maven-plugin-goal-create-extension-namespaceid[namespaceId]`

[.description]
--
A prefix common to all extension artifactIds in the current source tree. 

Default: "quarkus-" in quarkus Quarkus Core and Quarkiverse else ""
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-namespacename]]`link:#quarkus-maven-plugin-goal-create-extension-namespacename[namespaceName]`

[.description]
--
A prefix common to all extension names in the current source tree. 

Default: "quarkus-" in Quarkus Core and Quarkiverse else ""
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-packagename]]`link:#quarkus-maven-plugin-goal-create-extension-packagename[packageName]`

[.description]
--
Base package under which classes should be created in Runtime and Deployment modules. 

Default: auto-generated out of `group-id`, `namespace-id` and `extension-id`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-project]]`link:#quarkus-maven-plugin-goal-create-extension-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-create-extension-quarkusbomartifactid]]`link:#quarkus-maven-plugin-goal-create-extension-quarkusbomartifactid[quarkusBomArtifactId]`

[.description]
--
The `artifactId` of the Quarkus platform BOM. 

Default: `CreateExtension++#++DEFAULT_BOM_ARTIFACT_ID`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-quarkusbomgroupid]]`link:#quarkus-maven-plugin-goal-create-extension-quarkusbomgroupid[quarkusBomGroupId]`

[.description]
--
The `groupId` of the Quarkus platform BOM. 

Default: `CreateExtension++#++DEFAULT_BOM_GROUP_ID`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-quarkusbomversion]]`link:#quarkus-maven-plugin-goal-create-extension-quarkusbomversion[quarkusBomVersion]`

[.description]
--
The `version` of the Quarkus platform BOM. 

Default: `CreateExtension++#++DEFAULT_BOM_VERSION`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-quarkusversion]]`link:#quarkus-maven-plugin-goal-create-extension-quarkusversion[quarkusVersion]`

[.description]
--
Quarkus version the newly created extension should depend on (REQUIRED - INHERITED IN QUARKUS-CORE).
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-session]]`link:#quarkus-maven-plugin-goal-create-extension-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-create-extension-version]]`link:#quarkus-maven-plugin-goal-create-extension-version[version]`

[.description]
--
The `version` for the newly created Maven modules. 

Default: automatic in Quarkus Core else `CreateExtension++#++DEFAULT_VERSION`
--|String 
|


a| [[quarkus-maven-plugin-goal-create-extension-withcodestart]]`link:#quarkus-maven-plugin-goal-create-extension-withcodestart[withCodestart]`

[.description]
--
Indicates whether to generate an extension codestart
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-create-extension-withoutdevmodetest]]`link:#quarkus-maven-plugin-goal-create-extension-withoutdevmodetest[withoutDevModeTest]`

[.description]
--
Indicates whether to generate a devmode test for the extension
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-create-extension-withoutintegrationtests]]`link:#quarkus-maven-plugin-goal-create-extension-withoutintegrationtests[withoutIntegrationTests]`

[.description]
--
Indicates whether to generate an integration tests for the extension
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-create-extension-withouttests]]`link:#quarkus-maven-plugin-goal-create-extension-withouttests[withoutTests]`

[.description]
--
Indicates whether to generate any tests for the extension (same as `-DwithoutUnitTest -DwithoutIntegrationTest -DwithoutDevModeTest`)
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-create-extension-withoutunittest]]`link:#quarkus-maven-plugin-goal-create-extension-withoutunittest[withoutUnitTest]`

[.description]
--
Indicates whether to generate a unit test class for the extension
--|boolean 
|`false`

|===
= quarkus:create-jbang

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-create-jbang-parameter-parameter]]link:#quarkus-maven-plugin-goal-create-jbang-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-create-jbang-bomartifactid]]`link:#quarkus-maven-plugin-goal-create-jbang-bomartifactid[bomArtifactId]`

[.description]
--
Artifact ID of the target platform BOM
--|String 
|


a| [[quarkus-maven-plugin-goal-create-jbang-bomgroupid]]`link:#quarkus-maven-plugin-goal-create-jbang-bomgroupid[bomGroupId]`

[.description]
--
Group ID of the target platform BOM
--|String 
|


a| [[quarkus-maven-plugin-goal-create-jbang-bomversion]]`link:#quarkus-maven-plugin-goal-create-jbang-bomversion[bomVersion]`

[.description]
--
Version of the target platform BOM
--|String 
|


a| [[quarkus-maven-plugin-goal-create-jbang-extensions]]`link:#quarkus-maven-plugin-goal-create-jbang-extensions[extensions]`

[.description]
--

--|Set 
|


a| [[quarkus-maven-plugin-goal-create-jbang-javaversion]]`link:#quarkus-maven-plugin-goal-create-jbang-javaversion[javaVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-create-jbang-nojbangwrapper]]`link:#quarkus-maven-plugin-goal-create-jbang-nojbangwrapper[noJBangWrapper]`

[.description]
--

--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-create-jbang-outputdirectory]]`link:#quarkus-maven-plugin-goal-create-jbang-outputdirectory[outputDirectory]`

[.description]
--

--|File 
|`${basedir}/jbang-with-quarkus`


a| [[quarkus-maven-plugin-goal-create-jbang-reposession]]`link:#quarkus-maven-plugin-goal-create-jbang-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-create-jbang-repos]]`link:#quarkus-maven-plugin-goal-create-jbang-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:dependency-tree

Displays Quarkus application build dependency tree including the deployment ones.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-dependency-tree-parameter-parameter]]link:#quarkus-maven-plugin-goal-dependency-tree-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-dependency-tree-appendoutput]]`link:#quarkus-maven-plugin-goal-dependency-tree-appendoutput[appendOutput]`

[.description]
--
Whether to append outputs into the output file or overwrite it.
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-dependency-tree-mode]]`link:#quarkus-maven-plugin-goal-dependency-tree-mode[mode]`

[.description]
--
Target launch mode corresponding to `io.quarkus.runtime.LaunchMode` for which the dependency tree should be built. `io.quarkus.runtime.LaunchMode.NORMAL` is the default.
--|String 
|`prod`


a| [[quarkus-maven-plugin-goal-dependency-tree-outputfile]]`link:#quarkus-maven-plugin-goal-dependency-tree-outputfile[outputFile]`

[.description]
--
If specified, this parameter will cause the dependency tree to be written to the path specified, instead of writing to the console.
--|File 
|


a| [[quarkus-maven-plugin-goal-dependency-tree-project]]`link:#quarkus-maven-plugin-goal-dependency-tree-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-dependency-tree-repos]]`link:#quarkus-maven-plugin-goal-dependency-tree-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:dev

The dev mojo, that runs a quarkus app in a forked process. A background compilation process is launched and any changes are automatically reflected in your running application. 
You can use this dev mode in a remote container environment with `remote-dev`.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-dev-parameter-parameter]]link:#quarkus-maven-plugin-goal-dev-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-dev-argsstring]]`link:#quarkus-maven-plugin-goal-dev-argsstring[argsString]`

[.description]
--

--|String 
|`${quarkus.args}`


a| [[quarkus-maven-plugin-goal-dev-builddir]]`link:#quarkus-maven-plugin-goal-dev-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-dev-compilerargs]]`link:#quarkus-maven-plugin-goal-dev-compilerargs[compilerArgs]`

[.description]
--
Additional parameters to pass to javac when recompiling changed source files.
--|List 
|


a| [[quarkus-maven-plugin-goal-dev-compileroptions]]`link:#quarkus-maven-plugin-goal-dev-compileroptions[compilerOptions]`

[.description]
--
Additional compiler arguments
--|List 
|


a| [[quarkus-maven-plugin-goal-dev-debug]]`link:#quarkus-maven-plugin-goal-dev-debug[debug]`

[.description]
--
If this server should be started in debug mode. The default is to start in debug mode and listen on port 5005. Whether the JVM is suspended waiting for a debugger to be attached, depends on the value of `suspend`. 
`debug` supports the following options:   *Value* Effect   *false* The JVM is not started in debug mode   *true* The JVM is started in debug mode and will be listening on `debugHost`:`debugPort`   *client* The JVM is started in client mode, and will attempt to connect to `debugHost`:`debugPort`   *++{++port++}++* The JVM is started in debug mode and will be listening on `debugHost`:++{++port++}++.   By default, `debugHost` has the value "localhost", and `debugPort` is 5005.
--|String 
|`${debug}`


a| [[quarkus-maven-plugin-goal-dev-debughost]]`link:#quarkus-maven-plugin-goal-dev-debughost[debugHost]`

[.description]
--

--|String 
|`${debugHost}`


a| [[quarkus-maven-plugin-goal-dev-debugport]]`link:#quarkus-maven-plugin-goal-dev-debugport[debugPort]`

[.description]
--

--|String 
|`${debugPort}`


a| [[quarkus-maven-plugin-goal-dev-deletedevjar]]`link:#quarkus-maven-plugin-goal-dev-deletedevjar[deleteDevJar]`

[.description]
--

--|boolean 
|`TRUE`


a| [[quarkus-maven-plugin-goal-dev-enforcebuildgoal]]`link:#quarkus-maven-plugin-goal-dev-enforcebuildgoal[enforceBuildGoal]`

[.description]
--
Whether to enforce the quarkus-maven-plugin build goal to be configured. By default, a missing build goal is considered an inconsistency (although the build goal is not _required_ technically). In this case a warning will be logged and the application will not be started.
--|boolean 
|`${quarkus.enforceBuildGoal}`


a| [[quarkus-maven-plugin-goal-dev-environmentvariables]]`link:#quarkus-maven-plugin-goal-dev-environmentvariables[environmentVariables]`

[.description]
--

--|Map 
|


a| [[quarkus-maven-plugin-goal-dev-jvmargs]]`link:#quarkus-maven-plugin-goal-dev-jvmargs[jvmArgs]`

[.description]
--

--|String 
|`${jvm.args}`


a| [[quarkus-maven-plugin-goal-dev-mojoexecution]]`link:#quarkus-maven-plugin-goal-dev-mojoexecution[mojoExecution]`

[.description]
--

--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-dev-nodeps]]`link:#quarkus-maven-plugin-goal-dev-nodeps[noDeps]`

[.description]
--
Whether changes in the projects that appear to be dependencies of the project containing the application to be launched should trigger hot-reload. By default, they do.
--|boolean 
|`${noDeps}`


a| [[quarkus-maven-plugin-goal-dev-openjavalang]]`link:#quarkus-maven-plugin-goal-dev-openjavalang[openJavaLang]`

[.description]
--

--|boolean 
|`${open-lang-package}`


a| [[quarkus-maven-plugin-goal-dev-outputdirectory]]`link:#quarkus-maven-plugin-goal-dev-outputdirectory[outputDirectory]`

[.description]
--
The directory for compiled classes.
--|File 
|`${project.build.outputDirectory}`


a| [[quarkus-maven-plugin-goal-dev-pluginrepos]]`link:#quarkus-maven-plugin-goal-dev-pluginrepos[pluginRepos]`

[.description]
--

--|List 
|`${project.remotePluginRepositories}`


a| [[quarkus-maven-plugin-goal-dev-preventnoverify]]`link:#quarkus-maven-plugin-goal-dev-preventnoverify[preventnoverify]`

[.description]
--
This value is intended to be set to true when some generated bytecode is erroneous causing the JVM to crash when the `verify:none` option is set (which is on by default)
--|boolean 
|`${preventnoverify}`


a| [[quarkus-maven-plugin-goal-dev-project]]`link:#quarkus-maven-plugin-goal-dev-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-dev-release]]`link:#quarkus-maven-plugin-goal-dev-release[release]`

[.description]
--
The --release argument to javac.
--|String 
|`${maven.compiler.release}`


a| [[quarkus-maven-plugin-goal-dev-reposession]]`link:#quarkus-maven-plugin-goal-dev-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-dev-repos]]`link:#quarkus-maven-plugin-goal-dev-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-dev-session]]`link:#quarkus-maven-plugin-goal-dev-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-dev-source]]`link:#quarkus-maven-plugin-goal-dev-source[source]`

[.description]
--
The -source argument to javac.
--|String 
|`${maven.compiler.source}`


a| [[quarkus-maven-plugin-goal-dev-sourcedir]]`link:#quarkus-maven-plugin-goal-dev-sourcedir[sourceDir]`

[.description]
--

--|File 
|`${project.build.sourceDirectory}`


a| [[quarkus-maven-plugin-goal-dev-suspend]]`link:#quarkus-maven-plugin-goal-dev-suspend[suspend]`

[.description]
--
Whether the JVM launch, in debug mode, should be suspended. This parameter is only relevant when the JVM is launched in `debug debug mode`. This parameter supports the following values (all the allowed values are case-insensitive):   Value Effect   y or true The debug mode JVM launch is suspended   n or false The debug mode JVM is started without suspending
--|String 
|`${suspend}`


a| [[quarkus-maven-plugin-goal-dev-systemproperties]]`link:#quarkus-maven-plugin-goal-dev-systemproperties[systemProperties]`

[.description]
--

--|Map 
|


a| [[quarkus-maven-plugin-goal-dev-target]]`link:#quarkus-maven-plugin-goal-dev-target[target]`

[.description]
--
The -target argument to javac.
--|String 
|`${maven.compiler.target}`


a| [[quarkus-maven-plugin-goal-dev-workingdir]]`link:#quarkus-maven-plugin-goal-dev-workingdir[workingDir]`

[.description]
--

--|File 
|

|===
= quarkus:generate-code

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-generate-code-parameter-parameter]]link:#quarkus-maven-plugin-goal-generate-code-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-generate-code-appartifact]]`link:#quarkus-maven-plugin-goal-generate-code-appartifact[appArtifact]`

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format: 
groupId:artifactId:classifier:type:version 
With the classifier, type and version being optional. 
If the type is missing, the artifact is assumed to be of type JAR. 
If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates. 
However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version. 
If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--|String 
|


a| [[quarkus-maven-plugin-goal-generate-code-builddir]]`link:#quarkus-maven-plugin-goal-generate-code-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-generate-code-closebootstrappedapp]]`link:#quarkus-maven-plugin-goal-generate-code-closebootstrappedapp[closeBootstrappedApp]`

[.description]
--
Whether to close the bootstrapped applications after the execution
--|boolean 
|


a| [[quarkus-maven-plugin-goal-generate-code-finalname]]`link:#quarkus-maven-plugin-goal-generate-code-finalname[finalName]`

[.description]
--

--|String 
|`${project.build.finalName}`


a| [[quarkus-maven-plugin-goal-generate-code-ignoredentries]]`link:#quarkus-maven-plugin-goal-generate-code-ignoredentries[ignoredEntries]`

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: `<configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration> `
--|java.lang.String[] 
|


a| [[quarkus-maven-plugin-goal-generate-code-manifestentries]]`link:#quarkus-maven-plugin-goal-generate-code-manifestentries[manifestEntries]`

[.description]
--
The list of main manifest attributes
--|Map 
|


a| [[quarkus-maven-plugin-goal-generate-code-manifestsections]]`link:#quarkus-maven-plugin-goal-generate-code-manifestsections[manifestSections]`

[.description]
--
The list of manifest sections
--|List 
|


a| [[quarkus-maven-plugin-goal-generate-code-mode]]`link:#quarkus-maven-plugin-goal-generate-code-mode[mode]`

[.description]
--

--|String 
|`NORMAL`


a| [[quarkus-maven-plugin-goal-generate-code-mojoexecution]]`link:#quarkus-maven-plugin-goal-generate-code-mojoexecution[mojoExecution]`

[.description]
--
The context of the execution of the plugin.
--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-generate-code-project]]`link:#quarkus-maven-plugin-goal-generate-code-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-generate-code-properties]]`link:#quarkus-maven-plugin-goal-generate-code-properties[properties]`

[.description]
--
The properties of the plugin.
--|Map 
|


a| [[quarkus-maven-plugin-goal-generate-code-reposession]]`link:#quarkus-maven-plugin-goal-generate-code-reposession[repoSession]`

[.description]
--
The current repository/network configuration of Maven.
--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-generate-code-repos]]`link:#quarkus-maven-plugin-goal-generate-code-repos[repos]`

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-generate-code-session]]`link:#quarkus-maven-plugin-goal-generate-code-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-generate-code-skipsourcegeneration]]`link:#quarkus-maven-plugin-goal-generate-code-skipsourcegeneration[skipSourceGeneration]`

[.description]
--
Skip the execution of this mojo
--|boolean 
|`false`

|===
= quarkus:generate-code-tests

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-generate-code-tests-parameter-parameter]]link:#quarkus-maven-plugin-goal-generate-code-tests-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-generate-code-tests-appartifact]]`link:#quarkus-maven-plugin-goal-generate-code-tests-appartifact[appArtifact]`

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format: 
groupId:artifactId:classifier:type:version 
With the classifier, type and version being optional. 
If the type is missing, the artifact is assumed to be of type JAR. 
If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates. 
However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version. 
If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--|String 
|


a| [[quarkus-maven-plugin-goal-generate-code-tests-builddir]]`link:#quarkus-maven-plugin-goal-generate-code-tests-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-closebootstrappedapp]]`link:#quarkus-maven-plugin-goal-generate-code-tests-closebootstrappedapp[closeBootstrappedApp]`

[.description]
--
Whether to close the bootstrapped applications after the execution
--|boolean 
|


a| [[quarkus-maven-plugin-goal-generate-code-tests-finalname]]`link:#quarkus-maven-plugin-goal-generate-code-tests-finalname[finalName]`

[.description]
--

--|String 
|`${project.build.finalName}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-ignoredentries]]`link:#quarkus-maven-plugin-goal-generate-code-tests-ignoredentries[ignoredEntries]`

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: `<configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration> `
--|java.lang.String[] 
|


a| [[quarkus-maven-plugin-goal-generate-code-tests-manifestentries]]`link:#quarkus-maven-plugin-goal-generate-code-tests-manifestentries[manifestEntries]`

[.description]
--
The list of main manifest attributes
--|Map 
|


a| [[quarkus-maven-plugin-goal-generate-code-tests-manifestsections]]`link:#quarkus-maven-plugin-goal-generate-code-tests-manifestsections[manifestSections]`

[.description]
--
The list of manifest sections
--|List 
|


a| [[quarkus-maven-plugin-goal-generate-code-tests-mode]]`link:#quarkus-maven-plugin-goal-generate-code-tests-mode[mode]`

[.description]
--

--|String 
|`NORMAL`


a| [[quarkus-maven-plugin-goal-generate-code-tests-mojoexecution]]`link:#quarkus-maven-plugin-goal-generate-code-tests-mojoexecution[mojoExecution]`

[.description]
--
The context of the execution of the plugin.
--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-project]]`link:#quarkus-maven-plugin-goal-generate-code-tests-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-properties]]`link:#quarkus-maven-plugin-goal-generate-code-tests-properties[properties]`

[.description]
--
The properties of the plugin.
--|Map 
|


a| [[quarkus-maven-plugin-goal-generate-code-tests-reposession]]`link:#quarkus-maven-plugin-goal-generate-code-tests-reposession[repoSession]`

[.description]
--
The current repository/network configuration of Maven.
--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-repos]]`link:#quarkus-maven-plugin-goal-generate-code-tests-repos[repos]`

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-session]]`link:#quarkus-maven-plugin-goal-generate-code-tests-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-generate-code-tests-skipsourcegeneration]]`link:#quarkus-maven-plugin-goal-generate-code-tests-skipsourcegeneration[skipSourceGeneration]`

[.description]
--
Skip the execution of this mojo
--|boolean 
|`false`

|===
= quarkus:go-offline

This goal downloads all the Maven artifact dependencies required to build, run, test and launch the application dev mode.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-go-offline-parameter-parameter]]link:#quarkus-maven-plugin-goal-go-offline-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-go-offline-mode]]`link:#quarkus-maven-plugin-goal-go-offline-mode[mode]`

[.description]
--
Target launch mode corresponding to `io.quarkus.runtime.LaunchMode` for which the dependencies should be resolved. `io.quarkus.runtime.LaunchMode.TEST` is the default, since it includes both `provided` and `test` dependency scopes.
--|String 
|`test`


a| [[quarkus-maven-plugin-goal-go-offline-project]]`link:#quarkus-maven-plugin-goal-go-offline-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-go-offline-reposession]]`link:#quarkus-maven-plugin-goal-go-offline-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-go-offline-repos]]`link:#quarkus-maven-plugin-goal-go-offline-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:help

Display help information on quarkus-maven-plugin.
Call `mvn quarkus:help -Ddetail=true -Dgoal=<goal-name>` to display parameter details.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-help-parameter-parameter]]link:#quarkus-maven-plugin-goal-help-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-help-detail]]`link:#quarkus-maven-plugin-goal-help-detail[detail]`

[.description]
--
If `true`, display all settable properties for each goal.
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-help-goal]]`link:#quarkus-maven-plugin-goal-help-goal[goal]`

[.description]
--
The name of the goal for which to show help. If unspecified, all goals will be displayed.
--|String 
|


a| [[quarkus-maven-plugin-goal-help-indentsize]]`link:#quarkus-maven-plugin-goal-help-indentsize[indentSize]`

[.description]
--
The number of spaces per indentation level, should be positive.
--|int 
|`2`


a| [[quarkus-maven-plugin-goal-help-linelength]]`link:#quarkus-maven-plugin-goal-help-linelength[lineLength]`

[.description]
--
The maximum length of a display line, should be positive.
--|int 
|`80`

|===
= quarkus:info

Log Quarkus-specific project information, such as imported Quarkus platform BOMs, Quarkus extensions found among the project dependencies, etc.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-info-parameter-parameter]]link:#quarkus-maven-plugin-goal-info-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-info-bomartifactid]]`link:#quarkus-maven-plugin-goal-info-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-info-bomgroupid]]`link:#quarkus-maven-plugin-goal-info-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-info-bomversion]]`link:#quarkus-maven-plugin-goal-info-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-info-permodule]]`link:#quarkus-maven-plugin-goal-info-permodule[perModule]`

[.description]
--
If true, the information will be logged per each relevant module of the project instead of an overall summary
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-info-project]]`link:#quarkus-maven-plugin-goal-info-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-info-reposession]]`link:#quarkus-maven-plugin-goal-info-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-info-repos]]`link:#quarkus-maven-plugin-goal-info-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:list-categories

List extension categories, which a user can use to filter extensions.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-list-categories-parameter-parameter]]link:#quarkus-maven-plugin-goal-list-categories-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-list-categories-bomartifactid]]`link:#quarkus-maven-plugin-goal-list-categories-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-categories-bomgroupid]]`link:#quarkus-maven-plugin-goal-list-categories-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-categories-bomversion]]`link:#quarkus-maven-plugin-goal-list-categories-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-categories-format]]`link:#quarkus-maven-plugin-goal-list-categories-format[format]`

[.description]
--
Select the output format among 'name' (display the name only) and 'full' (includes a verbose name and a description).
--|String 
|`concise`


a| [[quarkus-maven-plugin-goal-list-categories-project]]`link:#quarkus-maven-plugin-goal-list-categories-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-list-categories-reposession]]`link:#quarkus-maven-plugin-goal-list-categories-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-list-categories-repos]]`link:#quarkus-maven-plugin-goal-list-categories-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:list-extensions

List the available extensions. You can add one or several extensions in one go, with the 2 following mojos: `add-extensions` and `add-extension`. You can list all extension or just installable. Choose between 3 output formats: name, concise and full.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-list-extensions-parameter-parameter]]link:#quarkus-maven-plugin-goal-list-extensions-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-list-extensions-all]]`link:#quarkus-maven-plugin-goal-list-extensions-all[all]`

[.description]
--
List all extensions or just the installable.
--|boolean 
|`true`


a| [[quarkus-maven-plugin-goal-list-extensions-bomartifactid]]`link:#quarkus-maven-plugin-goal-list-extensions-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-extensions-bomgroupid]]`link:#quarkus-maven-plugin-goal-list-extensions-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-extensions-bomversion]]`link:#quarkus-maven-plugin-goal-list-extensions-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-extensions-category]]`link:#quarkus-maven-plugin-goal-list-extensions-category[category]`

[.description]
--
Only list extensions from given category.
--|String 
|


a| [[quarkus-maven-plugin-goal-list-extensions-format]]`link:#quarkus-maven-plugin-goal-list-extensions-format[format]`

[.description]
--
Select the output format among 'id' (display the artifactId only), 'concise' (display name and artifactId) and 'full' (concise format and version related columns).
--|String 
|`concise`


a| [[quarkus-maven-plugin-goal-list-extensions-installed]]`link:#quarkus-maven-plugin-goal-list-extensions-installed[installed]`

[.description]
--
List the already installed extensions
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-list-extensions-project]]`link:#quarkus-maven-plugin-goal-list-extensions-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-list-extensions-reposession]]`link:#quarkus-maven-plugin-goal-list-extensions-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-list-extensions-repos]]`link:#quarkus-maven-plugin-goal-list-extensions-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-list-extensions-searchpattern]]`link:#quarkus-maven-plugin-goal-list-extensions-searchpattern[searchPattern]`

[.description]
--
Search filter on extension list. The format is based on Java Pattern.
--|String 
|

|===
= quarkus:list-platforms

List imported and optionally other platforms available for the project.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-list-platforms-parameter-parameter]]link:#quarkus-maven-plugin-goal-list-platforms-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-list-platforms-bomartifactid]]`link:#quarkus-maven-plugin-goal-list-platforms-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-platforms-bomgroupid]]`link:#quarkus-maven-plugin-goal-list-platforms-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-platforms-bomversion]]`link:#quarkus-maven-plugin-goal-list-platforms-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-list-platforms-installed]]`link:#quarkus-maven-plugin-goal-list-platforms-installed[installed]`

[.description]
--
List the already installed extensions
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-list-platforms-project]]`link:#quarkus-maven-plugin-goal-list-platforms-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-list-platforms-reposession]]`link:#quarkus-maven-plugin-goal-list-platforms-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-list-platforms-repos]]`link:#quarkus-maven-plugin-goal-list-platforms-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:prepare

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-prepare-parameter-parameter]]link:#quarkus-maven-plugin-goal-prepare-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-prepare-appartifact]]`link:#quarkus-maven-plugin-goal-prepare-appartifact[appArtifact]`

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format: 
groupId:artifactId:classifier:type:version 
With the classifier, type and version being optional. 
If the type is missing, the artifact is assumed to be of type JAR. 
If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates. 
However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version. 
If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--|String 
|


a| [[quarkus-maven-plugin-goal-prepare-builddir]]`link:#quarkus-maven-plugin-goal-prepare-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-prepare-closebootstrappedapp]]`link:#quarkus-maven-plugin-goal-prepare-closebootstrappedapp[closeBootstrappedApp]`

[.description]
--
Whether to close the bootstrapped applications after the execution
--|boolean 
|


a| [[quarkus-maven-plugin-goal-prepare-finalname]]`link:#quarkus-maven-plugin-goal-prepare-finalname[finalName]`

[.description]
--

--|String 
|`${project.build.finalName}`


a| [[quarkus-maven-plugin-goal-prepare-ignoredentries]]`link:#quarkus-maven-plugin-goal-prepare-ignoredentries[ignoredEntries]`

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: `<configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration> `
--|java.lang.String[] 
|


a| [[quarkus-maven-plugin-goal-prepare-manifestentries]]`link:#quarkus-maven-plugin-goal-prepare-manifestentries[manifestEntries]`

[.description]
--
The list of main manifest attributes
--|Map 
|


a| [[quarkus-maven-plugin-goal-prepare-manifestsections]]`link:#quarkus-maven-plugin-goal-prepare-manifestsections[manifestSections]`

[.description]
--
The list of manifest sections
--|List 
|


a| [[quarkus-maven-plugin-goal-prepare-mode]]`link:#quarkus-maven-plugin-goal-prepare-mode[mode]`

[.description]
--

--|String 
|`NORMAL`


a| [[quarkus-maven-plugin-goal-prepare-mojoexecution]]`link:#quarkus-maven-plugin-goal-prepare-mojoexecution[mojoExecution]`

[.description]
--
The context of the execution of the plugin.
--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-prepare-project]]`link:#quarkus-maven-plugin-goal-prepare-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-prepare-properties]]`link:#quarkus-maven-plugin-goal-prepare-properties[properties]`

[.description]
--
The properties of the plugin.
--|Map 
|


a| [[quarkus-maven-plugin-goal-prepare-reposession]]`link:#quarkus-maven-plugin-goal-prepare-reposession[repoSession]`

[.description]
--
The current repository/network configuration of Maven.
--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-prepare-repos]]`link:#quarkus-maven-plugin-goal-prepare-repos[repos]`

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-prepare-session]]`link:#quarkus-maven-plugin-goal-prepare-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-prepare-skipsourcegeneration]]`link:#quarkus-maven-plugin-goal-prepare-skipsourcegeneration[skipSourceGeneration]`

[.description]
--
Skip the execution of this mojo
--|boolean 
|`false`

|===
= quarkus:prepare-tests

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-prepare-tests-parameter-parameter]]link:#quarkus-maven-plugin-goal-prepare-tests-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-prepare-tests-appartifact]]`link:#quarkus-maven-plugin-goal-prepare-tests-appartifact[appArtifact]`

[.description]
--
Coordinates of the Maven artifact containing the original Java application to build the native image for. If not provided, the current project is assumed to be the original Java application. 
The coordinates are expected to be expressed in the following format: 
groupId:artifactId:classifier:type:version 
With the classifier, type and version being optional. 
If the type is missing, the artifact is assumed to be of type JAR. 
If the version is missing, the artifact is going to be looked up among the project dependencies using the provided coordinates. 
However, if the expression consists of only three parts, it is assumed to be groupId:artifactId:version. 
If the expression consists of only four parts, it is assumed to be groupId:artifactId:classifier:type.
--|String 
|


a| [[quarkus-maven-plugin-goal-prepare-tests-builddir]]`link:#quarkus-maven-plugin-goal-prepare-tests-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-prepare-tests-closebootstrappedapp]]`link:#quarkus-maven-plugin-goal-prepare-tests-closebootstrappedapp[closeBootstrappedApp]`

[.description]
--
Whether to close the bootstrapped applications after the execution
--|boolean 
|


a| [[quarkus-maven-plugin-goal-prepare-tests-finalname]]`link:#quarkus-maven-plugin-goal-prepare-tests-finalname[finalName]`

[.description]
--

--|String 
|`${project.build.finalName}`


a| [[quarkus-maven-plugin-goal-prepare-tests-ignoredentries]]`link:#quarkus-maven-plugin-goal-prepare-tests-ignoredentries[ignoredEntries]`

[.description]
--
When building an uber-jar, this array specifies entries that should be excluded from the final jar. The entries are relative to the root of the file. An example of this configuration could be: `<configuration> <uberJar>true</uberJar> <ignoredEntries> <ignoredEntry>META-INF/BC2048KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC2048KE.DSA</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.SF</ignoredEntry> <ignoredEntry>META-INF/BC1024KE.DSA</ignoredEntry> </ignoredEntries> </configuration> `
--|java.lang.String[] 
|


a| [[quarkus-maven-plugin-goal-prepare-tests-manifestentries]]`link:#quarkus-maven-plugin-goal-prepare-tests-manifestentries[manifestEntries]`

[.description]
--
The list of main manifest attributes
--|Map 
|


a| [[quarkus-maven-plugin-goal-prepare-tests-manifestsections]]`link:#quarkus-maven-plugin-goal-prepare-tests-manifestsections[manifestSections]`

[.description]
--
The list of manifest sections
--|List 
|


a| [[quarkus-maven-plugin-goal-prepare-tests-mode]]`link:#quarkus-maven-plugin-goal-prepare-tests-mode[mode]`

[.description]
--

--|String 
|`NORMAL`


a| [[quarkus-maven-plugin-goal-prepare-tests-mojoexecution]]`link:#quarkus-maven-plugin-goal-prepare-tests-mojoexecution[mojoExecution]`

[.description]
--
The context of the execution of the plugin.
--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-prepare-tests-project]]`link:#quarkus-maven-plugin-goal-prepare-tests-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-prepare-tests-properties]]`link:#quarkus-maven-plugin-goal-prepare-tests-properties[properties]`

[.description]
--
The properties of the plugin.
--|Map 
|


a| [[quarkus-maven-plugin-goal-prepare-tests-reposession]]`link:#quarkus-maven-plugin-goal-prepare-tests-reposession[repoSession]`

[.description]
--
The current repository/network configuration of Maven.
--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-prepare-tests-repos]]`link:#quarkus-maven-plugin-goal-prepare-tests-repos[repos]`

[.description]
--
The project's remote repositories to use for the resolution of artifacts and their dependencies.
--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-prepare-tests-session]]`link:#quarkus-maven-plugin-goal-prepare-tests-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-prepare-tests-skipsourcegeneration]]`link:#quarkus-maven-plugin-goal-prepare-tests-skipsourcegeneration[skipSourceGeneration]`

[.description]
--
Skip the execution of this mojo
--|boolean 
|`false`

|===
= quarkus:remote-dev

The dev mojo, that connects to a remote host.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-remote-dev-parameter-parameter]]link:#quarkus-maven-plugin-goal-remote-dev-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-remote-dev-argsstring]]`link:#quarkus-maven-plugin-goal-remote-dev-argsstring[argsString]`

[.description]
--

--|String 
|`${quarkus.args}`


a| [[quarkus-maven-plugin-goal-remote-dev-builddir]]`link:#quarkus-maven-plugin-goal-remote-dev-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-remote-dev-compilerargs]]`link:#quarkus-maven-plugin-goal-remote-dev-compilerargs[compilerArgs]`

[.description]
--
Additional parameters to pass to javac when recompiling changed source files.
--|List 
|


a| [[quarkus-maven-plugin-goal-remote-dev-compileroptions]]`link:#quarkus-maven-plugin-goal-remote-dev-compileroptions[compilerOptions]`

[.description]
--
Additional compiler arguments
--|List 
|


a| [[quarkus-maven-plugin-goal-remote-dev-debug]]`link:#quarkus-maven-plugin-goal-remote-dev-debug[debug]`

[.description]
--
If this server should be started in debug mode. The default is to start in debug mode and listen on port 5005. Whether the JVM is suspended waiting for a debugger to be attached, depends on the value of `suspend`. 
`debug` supports the following options:   *Value* Effect   *false* The JVM is not started in debug mode   *true* The JVM is started in debug mode and will be listening on `debugHost`:`debugPort`   *client* The JVM is started in client mode, and will attempt to connect to `debugHost`:`debugPort`   *++{++port++}++* The JVM is started in debug mode and will be listening on `debugHost`:++{++port++}++.   By default, `debugHost` has the value "localhost", and `debugPort` is 5005.
--|String 
|`${debug}`


a| [[quarkus-maven-plugin-goal-remote-dev-debughost]]`link:#quarkus-maven-plugin-goal-remote-dev-debughost[debugHost]`

[.description]
--

--|String 
|`${debugHost}`


a| [[quarkus-maven-plugin-goal-remote-dev-debugport]]`link:#quarkus-maven-plugin-goal-remote-dev-debugport[debugPort]`

[.description]
--

--|String 
|`${debugPort}`


a| [[quarkus-maven-plugin-goal-remote-dev-deletedevjar]]`link:#quarkus-maven-plugin-goal-remote-dev-deletedevjar[deleteDevJar]`

[.description]
--

--|boolean 
|`TRUE`


a| [[quarkus-maven-plugin-goal-remote-dev-enforcebuildgoal]]`link:#quarkus-maven-plugin-goal-remote-dev-enforcebuildgoal[enforceBuildGoal]`

[.description]
--
Whether to enforce the quarkus-maven-plugin build goal to be configured. By default, a missing build goal is considered an inconsistency (although the build goal is not _required_ technically). In this case a warning will be logged and the application will not be started.
--|boolean 
|`${quarkus.enforceBuildGoal}`


a| [[quarkus-maven-plugin-goal-remote-dev-environmentvariables]]`link:#quarkus-maven-plugin-goal-remote-dev-environmentvariables[environmentVariables]`

[.description]
--

--|Map 
|


a| [[quarkus-maven-plugin-goal-remote-dev-jvmargs]]`link:#quarkus-maven-plugin-goal-remote-dev-jvmargs[jvmArgs]`

[.description]
--

--|String 
|`${jvm.args}`


a| [[quarkus-maven-plugin-goal-remote-dev-mojoexecution]]`link:#quarkus-maven-plugin-goal-remote-dev-mojoexecution[mojoExecution]`

[.description]
--

--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-remote-dev-nodeps]]`link:#quarkus-maven-plugin-goal-remote-dev-nodeps[noDeps]`

[.description]
--
Whether changes in the projects that appear to be dependencies of the project containing the application to be launched should trigger hot-reload. By default, they do.
--|boolean 
|`${noDeps}`


a| [[quarkus-maven-plugin-goal-remote-dev-openjavalang]]`link:#quarkus-maven-plugin-goal-remote-dev-openjavalang[openJavaLang]`

[.description]
--

--|boolean 
|`${open-lang-package}`


a| [[quarkus-maven-plugin-goal-remote-dev-outputdirectory]]`link:#quarkus-maven-plugin-goal-remote-dev-outputdirectory[outputDirectory]`

[.description]
--
The directory for compiled classes.
--|File 
|`${project.build.outputDirectory}`


a| [[quarkus-maven-plugin-goal-remote-dev-pluginrepos]]`link:#quarkus-maven-plugin-goal-remote-dev-pluginrepos[pluginRepos]`

[.description]
--

--|List 
|`${project.remotePluginRepositories}`


a| [[quarkus-maven-plugin-goal-remote-dev-preventnoverify]]`link:#quarkus-maven-plugin-goal-remote-dev-preventnoverify[preventnoverify]`

[.description]
--
This value is intended to be set to true when some generated bytecode is erroneous causing the JVM to crash when the `verify:none` option is set (which is on by default)
--|boolean 
|`${preventnoverify}`


a| [[quarkus-maven-plugin-goal-remote-dev-project]]`link:#quarkus-maven-plugin-goal-remote-dev-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-remote-dev-release]]`link:#quarkus-maven-plugin-goal-remote-dev-release[release]`

[.description]
--
The --release argument to javac.
--|String 
|`${maven.compiler.release}`


a| [[quarkus-maven-plugin-goal-remote-dev-reposession]]`link:#quarkus-maven-plugin-goal-remote-dev-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-remote-dev-repos]]`link:#quarkus-maven-plugin-goal-remote-dev-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-remote-dev-session]]`link:#quarkus-maven-plugin-goal-remote-dev-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-remote-dev-source]]`link:#quarkus-maven-plugin-goal-remote-dev-source[source]`

[.description]
--
The -source argument to javac.
--|String 
|`${maven.compiler.source}`


a| [[quarkus-maven-plugin-goal-remote-dev-sourcedir]]`link:#quarkus-maven-plugin-goal-remote-dev-sourcedir[sourceDir]`

[.description]
--

--|File 
|`${project.build.sourceDirectory}`


a| [[quarkus-maven-plugin-goal-remote-dev-suspend]]`link:#quarkus-maven-plugin-goal-remote-dev-suspend[suspend]`

[.description]
--
Whether the JVM launch, in debug mode, should be suspended. This parameter is only relevant when the JVM is launched in `debug debug mode`. This parameter supports the following values (all the allowed values are case-insensitive):   Value Effect   y or true The debug mode JVM launch is suspended   n or false The debug mode JVM is started without suspending
--|String 
|`${suspend}`


a| [[quarkus-maven-plugin-goal-remote-dev-systemproperties]]`link:#quarkus-maven-plugin-goal-remote-dev-systemproperties[systemProperties]`

[.description]
--

--|Map 
|


a| [[quarkus-maven-plugin-goal-remote-dev-target]]`link:#quarkus-maven-plugin-goal-remote-dev-target[target]`

[.description]
--
The -target argument to javac.
--|String 
|`${maven.compiler.target}`


a| [[quarkus-maven-plugin-goal-remote-dev-workingdir]]`link:#quarkus-maven-plugin-goal-remote-dev-workingdir[workingDir]`

[.description]
--

--|File 
|

|===
= quarkus:remove-extension

Allow removing an extension from an existing pom.xml file. Because you can remove one or several extension in one go, there are 2 mojos: `remove-extensions` and `remove-extension`. Both supports the `extension` and `extensions` parameters.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-remove-extension-parameter-parameter]]link:#quarkus-maven-plugin-goal-remove-extension-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-remove-extension-bomartifactid]]`link:#quarkus-maven-plugin-goal-remove-extension-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extension-bomgroupid]]`link:#quarkus-maven-plugin-goal-remove-extension-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extension-bomversion]]`link:#quarkus-maven-plugin-goal-remove-extension-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extension-extension]]`link:#quarkus-maven-plugin-goal-remove-extension-extension[extension]`

[.description]
--
For usability reason, this parameter allows removing a single extension.
--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extension-extensions]]`link:#quarkus-maven-plugin-goal-remove-extension-extensions[extensions]`

[.description]
--
The list of extensions to be removed.
--|Set 
|


a| [[quarkus-maven-plugin-goal-remove-extension-project]]`link:#quarkus-maven-plugin-goal-remove-extension-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-remove-extension-reposession]]`link:#quarkus-maven-plugin-goal-remove-extension-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-remove-extension-repos]]`link:#quarkus-maven-plugin-goal-remove-extension-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:remove-extensions

Allow removing extensions to an existing pom.xml file. Because you can remove one or several extension in one go, there are 2 mojos: `remove-extensions` and `remove-extension`. Both supports the `extension` and `extensions` parameters.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-remove-extensions-parameter-parameter]]link:#quarkus-maven-plugin-goal-remove-extensions-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-remove-extensions-bomartifactid]]`link:#quarkus-maven-plugin-goal-remove-extensions-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extensions-bomgroupid]]`link:#quarkus-maven-plugin-goal-remove-extensions-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extensions-bomversion]]`link:#quarkus-maven-plugin-goal-remove-extensions-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extensions-extension]]`link:#quarkus-maven-plugin-goal-remove-extensions-extension[extension]`

[.description]
--
For usability reason, this parameter allows removing a single extension.
--|String 
|


a| [[quarkus-maven-plugin-goal-remove-extensions-extensions]]`link:#quarkus-maven-plugin-goal-remove-extensions-extensions[extensions]`

[.description]
--
The list of extensions to be removed.
--|Set 
|


a| [[quarkus-maven-plugin-goal-remove-extensions-project]]`link:#quarkus-maven-plugin-goal-remove-extensions-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-remove-extensions-reposession]]`link:#quarkus-maven-plugin-goal-remove-extensions-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-remove-extensions-repos]]`link:#quarkus-maven-plugin-goal-remove-extensions-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
= quarkus:test

The test mojo, that starts continuous testing outside of dev mode

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-test-parameter-parameter]]link:#quarkus-maven-plugin-goal-test-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-test-argsstring]]`link:#quarkus-maven-plugin-goal-test-argsstring[argsString]`

[.description]
--

--|String 
|`${quarkus.args}`


a| [[quarkus-maven-plugin-goal-test-builddir]]`link:#quarkus-maven-plugin-goal-test-builddir[buildDir]`

[.description]
--

--|File 
|`${project.build.directory}`


a| [[quarkus-maven-plugin-goal-test-compilerargs]]`link:#quarkus-maven-plugin-goal-test-compilerargs[compilerArgs]`

[.description]
--
Additional parameters to pass to javac when recompiling changed source files.
--|List 
|


a| [[quarkus-maven-plugin-goal-test-compileroptions]]`link:#quarkus-maven-plugin-goal-test-compileroptions[compilerOptions]`

[.description]
--
Additional compiler arguments
--|List 
|


a| [[quarkus-maven-plugin-goal-test-debug]]`link:#quarkus-maven-plugin-goal-test-debug[debug]`

[.description]
--
If this server should be started in debug mode. The default is to start in debug mode and listen on port 5005. Whether the JVM is suspended waiting for a debugger to be attached, depends on the value of `suspend`. 
`debug` supports the following options:   *Value* Effect   *false* The JVM is not started in debug mode   *true* The JVM is started in debug mode and will be listening on `debugHost`:`debugPort`   *client* The JVM is started in client mode, and will attempt to connect to `debugHost`:`debugPort`   *++{++port++}++* The JVM is started in debug mode and will be listening on `debugHost`:++{++port++}++.   By default, `debugHost` has the value "localhost", and `debugPort` is 5005.
--|String 
|`${debug}`


a| [[quarkus-maven-plugin-goal-test-debughost]]`link:#quarkus-maven-plugin-goal-test-debughost[debugHost]`

[.description]
--

--|String 
|`${debugHost}`


a| [[quarkus-maven-plugin-goal-test-debugport]]`link:#quarkus-maven-plugin-goal-test-debugport[debugPort]`

[.description]
--

--|String 
|`${debugPort}`


a| [[quarkus-maven-plugin-goal-test-deletedevjar]]`link:#quarkus-maven-plugin-goal-test-deletedevjar[deleteDevJar]`

[.description]
--

--|boolean 
|`TRUE`


a| [[quarkus-maven-plugin-goal-test-enforcebuildgoal]]`link:#quarkus-maven-plugin-goal-test-enforcebuildgoal[enforceBuildGoal]`

[.description]
--
Whether to enforce the quarkus-maven-plugin build goal to be configured. By default, a missing build goal is considered an inconsistency (although the build goal is not _required_ technically). In this case a warning will be logged and the application will not be started.
--|boolean 
|`${quarkus.enforceBuildGoal}`


a| [[quarkus-maven-plugin-goal-test-environmentvariables]]`link:#quarkus-maven-plugin-goal-test-environmentvariables[environmentVariables]`

[.description]
--

--|Map 
|


a| [[quarkus-maven-plugin-goal-test-jvmargs]]`link:#quarkus-maven-plugin-goal-test-jvmargs[jvmArgs]`

[.description]
--

--|String 
|`${jvm.args}`


a| [[quarkus-maven-plugin-goal-test-mojoexecution]]`link:#quarkus-maven-plugin-goal-test-mojoexecution[mojoExecution]`

[.description]
--

--|MojoExecution 
|`${mojoExecution}`


a| [[quarkus-maven-plugin-goal-test-nodeps]]`link:#quarkus-maven-plugin-goal-test-nodeps[noDeps]`

[.description]
--
Whether changes in the projects that appear to be dependencies of the project containing the application to be launched should trigger hot-reload. By default, they do.
--|boolean 
|`${noDeps}`


a| [[quarkus-maven-plugin-goal-test-openjavalang]]`link:#quarkus-maven-plugin-goal-test-openjavalang[openJavaLang]`

[.description]
--

--|boolean 
|`${open-lang-package}`


a| [[quarkus-maven-plugin-goal-test-outputdirectory]]`link:#quarkus-maven-plugin-goal-test-outputdirectory[outputDirectory]`

[.description]
--
The directory for compiled classes.
--|File 
|`${project.build.outputDirectory}`


a| [[quarkus-maven-plugin-goal-test-pluginrepos]]`link:#quarkus-maven-plugin-goal-test-pluginrepos[pluginRepos]`

[.description]
--

--|List 
|`${project.remotePluginRepositories}`


a| [[quarkus-maven-plugin-goal-test-preventnoverify]]`link:#quarkus-maven-plugin-goal-test-preventnoverify[preventnoverify]`

[.description]
--
This value is intended to be set to true when some generated bytecode is erroneous causing the JVM to crash when the `verify:none` option is set (which is on by default)
--|boolean 
|`${preventnoverify}`


a| [[quarkus-maven-plugin-goal-test-project]]`link:#quarkus-maven-plugin-goal-test-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-test-release]]`link:#quarkus-maven-plugin-goal-test-release[release]`

[.description]
--
The --release argument to javac.
--|String 
|`${maven.compiler.release}`


a| [[quarkus-maven-plugin-goal-test-reposession]]`link:#quarkus-maven-plugin-goal-test-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-test-repos]]`link:#quarkus-maven-plugin-goal-test-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`


a| [[quarkus-maven-plugin-goal-test-session]]`link:#quarkus-maven-plugin-goal-test-session[session]`

[.description]
--

--|MavenSession 
|`${session}`


a| [[quarkus-maven-plugin-goal-test-source]]`link:#quarkus-maven-plugin-goal-test-source[source]`

[.description]
--
The -source argument to javac.
--|String 
|`${maven.compiler.source}`


a| [[quarkus-maven-plugin-goal-test-sourcedir]]`link:#quarkus-maven-plugin-goal-test-sourcedir[sourceDir]`

[.description]
--

--|File 
|`${project.build.sourceDirectory}`


a| [[quarkus-maven-plugin-goal-test-suspend]]`link:#quarkus-maven-plugin-goal-test-suspend[suspend]`

[.description]
--
Whether the JVM launch, in debug mode, should be suspended. This parameter is only relevant when the JVM is launched in `debug debug mode`. This parameter supports the following values (all the allowed values are case-insensitive):   Value Effect   y or true The debug mode JVM launch is suspended   n or false The debug mode JVM is started without suspending
--|String 
|`${suspend}`


a| [[quarkus-maven-plugin-goal-test-systemproperties]]`link:#quarkus-maven-plugin-goal-test-systemproperties[systemProperties]`

[.description]
--

--|Map 
|


a| [[quarkus-maven-plugin-goal-test-target]]`link:#quarkus-maven-plugin-goal-test-target[target]`

[.description]
--
The -target argument to javac.
--|String 
|`${maven.compiler.target}`


a| [[quarkus-maven-plugin-goal-test-workingdir]]`link:#quarkus-maven-plugin-goal-test-workingdir[workingDir]`

[.description]
--

--|File 
|

|===
= quarkus:update

Log Quarkus-related recommended updates, such as new Quarkus platform BOM versions and Quarkus extensions versions that aren't managed by the Quarkus platform BOMs.

:summaryTableId: quarkus-maven-plugin-goals
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|[[quarkus-maven-plugin-goal-update-parameter-parameter]]link:#quarkus-maven-plugin-goal-update-parameter-parameter[Parameter]

h|Type
h|Default

a| [[quarkus-maven-plugin-goal-update-bomartifactid]]`link:#quarkus-maven-plugin-goal-update-bomartifactid[bomArtifactId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-update-bomgroupid]]`link:#quarkus-maven-plugin-goal-update-bomgroupid[bomGroupId]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-update-bomversion]]`link:#quarkus-maven-plugin-goal-update-bomversion[bomVersion]`

[.description]
--

--|String 
|


a| [[quarkus-maven-plugin-goal-update-permodule]]`link:#quarkus-maven-plugin-goal-update-permodule[perModule]`

[.description]
--
If true, the information will be logged per each relevant module of the project instead of an overall summary
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-update-project]]`link:#quarkus-maven-plugin-goal-update-project[project]`

[.description]
--

--|MavenProject 
|`${project}`


a| [[quarkus-maven-plugin-goal-update-recommendedstate]]`link:#quarkus-maven-plugin-goal-update-recommendedstate[recommendedState]`

[.description]
--
If true, the state of the project will be logged as if the recommended updates were applied
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-update-rectify]]`link:#quarkus-maven-plugin-goal-update-rectify[rectify]`

[.description]
--
If true, instead of checking and recommending the latest available Quarkus platform version, recommendations to properly align the current project configuration will be logged (if any)
--|boolean 
|`false`


a| [[quarkus-maven-plugin-goal-update-reposession]]`link:#quarkus-maven-plugin-goal-update-reposession[repoSession]`

[.description]
--

--|RepositorySystemSession 
|`${repositorySystemSession}`


a| [[quarkus-maven-plugin-goal-update-repos]]`link:#quarkus-maven-plugin-goal-update-repos[repos]`

[.description]
--

--|List 
|`${project.remoteProjectRepositories}`

|===
