---
date: 2024-05-29
---
:toc:

[NOTE]
====
We highly recommend the use of https://quarkus.io/guides/update-quarkus[`quarkus update`] to update to a new version of Quarkus.

Items marked below with :gear: :white_check_mark: are automatically handled by https://quarkus.io/guides/update-quarkus[`quarkus update`].
====

== Config

Removed deprecated `ProfileManager#getActiveProfile` and `ProfileManager`. The `ProfileManager` could not handle multiple profiles, added in Quarkus 2.16. To retrieve the active profile, please use `io.quarkus.runtime.configuration.ConfigUtils#getProfiles`. The configuration name used to retrieve the Quarkus profile cannot be appropriately determined by a simple constant definition (as it was in `ProfileManager`); if you need it, please use `LaunchMode.current().getProfileKey()`.

== JPA / Hibernate ORM

=== Upgrade to Hibernate ORM 6.5

The Quarkus extensions for Hibernate ORM was upgraded to Hibernate ORM 6.5.

Hibernate ORM 6.5 is largely backwards-compatible with Hibernate ORM 6.4, but a few checks have been tightened, so applications with incorrect configuration, mapping, or queries may now throw exceptions where they used to experience only warnings and malfunctions.

See the https://github.com/hibernate/hibernate-orm/blob/6.5/migration-guide.adoc[Hibernate ORM 6.5 migration guide] for more details.

[[elasticsearch-opensearch]]
== Elasticsearch/OpenSearch

[[elasticsearch-opensearch-dev-services]]
=== Dev Services

The Elasticsearch/OpenSearch Dev Services now default to starting:

* Elasticsearch 8.13, instead of 8.12 previously
* OpenSearch 2.13, instead of 2.11 previously

To force the use of a specific distribution (Elasticsearch vs. OpenSearch) or version, https://quarkus.io/guides/elasticsearch-dev-services#configuring-the-image[configure the container image explicitly].

== Webjar-locator extension renamed to Web-dependency-locator

The Webjar locator has been enhanced to include https://mvnpm.org[mvnpm], and importmaps. Since this is now more that just webjars, we renamed to reflect this. Read more about the webjar locator https://quarkus.io/version/main/guides/web-dependency-locator[here]
