---
date: 2023-11-29
---
:toc:

[NOTE]
====
We highly recommend the use of https://quarkus.io/guides/update-quarkus[`quarkus update`] to update to a new version of Quarkus.

Items marked below with :gear: :white_check_mark: are automatically handled by https://quarkus.io/guides/update-quarkus[`quarkus update`].
====

== Jaeger and SmallRye OpenTracing extensions retired :gear: :white_check_mark:

After having been deprecated for a long while, the Jaeger and SmallRye OpenTracing extensions have been retired from the Quarkus Platform.

It is recommended to  migrate your applications to OpenTelemetry and a  https://quarkus.io/version/main/guides/telemetry-opentracing-to-otel-tutorial[tutorial is available].

The code of the extensions have been moved to the Quarkiverse and can be consumed from there from now on (relocations have been put in place to avoid breaking your builds).
If you want these extensions to continue working in the future, it is recommended to be involved in their development.

These extensions are not in the Quarkus Platform BOM anymore and you need to define the version yourself in your build file, together with moving to the new groupId:

|===
| Component  | New groupId | Current version | Repository |

| Jaeger | `io.quarkiverse.jaeger` | `1.0.0` | https://github.com/quarkiverse/quarkus-jaeger |
| SmallRye OpenTracing | `io.quarkiverse.opentracing` | `1.0.0` | https://github.com/quarkiverse/quarkus-smallrye-opentracing |
|===

== Kafka extension Strimzi Oauth Support known issue

With version 3.6 the quarkus-bom version of the `io.strimzi:strimzi-kafka-oauth` dependency is updated to `0.14.0`. 
A https://github.com/strimzi/strimzi-kafka-oauth/issues/209[known issue] in this version causes native build failure with the error `" Error: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl is not loaded.`. 

The workaround until the upstream issue is resolved is to add the `io.strimzi:kafka-oauth-common` dependency to the classpath of the Quarkus project.

== Quarkus SmallRye JWT and Reactive Routes

Quarkus SmallRye JWT used to bring the `quarkus-reactive-routes` extension prior to 3.6.
That is not the case anymore in 3.6.

So if you relied on Quarkus SmallRye JWT to bring the `quarkus-reactive-routes` extension, add a dependency to `quarkus-reactive-routes` in your build file.
