---
layout: post
title: 'Quarkus 0.28.1 released - Some more bugfixes, help us squash 404s'
date: 2019-11-04
tags: quarkus release
synopsis: 0.28.1 is a bugfix release. We also made some changes to the guides and quickstarts URLs.
author: gsmet
---

This release is a bugfix/usability improvements release so the upgrade from 0.27.0 should be safe.

Thus, no big changes to announce.

== What's new?

=== New website theme

We just pushed a new theme for the website. We are still working on polishing it but, if you see something weird, please report it in https://github.com/quarkusio/quarkusio.github.io/issues[our tracker].

=== Guides and quickstarts URLs changes

Our guides URLs and our quickstarts directories were not entirely consistent until now. We changed them for more consistency.

We put redirections in place for the guides but we can't do it for the quickstarts directories so if you encounter any broken links on the website, please report them and we'll fix them right away.

Thanks!

=== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/0.28.0[the full changelog of 0.28.0 on GitHub] and https://github.com/quarkusio/quarkus/releases/tag/0.28.1[the one from 0.28.1].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[177 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Alex Soto, Alexey Loubyansky, Aurea Munoz, Bill Burke, Clement Escoffier, Deven Phillips, Emmanuel Bernard, Georgios Andrianakis, Guillaume Smet, Gwenneg Lepage, Hector Ventura, Ioannis Canellos, Jaikiran Pai, Jan Martiska, Jason T. Greene, Ken Finnigan, Luca Burgazzoli, Logan Hauspie, Loïc Mathieu, Maciej Swiderski, Manyanda Chitimbo, Martin Kouba, Martin Stefanko, Matej Novotny, Max Rydahl Andersen, Michael Edgar, Pedro Igor, Ronak Patel, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Stuart Douglas, Syed M Shaaf, Tako Schotanus and Timothy Power.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

