---
layout: post
title: 'Quarkus 0.21.2 released'
date: 2019-09-05
tags: release
synopsis: We just released Quarkus 0.21.2 fixing several bugs and usability issues. Time to upgrade.
author: gsmet
---

We just released Quarkus 0.21.2.

== What's new?

This release is all about fixing bugs, usability and documentation issues. We are still working on our next big release which will be 0.22.0. 

You can find https://github.com/quarkusio/quarkus/releases/tag/0.21.2[the full changelog of 0.21.2] on GitHub.

We have a lot of interesting things in the works so stay tuned.

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[142 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Bertrand Rousseau, chaminnk, Clement Escoffier, Daniel Ribeiro, David M. Lloyd, Dennis Baerten, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Gunnar Morling, Gwenneg Lepage, Maciej Swiderski, Manyanda Chitimbo, Martin Kouba, Matej Novotny, Matteo Mortari, Rostislav Svoboda, Sergey Beryozkin, Stéphane Epardaud and Stuart Douglas.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

