---
layout: post
title: 'Quarkus 1.0.1.Final released - Important security fix'
date: 2019-11-28
tags: release
synopsis: 1.0.1.Final fixes an important security issue. Upgrade highly recommended.
author: gsmet
---

We just released 1.0.1.Final to fix an important security issue introduced in CR2 and still present in 1.0.0.Final.

Please upgrade to this version as soon as possible if you are using our security layer.

== What's new?

=== Security issue fix

If you are using our security annotations (e.g. `@RolesAllowed`) and also other annotations (such as Bean Validation annotations) on the parameters of your secured methods, the security checks would entirely be bypassed.

This issue was originally reported here: https://github.com/quarkusio/quarkus/issues/5763 .

1.0.1.Final fixes this issue and upgrade is highly recommended.

=== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/1.0.1.Final[the full changelog of 1.0.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

