---
layout: post
title: 'Quarkus 1.0.0.Final is here'
date: 2019-11-21
tags: quarkus release
synopsis: After two release candidates, we are happy to announce that Quarkus 1.0.0.Final has been released.
author: gsmet
---

TODO GSM: update date (posts are not visible if dated in the future)

After two release candidates, we are happy to announce that Quarkus 1.0.0.Final has been released. You can read Quarkus 1.0's announcement https://quarkus.io/blog/announcing-quarkus-1-0/[here].

We have now our heads towards the future.

Many thanks to all the communities we rely on and interact with to provide the Quarkus ecosystem: Netty, Vert.x, RESTEasy, SmallRye, Hibernate, Neo4j, Undertow, PostgreSQL, Infinispan, Dekorate, Fabric8, Elytron, Apache Camel, Kogito, and many more, not forgetting Kubernetes, GraalVM and OpenJDK.

Equally important thank you all of the contributors that made Quarkus what it is: TODO GSM insert full list here at last minute to have everyone.

== What's new since 0.28.1

We had 2 release candidates to fix issues and improve developer experience and documentation.

While it was a tremendous amount of work, it was mostly a lot of small adjustments. That being said, there are a few things that should be highlighted and here is a retrospective of these 2 release candidates.

=== Quarkus Platform

If you create a new project using https://code.quarkus.io/, you will notice that the generated project now includes what we call the Platform BOM instead of the usual Quarkus BOM.

What's the difference with the Quarkus BOM you are used to (and you can still use by tweaking the Maven properties)? Mostly that you will be able to use the full Quarkus ecosystem instead of just the core extensions.

For now, it "just" adds all the Camel extensions but, in the future, we expect to have a lot more external extensions and the Platform is what will make them available to your projects.

=== SmallRye OpenAPI and Swagger UI upgrade

Both SmallRye OpenAPI and Swagger UI were upgraded, fixing several bugs the community reported.

=== HttpServletRequest replacement

We had several reports of people being unable to inject `HttpServletRequest` in their JAX-RS resources anymore due to our move to Vert.x by default. RESTEasy now offers a common ground `HttpRequest` class that you can use be it with our Vert.x layer or with Undertow/Servlet.

=== Security

There were quite a lot of fixes and improvements to our security layer.

=== Persistence

Infinispan was upgraded to 10.0.0.Final. We also upgraded Hibernate ORM to fix a few issues.

=== Spring compatibility layer

Our Spring compatibility layer got significantly improved thanks to our community's reports and pull requests. Keep them coming!

=== Sending email with Gmail

We had several reports of people not being able to send emails using our Mailer extension and Gmail. It was a documentation issue and it has been updated to cover more Gmail use cases.

=== Gradle and Kotlin

We fixed a number of issues with our Gradle integration and our Kotlin extension. Contributions in this area are highly welcome!

Note that we are aware that you might have scary unrecommended dependency warnings when using Gradle, this is due to bad isolation between the Gradle build class loader and ours. Don't worry about it for now, we have a plan to fix it soon.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

