---
layout: post
title: 'Quarkus 0.27.0 released - More Amazon Lambda goodness'
date: 2019-10-30
tags: release
synopsis: More Amazon Lambda features, move to Jakarta, usability fixes, go find out what we baked for you.
author: gsmet
---

Another week, another release, this time with a focus on Amazon Lambda, usability and bugfixes.

[NOTE]
====
If you are generating native images, the recommended version of GraalVM is now 19.2.1 so https://www.graalvm.org/downloads/[please upgrade]!
====

== What's new?

=== Amazon Lambda

We were hard at work to get the Amazon Lambda features on par with the Azure Functions ones. You can now use traditional Lambdas or RESTEasy/JAX-RS/Servlet based ones and create your new Lambda projects with simple Maven archetypes.

And... we also added native support!

Learn more about all this in our new guides for link:/guides/amazon-lambda[Amazon Lambda] and link:/guides/amazon-lambda-http[Amazon Lambda with Vert.x Web, Servlet, or RESTEasy].

=== Dev mode detects pom.xml changes

Love live coding with our dev mode? It now detects the changes to your `pom.xml` and reloads the application for you.

=== Producing only one output at a time

We made a major change in how the project outputs (jars, native images) are produced: they are produced one at a time to allow for maximum flexibility and pave the way for output-specific optimizations.

In practice, it won't change things for you except for one use case: if you build a native image, we won't build the runner jar at the same time anymore. Two distinct builds are required.

As a consequence of this change, if you use Docker to build your native images, use the following command from now on:

[source,shell]
----
./mvnw package -Dnative -Dquarkus.native.container-build=true
----

=== Move to Jakarta artifacts

We used to have a mix of `javax.*` and `jakarta.*` artifacts in Quarkus: we have now moved everything to Jakarta.

If your application uses dependencies outside of the Quarkus extension ecosystem, you might now see a warning message saying you are using non recommended artifacts. We warn you so that you don't end up with duplicate implementations of the same classes in your project, which could lead to weird problems. If you are in this case, follow the advice we give you in this warning message and add exclusions/explicit dependencies.

This is a new feature so if you are seeing something weird, report it on the `quarkus-dev` mailing list.

=== Customize Kubernetes manifests via application.properties

Thanks to several improvements made to the Kubernetes extension, you now have a lot more flexibility in how you customize the Kubernetes manifests via our central `application.properties`: learn more about it in link:/guides/kubernetes-resources[the updated documentation].

Moreover, OpenShift manifests can also be generated by the extension.

=== Some Substrate-related renamings

`@SubstrateTest` has been deprecated: use `@NativeImageTest` instead.

If you are an extension author, all the native image-related build items have been renamed: they are now in a `nativeimage` package instead of `substrate` and, if their name contained `Substrate`, you should just replace `Substrate` with `NativeImage` in the name.
We deprecated the old build items, they will be removed at a later stage.

=== War launcher removal

The war launcher has been removed. We don't think anyone was using it but let's be thorough.

=== Full changelog

We also fixed bugs and usability issues: get https://github.com/quarkusio/quarkus/releases/tag/0.27.0[the full changelog of 0.27.0 on GitHub].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[171 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Alessio Soldano, Alex Soto, Alexey Loubyansky, Andy Damevin, Aurea Munoz, Bill Burke, cknoblauch, Clement Escoffier, Daniel Platz, Emmanuel Bernard, Erin Schnabel, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Gwenneg Lepage, Ioannis Canellos, Jaikiran Pai, Jan Martiska, John O'Hara, Jorge Solorzano, Justin Lee, Ken Finnigan, Kolja Markwardt, Krzysztof Urman, Logan Hauspie, Loïc Mathieu, Luis Barreiro, Manyanda Chitimbo, Marcin Czeczko, Martin Kouba, Matej Novotny, Max Rydahl Andersen, Michal Szynkiewicz, Ondra Chaloupka, Pedro Igor, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Stuart Douglas, Stéphane Épardaud, Tako Schotanus, Timothy Power, Tom Jenkinson, Vincent Sevel and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

