---
layout: post
title: 'Quarkus 1.0.0.Final bits are here'
date: 2019-11-25
tags: release
synopsis: After two release candidates, we are happy to announce that Quarkus 1.0.0.Final has been released.
author: gsmet
---

After two release candidates, we are happy to announce that Quarkus 1.0.0.Final has been released. You can read Quarkus 1.0's announcement https://quarkus.io/blog/announcing-quarkus-1-0/[here].
We have now our heads towards the future.

Many thanks to all the communities we rely on and interact with to provide the Quarkus ecosystem:  Netty, Vert.x, RESTEasy, SmallRye, Hibernate, Neo4j, Undertow, PostgreSQL, Infinispan, Dekorate, Fabric8, Elytron, Apache Camel, Kogito, and many many more, not forgetting Kubernetes, GraalVM and OpenJDK.

Equally important, deep thanks to all of the contributors that made Quarkus what it is: 16yuki0702, Adam Bien, Alessio Soldano, Alex Kochnev, Alex Soto, Alexey Loubyansky, Alexey Volkov, Aleš Justin, Anamarija Talijanac, Andrea Boriero, Andrea Cosentino, Andrej Petras, Andres Almiray, Andrew Guibert, Andy Damevin, Andy Muir, Anthony Dahanne, Antoine Sabot-Durand, Antonio Goncalves, Aris Tzoumas, Arnaud Heritier, Arne Mejlholm, Arnost Valicek, Aurea Munoz, Bartosz Firyn, Bill Burke, Bob McWhirter, Brent Douglas, Bruno Borges, Bruno Devaux, Chamin Kahandawaarachchi, Chao Wang, Chris Laprun, cknoblauch, Clement Escoffier, Cristhian Lopez, Cristiano Nicolai, Damien Clément D'Huart, Dan McPherson, Daniel Petisme, Daniel Platz, Daniel Ribeiro, Darin Pope, David M. Lloyd, Dennis Baerten, Deven Phillips, Dmitry Telegin, Don Naro, Dusan Odalovic, Edoardo Vacchi, Emmanuel Bernard, Emmanuel Feller, Erin Schnabel, Esteban Aliverti, Fabian Martinez, Fabio Heer, Fabrice Pipart, Federico Fissore, Frank de Jong, Fred Bricon, Galder Zamarreño, Gary Brown, Gary Tierney, George Gastaldi, Georgios Andrianakis, Guillaume Dufour, Guillaume Nodet, Guillaume Smet, Gunnar Morling, Gwenneg Lepage, Hantsy Bai, Harald Reinmüller, Hector Ventura, Ioannis Canellos, Irena Kezic, Ivan Gregurić Ortolan, Jacob Middag, Jaikiran Pai, James Perkins, Jan Martiska, Jason Porter, Jason T. Greene, Jasper Huzen, Jean-Baptiste Nizet, Jeff Maury, Jeff Mesnil, Jérémie Bresson, Jesper Skov, Jim Ma, Jim Tyrrell, Jirka Kremser, John O'Hara, John Oliver, Jonathan Dowland, Jorge Solorzano, Jose Quaresma, Juri Berlanda, Justin Lee, jycr, Juan Zuriaga, Kamesh Sampath, Katia Aresti, Kazuhiro Sera, Ken Finnigan, Klearchos Klearchou, Kolja Markwardt, Krzysztof Urman, Libor Krzyzanek, Logan Hauspie, Loïc Mathieu, Luca Burgazzoli, Luis Barreiro, Łukasz Kostrzewa, Łukasz Włódarczyk, Maarten Dirkse, Maarten Mulders, Maciej Swiderski, Manaswini Das, Manyanda Chitimbo, Marcin Czeczko, Marco Mornati, Marek Marusic, Mario Fusco, Mark Little, Martin Kouba, Martin Panzer, Martin Stefanko, Masatoshi Hayashi, Matej Novotny, Mathias Geat, Matteo Mortari, Matthias Andreas Benkard, Max Rydahl Andersen, Michael Bornholdt Nielsen, Michael Edgar, Michael Musgrove, Michael Simons, Michael Vorburger, Michal Karm Babacek, Michał Szynkiewicz, Minto van der Sluis, Mitesh Aghera, Moncef Aoudia, Myron Randall, Nelson Graça, Nicolas Delsaux, Nils Hartmann, Norito Agetsuma, Ondra Chaloupka, Paolo Patierno, Paulo Lieuthier, Pavol Loffay, Paweł Żalejko, Pedro Igor, Peter Palaga, Peter Sönder, Radim Vansa, Renann Prado, Roberto Gamarra, Romain Quinio, Ronak Patel, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Scott M Stark, Sébastien Blanc, Sebastián Estévez, Sergey Beryozkin, Simon Bengtsson, soberich, Soroosh Sarabadani, Stéphane Epardaud, Stuart Douglas, Ståle Pedersen, Summers Pittman, Syed M Shaaf, Tako Schotanus, Thomas Andraschko, Thomas Qvarnström, Thomas Segismont, Tiago Dolphine, Timm Hirsens, Timothy Power, Tom Jenkinson, Tomas Hofman, Tomaz Cerar, Vincent Sevel, William Burns, William Siqueira, Wouter Oet and Yoann Rodière.

== What's new since 0.28.1

We had 2 release candidates to fix issues and improve developer experience and documentation.
While it was a tremendous amount of work, it was mostly a lot of small adjustments. That being said, there are a few things that should be highlighted and here is a retrospective of these 2 release candidates.

[NOTE]
====
If you are building native images with GraalVM, be sure to use 19.2.1. Support for 19.3.0 is planned for Quarkus 1.1.
====

=== Quarkus Platform

If you create a new project using https://code.quarkus.io/, you will notice that the generated project now includes what we call the Platform BOM instead of the usual Quarkus BOM.

What's the difference with the Quarkus BOM you are used to (and you can still use by tweaking the Maven properties)? Mostly that you will be able to use the full Quarkus ecosystem instead of just the core extensions.

To better increase the Quarkus ecosystem, we have separated the notion of extension publication from the notion of Quarkus Core release.
Concretely today, it adds all the Apache Camel extensions but more are coming.

=== SmallRye OpenAPI and Swagger UI upgrade

Both SmallRye OpenAPI and Swagger UI were upgraded, fixing several bugs the community reported.

=== HttpServletRequest replacement

We had several reports of people being unable to inject `HttpServletRequest` in their JAX-RS resources anymore due to our move to Vert.x by default. RESTEasy now offers a common ground `HttpRequest` class that you can use be it with our Vert.x layer or with Undertow/Servlet.

=== Security

There were quite a lot of fixes and improvements to our security layer.

=== Persistence

Infinispan was upgraded to 10.0.0.Final. We also upgraded Hibernate ORM to fix a few issues.

=== Spring compatibility layer

Our Spring compatibility layer got significantly improved thanks to our community's reports and pull requests. Keep them coming!

=== Sending email with Gmail

We had several reports of people not being able to send emails using our Mailer extension and Gmail. It was a documentation issue and it has been updated to cover more Gmail use cases.

=== Gradle and Kotlin

We fixed a number of issues with our Gradle integration and our Kotlin extension. Contributions in this area are highly welcome!

You might have scary unrecommended dependency warnings when using Gradle, this is due to some isolation problems between the Gradle build class loader and ours. Don't worry about it for now, we have a plan to fix it soon.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

