---
layout: post
title: 'Quarkus 0.22.0 released'
date: 2019-09-16
tags: release
synopsis: We just released Quarkus 0.22.0 with improved Spring API support.
author: gsmet
---

We just released Quarkus 0.22.0 including an improved Spring API support.

We also officially launch https://code.quarkus.io/[code.quarkus.io]: it has never been easier to create a Quarkus application.

== What's new?

=== Improved Spring API support

Quarkus has had https://quarkus.io/guides/spring-di[a Quarkus Extension for Spring Dependency Injection API] since its initial release. The plan has always been to extend Spring API support and executing on that plan, this release brings the addition of https://quarkus.io/guides/spring-web[the Quarkus Extension for Spring Web API] and https://quarkus.io/guides/spring-data-jpa[the Quarkus Extension for Spring Data JPA API].

Spring developers can now feel at home with Quarkus while benefiting from features like out-of-the-box support for live coding and native compilation.

=== code.quarkus.io

It has been in the works for a while and we are proud to officially launch https://code.quarkus.io/[code.quarkus.io], a user-friendly web interface to create your Quarkus applications. It also constitutes a great tool to explore the full breadth of our extension ecosystem.

=== New extensions

The extension ecosystem is growing very nicely.
We are working on a model to streamline extension publications. We call this effort the Quarkus platform.
In the mean time we have seen community members wanting to collaborate on extensions, we have created a https://github.com/quarkusio/quarkus/issues/new?assignees=&labels=extension-proposal&template=extension_proposal.md&title=[new issue template] and https://github.com/quarkusio/quarkus/labels/extension-proposal[GitHub tag] to capture these.

=== Full changelog

We also fixed a few bugs and usability issues: get https://github.com/quarkusio/quarkus/releases/tag/0.22.0[the full changelog of 0.22.0 on GitHub].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[148 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Aurea Munoz, Clement Escoffier, David M. Lloyd, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Gwenneg Lepage, Manyanda Chitimbo, mejlholm, Stephane Epardaud and Stuart Douglas.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

