---
layout: post
title: 'Quarkus 0.19.1 released'
date: 2019-07-11
tags: release
author: gsmet
---

We just released Quarkus 0.19.1.

This new version brings a lot of new extensions, especially in the persistence area.

[NOTE]
====
Quarkus 0.19.1 is still targeting GraalVM 19.0.2 as we discovered a bug in GraalVM 19.1.0 that affects Quarkus.

The issue is already fixed but we are waiting for a 19.1.1 release.
====

== What's new?

Here are the main highlights of this release: MongoDB support, Neo4J support, Amazon DynamoDB support, Apache Tika support, Reactive Messaging MQTT support and better Hibernate ORM schema upgrade (useful for dev mode).

=== Hibernate ORM schema management improvements

We had a few issues with automatic schema upgrades handled by Hibernate ORM. Things are now smoother and we significantly improved the documentation to explain https://quarkus.io/guides/hibernate-orm#hibernate-orm-in-development-mode[how to configure schema management in various situations].

=== New extensions

==== MongoDB extension

https://www.mongodb.com/[MongoDB] needs no introduction as it's probably the most widely used NoSQL datastore.
We had a lot of users asking for MongoDB support in Quarkus and here we are: we now have a fully featured MongoDB client extension.

It supports imperative and reactive and comes with a lot of configuration properties to tune the client. And, of course, you can use it with GraalVM.

You can learn more about it in the link:/guides/mongodb[MongoDB client guide].

==== Neo4j extension

https://neo4j.com/[Neo4j] is a graph database management system focused not only on the data itself, but especially on the relations between data.

Neo4j offers Cypher, a declarative query language much like SQL.
Cypher is used to query the graph, telling the database engine what patterns to match and how.
Clients communicate over the so called Bolt protocol with the database.

Quarkus now offers a Neo4j extension so that you can easily use Neo4j with Quarkus in JVM and native mode.

Want to give it a try? We have link:/guides/neo4j[a guide] for you.

==== Amazon DynamoDB extension

https://aws.amazon.com/dynamodb/[Amazon DynamoDB] is a key-value and document database available on AWS.

The first version of this extensions allow to leverage Amazon DynamoDB features in JVM and native mode but it is not fully "quarked" yet.
Future iterations will bring Quarkus-style config and the ability to inject the client directly with CDI.

In the meantime, you can create your client manually and give us feedback about the configuration knobs you want us to expose.

==== Apache Tika extension

http://tika.apache.org/[Apache Tika] is a framework to extract data from documents (and especially binary ones such as PDF documents). With the Apache Tika Quarkus extension, just inject a `TikaParser` and you can extract the information from your documents. Yes, in native mode too.

==== Reactive Messaging MQTT connector

http://mqtt.org/[MQTT] is a machine-to-machine/IoT connectivity protocol. Our reactive messaging layer is growing and we now have support for it.

=== Full changelog

We also fixed some issues and merged a lot of improvements all over the place.

You can find https://github.com/quarkusio/quarkus/releases/tag/0.19.0[the full changelog of 0.19.0 release on GitHub] and also https://github.com/quarkusio/quarkus/releases/tag/0.19.1[the additional issues we fixed in 0.19.1].

== Where is 0.19.0?

We found a regression in our Gradle support while releasing 0.19.0, that's why we released 0.19.1 right away.

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[116 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Alessio Soldano, Alexey Loubyansky, Arnost Valicek, Clement Escoffier, David M. Lloyd, Emmanuel Bernard, Federico Fissore, Gary Tierney, George Gastaldi, Georgios Andrianakis, Guillaume Dufour, Guillaume Smet, Gwenneg Lepage, Jason T. Greene, Jasper Huzen, Ken Finnigan, Loïc Mathieu, Maciej Swiderski, Manyanda Chitimbo, Marcin Czeczko, Martin Kouba, Martin Panzer, Martin Stefanko, Michael Simons, Michal Szynkiewicz, Pedro Igor, Romain Quinio, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Stéphane Epardaud and Stuart Douglas.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

