---
layout: post
title: 'Quarkus 0.23.2 released - Back on track'
date: 2019-10-02
tags: release
synopsis: 0.23.2 fixes the memory usage increase observed in 0.23.
author: gsmet
---

Last week, we released link:/blog/quarkus-0-23-1-released/[Quarkus 0.23.1] which paved the way towards our new Vert.x based HTTP layer and brought a lot of new features (see link:/blog/quarkus-0-23-1-released/[the original announcement post] for all the details).
We discovered a memory usage regression shortly after the release: it was not a memory leak or anything that bad but an increased memory usage due to Netty getting a bit too comfortable.

Today, we release 0.23.2, which contains all the great features of 0.23 and has better intentions on the memory side.

[NOTE]
====
The recommended version of GraalVM is now 19.2.0.1 so https://www.graalvm.org/downloads/[please upgrade]!
====

== What's new?

=== Better Netty tuning

0.23 comes with the foundations of a brand new HTTP layer based on Vert.x and Netty.
By default, Netty has a tendency to initialize a significant amount of memory at startup for performance reasons.
This is obviously not ideal in highly constrained environments.

Another issue we had is that some Netty classes were initialized at build time and the hardware on which you built your application was used as the reference for Netty autotuning.
This doesn't fly in a container world.

Both issues were fixed in 0.23.2.

=== Full changelog

We also fixed a few bugs and usability issues: get https://github.com/quarkusio/quarkus/releases/tag/0.23.2[the full changelog of 0.23.2 on GitHub].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[152 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Adam Bien, Andrej Petras, Clement Escoffier, George Gastaldi, Guillaume Smet, Jaikiran Pai, Jason T. Greene, Radim Vansa and Stuart Douglas.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

