---
layout: post
title: 'Quarkus 0.21.1 released'
date: 2019-08-15
tags: release
author: gsmet
---

We just released Quarkus 0.21.1.

As for 0.20.0, to build native executables, you will need GraalVM 19.1.1.

== What's new?

This release is mostly about fixing bugs and usability issues. The link:/guides/kafka-streams[Kafka Streams] and link:/guides/tika[Apache Tika] extensions got their usability greatly improved for instance.

You can find https://github.com/quarkusio/quarkus/releases/tag/0.21.0[the full changelog of 0.21.0] and https://github.com/quarkusio/quarkus/releases/tag/0.21.1[the few additional issues we fixed in 0.21.1] on GitHub.

We have a lot of interesting things in the works so stay tuned for our late August and September announcements.

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[130 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Alessio Soldano, Alexey Loubyansky, Andy Damevin, Aurea Munoz, Daniel Petisme, Emmanuel Bernard, Fabian Martinez, Georgios Andrianakis, Guillaume Dufour, Guillaume Smet, Gunnar Morling, Gwenneg Lepage, Jan Martiska, Jason T. Greene, Jorge Solorzano, Ken Finnigan, Loïc Mathieu, Łukasz Kostrzewa, Manaswini Das, Manyanda Chitimbo, Martin Kouba, Matej Novotny, Peter Palaga, Rostislav Svoboda, Sergey Beryozkin, and Stuart Douglas.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

