---
layout: post
title: 'Quarkus 0.26.1 released - Stabilizing things and adding Vault support'
date: 2019-10-23
tags: release
synopsis: Quarkus 0.26.1 comes with bugfixes and doc improvements. It also adds an extension for Vault support.
author: gsmet
---

Keeping the rapid pace of one release per week, here comes Quarkus 0.26.1.

Thanks a lot to the community at large for the useful bug reports, that helps a lot in stabilizing the new HTTP and security layers. Keep them coming.

Apart from bugfixes, the new big thing in 0.26.1 is an extension adding support for https://www.vaultproject.io/[HashiCorp Vault].

[NOTE]
====
The recommended version of GraalVM is still 19.2.0.1 as the 19.2.1 artifacts are still not published on Central.
====

== What's new?

=== Vault support

The latest addition in Quarkus extension universe is a Vault extension. No more plain text database credentials in your configuration files: you can now store them securely in https://www.vaultproject.io/[Vault].

The extension comes with a MicroProfile config source so you can directly inject secured properties coming from Vault in your application.

More on that in https://quarkus.io/guides/vault[our extensive guide].

As usual for new extensions, feedback is highly welcome, be it positive feedback or bug reports.

=== Gradle plugin published on Gradle portal

The Gradle plugin is now published https://plugins.gradle.org/plugin/io.quarkus[on the Gradle portal] for each new version as part of our release process.

=== Live reload issue on Windows

This time, https://github.com/quarkusio/quarkus/issues/3592[the infamous `InvalidPathException` on live reload issue] should be fully solved. There was one remaining problem with JDK 11+ due to a JDK bug.

=== Full changelog

We also fixed a few bugs and usability issues: get https://github.com/quarkusio/quarkus/releases/tag/0.26.0[the full changelog of 0.26.0 on GitHub] - and, if you're really curious, https://github.com/quarkusio/quarkus/releases/tag/0.26.1[the issues we fixed in 0.26.1].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[166 contributors].
Many many thanks to each and everyone of them.

In particular for this release, thanks to Alexey Loubyansky, Andrew Guibert, Andy Damevin, cknoblauch, Clement Escoffier, Daniel Petisme, Dusan Odalovic, Gary Brown, George Gastaldi, Georgios Andrianakis, Guillaume Nodet, Guillaume Smet, Gwenneg Lepage, Jaikiran Pai, Jan Martiska, John OHara, Ken Finnigan, Maciej Swiderski, Manyanda Chitimbo, Martin Kouba, Max Rydahl Andersen, Minto van der Sluis, Nelson Graça, Pedro Igor, Sanne Grinovero, Sergey Beryozkin, Stuart Douglas, Stéphane Épardaud, Tom Jenkinson and Vincent Sevel.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

