---
layout: post
title: 'Quarkus 1.3.1.Final released - Bugfixes, JDK 11 by default'
date: 2020-03-28
tags: release
synopsis: 1.3.1.Final fixes some issues and bring some documentation improvements. Generated projects are now using Java 11 by default.
author: gsmet
---

Today, we released 1.3.1.Final which is a bugfix version on top of 1.3.0.Final.
This version contains bugfixes and documentation improvements and makes Java 11 our default target for newly generated projects.

This is a safe upgrade for everyone using 1.3.0.Final.

== What's new?

=== Java 11 by default

This was an oversight in 1.3.0.Final and we decided to fix it now rather than waiting for 1.4.

From now on, newly generated projects target Java 11 by default, including the ones generated by https://code.quarkus.io/. This also means that all the default container images have been upgraded to Java 11.

If you use Java 8 to create a project locally, the project still targets Java 8 though.

[WARNING]
====
We will deprecate the Java 8 support in 1.4. You will have a nice warning if you are using Java 8 with Quarkus.

We plan to drop Java 8 support in a few releases, probably around 1.6.
====

=== MongoDB client socket-timeout renamed to read-timeout

The `quarkus.mongodb.socket-timeout` configuration property was previously ignored. We fixed that and in passing, we renamed it to `quarkus.mongodb.read-timeout` to be more accurate.

If you used it, you will now get a warning about having an unapplied property but the behavior will be the same as before i.e. the property not being applied. If you want to configure it, just replace the old name with the new one.

=== Bugfixes and documentation improvements

You can get https://github.com/quarkusio/quarkus/releases/tag/1.3.1.Final[the full changelog of 1.3.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

