---
layout: post
title: 'Quarkus Insights #3: Hibernate with Panache'
date: 2020-05-20  
tags: insights
synopsis: Stéphane talks us through how to do Hibernate with Panache.
author: maxandersen
---

Monday we did https://www.youtube.com/watch?v=t84sdt9Mnmw[Quarkus Insights episode #3: Hibernate Panache] 
with Stéphane through what Panache is, why it is awesome and how you get the most out of it.

video::t84sdt9Mnmw[youtube,width=640, height=360]

== Podcast feed

If you prefer to listen to these in podcast format they are now available from https://podcasts.apple.com/ch/podcast/quarkus-insights/id1513810337[Apple Podcasts] and should shouw up in Spotify podcasts shortly too.

== Next Episode(s)

On Monday May 25th 05:00 EST / 11:00 CEST / 14:30 IST we will do Quarkus Insights #4: https://www.youtube.com/watch?v=MJe2giXrbuM[JHipster with Quarkus] with https://twitter.com/dpetisme[Daniel Petisme].

He will come and talk about how he utilized JHipster to build a blueprint for Quarkus to scaffold full applications.

On Tuesday June 2nd at 09:00 EST / 15:00 CET / 18:30 IT its Quarkus Insights #5: https://youtu.be/6XVBa5YlEsw[Quarkify.net]

https://twitter.com/dmi3coder[Dmitry Chaban] to talk about his work and his Quarkus efforts on Quarkify.net

Do add questions to the youtube video already or show up on the live show and ask away - we will cover as much as we can!

To join current live show or see the next one scheduled bookmark this link: https://youtube.com/quarkusio/live
 
