---
layout: post
title: 'Quarkus 1.6.1.Final released - Bugfixes'
date: 2020-07-21
tags: release
synopsis: 1.6.1.Final fixes some regressions and bugs and also got some documentation improvements. 
author: gsmet
---

Today, we released Quarkus 1.6.1.Final with some bugfixes and documentation improvements.

It is a safe upgrade for everyone using 1.6.0.Final.

== What's new?

Apart from bugfixes and usability improvements, Quarkus 1.6.1.Final introduces one behavior change:
when building a native executable with GraalVM, the `file.encoding` is now set to UTF-8.
It won't change anything if you were using an UTF-8 system but it should be better if you were using non-UTF-8 locales on your system.

This behavior is enforced.
If you have a case requiring the `file.encoding` to be configurable, please reach out to us via the usual channels.

Thanks to our contributors, we also made numerous improvements to the documentation.

You can get https://github.com/quarkusio/quarkus/releases/tag/1.6.1.Final[the full changelog of 1.6.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

