---
layout: post
title: Free Quarkus Sessions at Red Hat Summit
date: 2020-04-24
tags: conference user-story
synopsis: A handy guide to Quarkus sessions at Red Hat's free Summit Virtual Experience. 
author: jclingan
---

In case you haven't heard, next week's https://www.redhat.com/en/summit[Red Hat Summit] is an online "Virtual Experience" with all of its content freely available (with registration)!

Here is a handy session guide for the <<keynote>>, <<technical>>, and <<stories>>, where Quarkus is either covered or is the central topic. Registration starts Monday.

== Keynote [[keynote]]
[width="100%",options="header",cols="3,^1,^1,^1"]
|====================
| Session | NA & LATAM | EMEA |  APAC
|Session #3 - From the private datacenter to the edge demo 3+^| 
Wednesday 9:00am EDT +
< ---- https://www.redhat.com/en/summit/agenda/agenda-at-a-glance[link] ---- >
|====================


== Technical Sessions [[technical]]

[width="100%",options="header",cols="3,^1,^1,^1"]
|====================
| Session | NA & LATAM | EMEA |  APAC
| Red Hat Middleware strategy and the future of Java 3+^| 
< ----
https://summit.redhat.com/conference/sessions/details/7be205cc-0422-4b9a-8e10-e34fc4d941ca?sb=false[link] ---- >
| Event-driven architecture with Quarkus, Kafka, and OpenShift ^|
Tuesday +
April 28th +
11:00 am EDT

https://summit.redhat.com/conference/sessions/details/06dee82e-ef89-4d98-9bf1-6c07f7d984ce?sb=false[link] ^| 
Tuesday +
April 28th +
5:00 pm CEST

https://summit.redhat.com/conference/sessions/details/7c072066-cc5e-4405-a354-899963cdb487?sb=false[link] ^|
Tuesday +
April 28 +
11:00 pm SGT

https://summit.redhat.com/conference/sessions/details/e41613c9-efff-45b0-942e-65a415b06b93?sb=false[link]
| @Autowire MicroProfile into Spring with Quarkus ^|
Wednesday +
April 29th +
1:00 pm EDT

https://summit.redhat.com/conference/sessions/details/d6050d28-f1cd-4684-88d0-05019c04ba9c?sb=false[link] ^| 
Wednesday +
April 29th +
1:00 pm CEST

https://summit.redhat.com/conference/sessions/details/a79ac340-1370-43c4-990d-29b94fe1fd7f?sb=false[link] ^|
Wednesday +
April 29 +
4:00 pm SGT

https://summit.redhat.com/conference/sessions/details/e6224f58-c4bd-48e2-8e63-bd695ad632f1?sb=false[link]
| Apache Camel 3—the next generation of enterprise integration ^|
Tuesday +
April 28th +
1:00 pm EDT

https://summit.redhat.com/conference/sessions/details/33450aab-45a1-4c20-ae18-32ebdd2329a4?sb=false[link] ^|
Tuesday +
April 28th +
7:00 pm CEST

https://summit.redhat.com/conference/sessions/details/5b130cf5-d4eb-4c68-b715-c859945f9303?sb=false[link] ^|
Wednesday +
April 29 +
8:00 am SGT

https://summit.redhat.com/conference/sessions/details/68332c0b-5769-47fc-b21b-d7b315513fd1?sb=false[link]
| Live coding 12-factor  ^|
Tuesday +
April 28th +
2:00 pm EDT

https://summit.redhat.com/conference/sessions/details/8959cc33-da59-456e-a955-91e887f6eadc?sb=false[link] ^|
Tuesday +
April 28th +
8:00 pm CEST

https://summit.redhat.com/conference/sessions/details/a8848c2f-9e3d-4e23-81cf-390fb939d1a7?sb=false[link] ^|
Wednesday +
April 29 +
11:00 am SGT

https://summit.redhat.com/conference/sessions/details/1dffa243-48b9-4bb0-8936-ef6bdf050324?sb=false[link]
| Serverless COBOL: Migrating legacy copybooks to a containerized cloud-native environment  3+^|
Wednesday +
April 29 +
10:00 am CEST

https://summit.redhat.com/conference/sessions/details/5a26074a-e8b1-4a95-8a68-010f8668da62?sb=false[link]
| Why building intelligent cloud-native business applications is easier with Kogito  ^|
Wednesday +
April 29th +
1:00 pm EDT

https://summit.redhat.com/conference/sessions/details/f9d36108-dde2-4b75-aeca-c7a9f38e4c60?sb=false[link] ^|
Wednesday +
April 29th +
1:00 pm CEST

https://summit.redhat.com/conference/sessions/details/a2519a01-b954-448b-9ec1-1326ee779960?sb=false[link] ^|
Wednesday +
April 29 +
4:00 pm SGT

https://summit.redhat.com/conference/sessions/details/b67fb55b-3931-45ff-8014-e0ab58163741?sb=false[link]
| Cloud-native secret management for microservices using Vault on OpenShift 3+^|

< ---- https://summit.redhat.com/conference/sessions/details/6b988f8d-ce9c-448a-830b-3d9f536eb520?sb=false[link] ---- >
| Solve the unsolvable: Why artificial intelligent systems can solve planning problems better than humans  ^|
Wednesday +
April 29th +
2:00 pm EDT

https://summit.redhat.com/conference/sessions/details/3d11278e-fc22-4d7d-944d-966cdf0a328b?sb=false[link] ^|
Wednesday +
April 29th +
5:00 pm CEST

https://summit.redhat.com/conference/sessions/details/2a8c60db-9c2c-4eef-ae58-74766528a070?sb=false[link] ^|
Wednesday +
April 29 +
5:00 pm SGT

https://summit.redhat.com/conference/sessions/details/bb5d9ab5-214d-4a10-8299-aa113ad9c958?sb=false[link]
|====================
 



== Quarkus in Production Customer Sessions [[stories]]

[width="100%",options="header",cols="3,^1,^1,^1"]
|====================
| Session | NA & LATAM | EMEA |  APAC
| Vodafone Greece's exciting migration journey from SpringBoot to Quarkus | Tuesday +
April 28th +
4:00 pm EDT 

https://summit.redhat.com/conference/sessions/details/0768ccdb-2ebe-445c-aa72-33d979852ad3?sb=false[link] | Wednesday +
April 29 +
7:00 am CEST

https://summit.redhat.com/conference/sessions/details/22e41661-d84c-436c-bebc-377bd6ee26bf?sb=false[link] | Wednesday +
April 29 +
12:00 pm SGT

https://summit.redhat.com/conference/sessions/details/4c877dcf-51bb-4e0a-8c3e-c17151b0398c?sb=false[link]
| Making Java subatomic in OpenShift—the Lufthansa Technik Quarkus |
Tuesday +
April 28th +
11:00 am EDT

https://summit.redhat.com/conference/sessions/details/302b843d-16e7-44ff-983e-cc87054ad0d7?sb=false[link] | 
Tuesday +
April 28th +
5:00 pm CEST

https://summit.redhat.com/conference/sessions/details/ce4f2278-65bc-417f-a8bd-81d179b30737?sb=false[link] |
Tuesday +
April 28 +
11:00 pm SGT

https://summit.redhat.com/conference/sessions/details/05a14c26-9b3a-4832-9b11-bcb3e72465fe?sb=false[link]
| Empowering Amadeus’ competitive advantage with cloud-native decision making on Quarkus |
Tuesday +
April 28th +
2:00 pm EDT

https://summit.redhat.com/conference/sessions/details/9938bf24-3e21-4503-99d9-d7fd12dd3f2f?sb=false[link] |
Tuesday +
April 28th +
8:00 pm CEST

https://summit.redhat.com/conference/sessions/details/a0f86841-13c8-4aec-857e-8818903ff728?sb=false[link] |
Wednesday +
April 29 +
11:00 am SGT

https://summit.redhat.com/conference/sessions/details/d30cc281-1caf-485f-8598-b10780f61319?sb=false[link]
| Transforming decision automation to be cloud-based and FaaS-like at BBVA 3+^| < ---- https://summit.redhat.com/conference/sessions/details/b007a212-3342-4ca3-9d25-8adf54b93def?sb=false[link] ---- > 
|====================
