---
layout: post
title: 'Quarkus 1.4 released - Command mode, HTTP 2, New FaaS framework, Mocking...'
date: 2020-04-27
tags: release
synopsis: Quarkus 1.4 brings command mode, HTTP 2 support, a new FaaS framework called Funqy, new mocking features and much more.
author: gsmet
---

Here comes the time of the month when you get your new Quarkus release: 1.4.1.Final is here.
No 1.4.0.Final, we had to skip it.

This version is packed with very nice features and includes tons of improvements and bugfixes:

 * Command mode
 * HTTP/2
 * New FaaS framework called Funqy
 * Improvements around mocking
 * Keycloak admin client
 * SmallRye Reactive Messaging 2.0
 * MongoDB client 4
 * Amazon Alexa extension
 * LDAP authentication
 * Improvements to the Vault support

We also made some nice performance improvements so your Quarkus applications should be faster than ever!

== Migration Guide

Eager to migrate your existing applications? Here is https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.4[our migration guide for 1.4].

== What's new?

=== Java 8 deprecated

Building Quarkus applications with Java 8 is now deprecated.
We recommend using Java 11 from now on.

We plan to drop Java 8 support for Quarkus 1.6 so in roughly two months.
If you have a strong case for us keeping Java 8 support longer, please reach out to us on our `quarkus-dev` mailing list.

=== Command mode

Until now, Quarkus goodness was reserved to server applications but these times are over!

You can now build command line applications with Quarkus using the new command mode.
Find out all about it in link:/guides/command-mode-reference[our dedicated reference documentation].

Stay tuned, we will publish a specific blog post shortly.

=== HTTP/2

Quarkus now supports HTTP/2. It is enabled by default but can be disabled by setting `quarkus.http.http2` to `false`.

=== New FaaS framework

We improved a lot on the function front (namely AWS Lambdas and Azure Functions) with the introduction of a new FaaS framework called Funqy.

A blog post will soon explain everything you need to know about Funky but in the meantime, you can refer to the updated documentation:

 * link:/guides/amazon-lambda[Amazon Lambda]
 * link:/guides/amazon-lambda-http[Amazon Lambda with RESTEasy, Undertow, or Vert.x Web]
 * link:/guides/azure-functions-http[Azure Functions (Serverless) with RESTEasy, Undertow, or Vert.x Web]

=== Improvements around mocking

Mocking CDI beans is now easier than ever. We also have a nice integration with Mockito.

For more information, please refer to our link:/guides/getting-started-testing[Testing your application guide].

Again, blog post coming soon!

=== MongoDB client upgrade

The MongoDB client has been upgraded to version 4. This might break a few applications and might require some code updates.

=== Vault

The default version of the Vault KV Secret Engine is now version 2. You can go back to v1 with some configuration.

Support for link:/guides/vault#totp[the Vault TOTP engine] was added, as well as two new topic guides:

 * link:/guides/vault-auth[Working with HashiCorp Vault’s Authentication]
 * link:/guides/vault-datasource[Using HashiCorp Vault with Databases]

=== New extensions

==== Keycloak Admin Client

We had some issues with the Keycloak Admin Client in previous versions.

We added a dedicated extension called `quarkus-keycloak-admin-client` to ensure a smooth experience.

==== Amazon Alexa

Amazon Alexa is now supported in native thanks to the addition of the `quarkus-amazon-alexa` extension.

==== LDAP authentication

We added LDAP to the list of authentication stores supported out of the box by Quarkus.

=== And more...

 * SmallRye Reactive Messaging has been updated to 2.0.
 * A lot of component upgrades, bugfixes and small improvements.

=== Full changelog

You can get the full changelogs of https://github.com/quarkusio/quarkus/releases/tag/1.4.0.CR1[1.4.0.CR1], https://github.com/quarkusio/quarkus/releases/tag/1.4.0.Final[1.4.0.Final] and https://github.com/quarkusio/quarkus/releases/tag/1.4.1.Final[1.4.1.Final] on GitHub.

== ADOPTERS.md

To share stories about Quarkus usage, we added https://github.com/quarkusio/quarkus/blob/master/ADOPTERS.md[an `ADOPTERS.md` file] at the root of the repository.

If you are using Quarkus and would like to be interviewed on our blog or simply added to this file, please contact us and we will be happy to oblige.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[269 contributors].
Many many thanks to each and everyone of them.

In particular for the 1.4 release, thanks to Aaron Rogers, Adrian, Adrian Fiedler, Akito Kidani, Alex Soto, Alexander Schwartz, Alexey Loubyansky, Andrej Petras, András Péteri, Andy Damevin, Antoine Sabot-Durand, Antonio Goncalves, Aurea Munoz, Bartosz Firyn, Bill Burke, Cem Nura, Clement Escoffier, Daniel Petisme, Daniel Wamara, Daniel Platz, David M. Lloyd, Emmanuel Bernard, Erik Mattheis, Falko Modler, Felix Wong, Galder Zamarreño, Geoffrey De Smet, George Doenlen, George Gastaldi, Georgios Andrianakis, Guillaume Le Floch, Guillaume Smet, Gwenneg Lepage, Gytis Trikleris, Harold Sun, Harsha R, Ioannis Canellos, Jaikiran Pai, Jan Martiska, Jason T. Greene, Jesper Skov, Jiri Ondrusek, Johan Westerlund, John O'Hara, Jonas Scholz, Jordan Moore, Jozef Hartinger, Julian Cui, Justin Holmes, Ken Finnigan, Ladislav Thon, Loïc Mathieu, Luis F Munoz, Manyanda Chitimbo, Marc Boissonneault, Mario Fusco, Marius Ileana, Martin Kouba, Martin Panzer, Matej Novotny, Matej Vasek, Matthias Andreas Benkard, Matthias Harter, Mattia, Max Rydahl Andersen, Mayank Kunwar, Michał Szynkiewicz, oscarfh, Pavol Loffay, Pedro Igor, Peter Palaga, Petr Nehyba, Phillip Kruger, Robbie Gemmell, Robert Marcano, Roberto Cortez, Rohan Maity, Rostislav Svoboda, Sanne Grinovero, Sebastian Daschner, Sebastien Dionne, Sergey Beryozkin, Stuart Douglas, Stéphane Épardaud, Timothy Power, Tobias Liese, Tobias Stadler, Tomaz Cerar, Vincent Sevel, Vincent Sourin, Vinícius Ferraz Campos Florentino, William Burns and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
