---
layout: post
title: 'Quarkus 1.3.2.Final released - Bugfixes'
date: 2020-04-08
tags: release
synopsis: 1.3.2.Final fixes some regressions with the Hibernate ORM extension and bugs related to the container image extensions.
author: gsmet
---

We just released 1.3.2.Final today with bugfixes and documentation improvements.

This is a safe upgrade for everyone using 1.3.0.Final or 1.3.1.Final. It is a very recommended upgrade if you are using Hibernate ORM.

== What's new?

=== Bugfixes

We fixed a couple of regressions introduced recently in the Hibernate ORM extension.

We are also continuously improving link:/guides/container-image[the container image extensions].

You can get https://github.com/quarkusio/quarkus/releases/tag/1.3.2.Final[the full changelog of 1.3.2.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

