---
layout: post
title: 'Quarkus Insights #1: Tests'
date: 2020-05-08
tags: insights
synopsis: First (real) episode on Quarkus Insights with Georgios on all things Testing.
author: maxandersen
---

Monday we went live with https://www.youtube.com/watch?v=OCPFdpvL1Q0[Quarkus Insights #1: Testing] with Georgios showing and talking about all things Testing. Especially showing the new Mockito integration and examples of TestContainer usage.

video::OCPFdpvL1Q0[youtube,width=640, height=360]

The code he shows are at https://github.com/geoand/quarkus-test-demo and below are a transcript (Thanks Markus!).

== Next Episode

On Tusday May 12th 11:15 CEST / 14:45 IST / 05:15 EST  we will do https://www.youtube.com/watch?v=5UhM_W6zukg[Quarkus Insights episode #2: quarkus:dev & command mode] with https://twitter.com/stuartwdouglas[Stuart Douglas]!

This is at a more European/APAC time friendly slot - anyone that shows up from United states gets a shout out for being up way too early!

We will talk about how to use `quarkus:dev` and the new command mode - knowing Stuart we will also get to digg deep into the internals of Quarkus.

Do add questions to the youtube video already or show up on the live show and ask away - we will cover as much as we can!

To join current live show or see the next one scheduled bookmark this link: https://youtube.com/quarkusio/live
 
== Transcript

Below is a transcription of the episode.

Kudos to Markus Eisele for making this happen!

include::insights_1_transcription.adoc[]