---
layout: post
title: 'Quarkus 1.1.1.Final released - Bugfixes only'
date: 2020-01-07
tags: release
synopsis: 1.1.1.Final fixes several issues mostly in our Kotlin and Gradle support.
author: gsmet
---

We just released 1.1.1.Final to push a series of bugfixes and documentation improvements early.
We are still working hard on preparing our next big version, which will be 1.2, released in late January.

This is a safe upgrade for everyone using 1.1.0.Final.

== What's new?

=== Bugfixes and documentation improvements

We introduced some big changes in our Gradle support for 1.1 and we got some interesting feedback.
1.1.1.Final fixes all the issues reported so far.

We also polished a few things in our Kotlin support.

Apart from that, we fixed minor issues here and there and polished the documentation.

=== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/1.1.1.Final[the full changelog of 1.1.1.Final on GitHub].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[208 contributors].
Many many thanks to each and everyone of them.

In particular for the 1.1.0 release, thanks to Akito Kidani, Alex Soto, Andreas Paschwitz, Andy Damevin, Arne Mejlholm, Bruno Devaux, George Gastaldi, Georgios Andrianakis, Grzegorz Piwowarek, Guillaume Smet, Gunnar Morling, Ian Wormsbecker, Jaikiran Pai, Loïc Mathieu, Manyanda Chitimbo, Mark Little, Matej Novotny, Max Rydahl Andersen, Michael J. Simons, Romain Quinio and Vinícius Ferraz Campos Florentino.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

