---
layout: post
title: 'Quarkus 1.2.1.Final released - Bugfixes only'
date: 2020-02-19
tags: release
synopsis: 1.2.1.Final fixes several issues in Quarkus and the documentation.
author: gsmet
---

Today, we released 1.2.1.Final which is a small iteration on top of 1.2.0.Final with only bugfixes and documentation fixes.

This is a safe upgrade for everyone using 1.2.0.Final.

== What's new?

=== Bugfixes and documentation improvements

The most important issue we fixed is the regression in the MariaDB driver when building native executables.

But we fixed other issues and some inaccuracies in the documentation.
You can get https://github.com/quarkusio/quarkus/releases/tag/1.2.1.Final[the full changelog of 1.2.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

