---
layout: post
title: 'Quarkus Insights on Youtube Live'
date: 2020-04-30 
tags: announcement insights
synopsis: Quarkus Insights is a live streaming channel where we and guests will talk to get insights on how Quarkus works and how it is used.
author: maxandersen
---

Yesterday, Emmanuel Bernard and I kicked off https://www.youtube.com/watch?v=YKm8rVzLhNE[Quarkus Insights #0: Inception]. All based on https://twitter.com/maxandersen/status/1254451547842531329[this tweet] where ~76% was up for us doing "something" in video/podcast'y style.

It is going to be recorded live as part of our existing https://youtube.com/c/quarkusio[QuarkusIO] channel. To be notified when new shows are planned and when they go live https://youtube.com/c/quarkusio[Go Subscribe] and hit the bell for notifications!

In the first episode we introduced the idea and concepts and took questions from the ~35 guests that made it in with short notice!

video::YKm8rVzLhNE[youtube,width=640, height=360]

Thanks to https://twitter.com/myfear[Markus Eisele] we will have transcripts for each episode - end of this blog has a transcript for episode #0.

It was super-fun and looking forward to do it again. 

== Format

Our main format will be focused on a guest talking around a topic/area related to development or usage of Quarkus. We'll also have some dedicated Q&A / StackOverflow episodes.

== Next Episode

On Monday May 4th we will do the first one!

https://youtu.be/OCPFdpvL1Q0[Quarkus Insights episode, #1: Tests] with a guest appearance from Georgios Andrianakis.

We will talk about doing testing with Quarkus and especially cover the new mocking features in Quarkus 1.4.

To join current live show or see the next one scheduled bookmark this link: https://youtube.com/quarkusio/live
 
== Transcript

Below is a transcription of the episode with timestamps giving a link to the approximate location in the video.

Kudos to Markus Eisele for making this happen!

include::insights_0_transcription.adoc[]
