---
layout: post
title: Free Quarkus Sessions at Quarkus Day by Red Hat
date: 2020-08-25
tags: conference user-story event
synopsis: A handy guide to Quarkus sessions at Red Hat's free Quarkus Day virtual event.
author: jfalkner
---

== TUESDAY & WEDNESDAY • SEPTEMBER 9 &10 • 9.45 CEST

https://www.brighttalk.com/summit/4800-quarkus-day-by-red-hat[Quarkus Day by Red Hat^] is a two-day event dedicated to developers and developer teams that want to be part of the future of cloud native development. At the event you will meet engineers and community members from the Quarkus community and learn everything there is to know about Quarkus – the Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM, crafted from best of breed Java libraries and standards. After attending, you are ready to start coding with Quarkus!

=== Day 1

Day 1 is all about Quarkus the technology, and focuses on development topics such as reactive systems, security in Quarkus apps, scalability and performance, native compilation and more. Whether you are interested in developer joy or securing your services, you’ll meet experts from Red Hat and our partner ecosystem telling you about the magic you can make happen with your new Java framework.

Day 1 Highlights include:

* *9.45 CEST* https://www.brighttalk.com/webinar/the-future-of-cloud-native-development-is-called-quarkus/[Opening remarks & Keynote: The future of cloud native development is called Quarkus^]
* *10.30 CEST* https://www.brighttalk.com/webinar/from-monoliths-to-microservices-with-developer-joy-and-performance/[From Monoliths to Microservices with developer joy and performance^]
* *13.00 CEST* https://www.brighttalk.com/webinar/distributed-development-and-native-images-quarkus-why-and-how/[Distributed development and native images: Quarkus, why and how?^]

=== Day 2

Day 2 completes the story with a focus on how Quarkus enables developers and development teams to build and deploy highly optimized applications with Quarkus. How can I optimize my application packaging on my nodes? How can I give my developers their joy back? How can I reduce friction in my software development process. Learn everything about why Quarkus and Kubernetes help you to modernize your applications and infrastructures while taking away a lot of the friction of typical container orchestration systems.

Day 2 Highlights include:

* *10:20 CEST* https://www.brighttalk.com/webinar/what-microservices-and-containers-will-change-and-how-to-adopt/[What Microservices and Containers will change and how to adopt?^]
* *13.00 CEST* https://www.brighttalk.com/webinar/manage-your-challenges-with-red-hat/[Manage your challenges with Red Hat^]

https://www.brighttalk.com/summit/4800-quarkus-day-by-red-hat[Check out the Quarkus Day event page to register to attend^] and learn more about the sessions and speakers at this free event. We hope to see you there!
