---
layout: post
title: 'Quarkus 1.13.6.Final released - Maintenance release'
date: 2021-05-27
tags: release
synopsis: 1.13.6.Final is a maintenance release for our 1.13 release train.
author: gsmet
---

Unfortunately, 1.13.5.Final introduced a regression in the Hibernate Validator extension due to a Jandex issue
(Jandex is our library indexing the classes and annotations).

Thus, we released 1.13.6.Final today to mitigate the issue.

1.13.6.Final is a safe upgrade for everyone using Quarkus 1.13.

Please also check out https://quarkus.io/blog/quarkus-1-13-5-final-released/[the 1.13.5 announcement]

If you are not using 1.13 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13[1.13 migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/1.13.6.Final[the full changelog of 1.13.6.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

