---
layout: post
title: 'Quarkus 2.0.0.CR3 released - Towards Final'
date: 2021-06-04
tags: release
synopsis: We fixed some more issues in this CR. Final is coming at the end of June.
author: gsmet
---

Thanks to your feedback, we fixed some more issues in Quarkus 2.0
and we thought a new CR was necessary.

As usual, it also comes with documentation refinements.

We will build the Final artifacts on June 23rd so keep the feedback coming!

== Migration Guide

We keep the Migration Guide up to date here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0.

== Jandex Upgrade

If you are using the Jandex Maven plugin or the Jandex Gradle plugin in your applications, you need to update them.

Refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#jandex-upgrade[migration guide] for the details.

== Documentation

The documentation for the `main` branch is available link:/version/main/guides/[on the website].

=== Full Changelog

You can get the full changelogs of https://github.com/quarkusio/quarkus/releases/tag/2.0.0.CR3[2.0.0.CR3] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
