---
layout: post
title: 'Quarkus 2.5.4.Final released - Maintenance release'
date: 2021-12-20
tags: release
synopsis: 2.5.4.Final is a maintenance release for our 2.5 release train.
author: gsmet
---

We just released Quarkus 2.5.4.Final, a maintenance release for our 2.5 release train containing bugfixes and documentation improvements.

It is a safe upgrade for anyone already using 2.5.

If you are not using 2.5 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.5[2.5 migration guide].

== Main changes

=== Jackson 2.12.6

We upgraded to Jackson 2.12.6 to fix https://github.com/FasterXML/jackson-databind/issues/3328[a security issue in Jackson Databind].

=== Platform resolution fix

An issue has been fixed regarding how the platforms are resolved in the dev tools.
This issue could cause code.quarkus.io do go out of memory when creating projects with high number of extensions.

If you are running your own instance of https://github.com/quarkusio/code.quarkus.io[code.quarkus.io] internally,
you will want to update to this version to avoid issues.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.5.4.Final[the full changelog of 2.5.4.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

