---
layout: post
title: 'Quarkus 2.0.0.Alpha3 released - GraalVM 21.1, SmallRye GraphQL Client...'
date: 2021-05-20
tags: release
synopsis: We continue to make progress on the road to Quarkus 2.0.
author: gsmet
---

We just released our third Alpha for Quarkus 2.0 which contains several enhancements and new features:

* https://github.com/quarkusio/quarkus/pull/17014[#17014] - Update to GraalVM 21.1
* https://github.com/quarkusio/quarkus/pull/17350[#17350] - SmallRye GraphQL Client extension + 1.2.1 upgrade
* https://github.com/quarkusio/quarkus/pull/16857[#16857] - Add Amazon SSM extension
* https://github.com/quarkusio/quarkus/pull/16963[#16963] - Add `quarkus:test` goal
* https://github.com/quarkusio/quarkus/pull/17232[#17232] - Introduce coroutine support in Reactive Messaging
* https://github.com/quarkusio/quarkus/pull/17056[#17056] - Add support for coroutines to the rest client
* https://github.com/quarkusio/quarkus/pull/16951[#16951] - Add support for hibernate.metadata_builder_contributor

If you have missed our previous announcements:

 * link:/blog/quarkus-2-0-0-alpha1-released/[2.0.0.Alpha1 announcement]
 * link:/blog/quarkus-2-0-0-alpha2-released/[2.0.0.Alpha2 announcement]

== Migration Guide

We will keep the Migration Guide up to date here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0.

== Documentation

The documentation for the `main` branch is available link:/version/main/guides/[on the website].

=== Full Changelog

You can get the full changelogs of https://github.com/quarkusio/quarkus/releases/tag/2.0.0.Alpha3[2.0.0.Alpha3] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
