---
layout: post
title: 'Quarkus 1.13.1.Final released - Bugfixes'
date: 2021-04-07
tags: release
synopsis: 1.13.1.Final fixes issues and comes with documentation improvements.
author: gsmet
---

It has been a week since the release of `1.13.0.Final` so it is time for our traditional `.1` release.

1.13.1.Final is a maintenance release fixing bugs and improving the documentation.

1.13.1.Final is a safe upgrade for everyone using Quarkus 1.13.

If you are not using 1.13 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13[1.13 migration guide].

== What's new?

=== Instrumentation-based live reload disabled by default

We have made several iterations of our instrumentation-based live reload (meaning we don't restart Quarkus but just perform class redefinition when we can) since its first introduction.

It has matured a lot but we decided it was too much of a change compared to our initial promise of "you refresh, everything is fully restarted".
So, in 1.13.1.Final, we disabled it by default.
If your live reloads are taking too long or if you want to keep the application state as much as possible, you can enable it by adding `quarkus.live-reload.instrumentation=true` in your `application.properties`.

=== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/1.13.1.Final[the full changelog of 1.13.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

