---
layout: post
title: 'The New Quarkus 2.x Platform Model and Ecosystem Support in the Dev Tools'
date: 2021-07-01
tags: release
synopsis: 'The Quarkus 2.0.0.Final release introduces the new Quarkus platform model and the dev tools that make it easy to discover and work with the Quarkus extension ecosystem.'
author: aloubyansky
---

= The Quarkus 2.x Platform Model

The Quarkus 1.x platform was based on a single BOM - `io.quarkus:quarkus-universe-bom`, that would be imported by Quarkus applications. The universe BOM would include all the Quarkus
platform extensions plus their dependencies. BOMs are meant to make it easy to align common dependencies on versions that work for all the libraries and frameworks used in an application.
However, badly composed BOMs may actually make it very difficult or practically impossible to achieve that. Generally speaking, the wider the scope of the dependencies a BOM manages,
the higher the risk for its users of running into incompatiblity issues including libraries that aren't managed by the BOM into their applications.

The `io.quarkus:quarkus-universe-bom`, as its artifactId implies, is certainly a large and diverse BOM, including dependencies of Camel, Google Cloud Services, Kogito, OptaPlanner
and other Quarkus platform members. Importing `io.quarkus:quarkus-universe-bom` will enforce ~3600 dependency version constraints on an application. Besides the fact that it's practically
always way more than necessary, it may actually cause a serious compatibility issue that could have been avoided if the Quarkus platform BOM was not trying to manage the "universe".

E.g. including a library that depends on a different version of the `commons-beanutils:commons-beanutils` than Camel Quarkus into an application that actually does not include any
Camel Quarkus extension may become problematic, because the `io.quarkus:quarkus-universe-bom` will enforce the version required by Camel Quarkus.

The Quarkus 2.0.0.Final release, in addition to the monolithic `io.quarkus:quarkus-universe-bom`, also includes the platform member-specific BOMs, e.g.

* `io.quarkus.platform:quarkus-bom:2.0.0.Final` - an equivalent of the `io.quarkus:quarkus-bom`;
* `io.quarkus.platform:quarkus-camel-bom:2.0.0.Final` - manages only the Camel Quarkus-related extensions and their required dependencies;
* `io.quarkus.platform:quarkus-kogito-bom:2.0.0.Final` - manages only the Kogito Quarkus-related extensions and their required dependencies;
* etc

Having member-specific BOMs, applications now can import only the BOMs that are relevant to them and avoid enforcing dependency constraints from the rest of the "universe".

NOTE: Given that every member-specific BOM is actually a fragment of the `io.quarkus:quarkus-universe-bom`, member BOMs can be imported in any order w/o creating a conflict.

== Dev Tools Support

The dev tools, such as the Quarkus CLI, Maven or Gradle plugins, can be used to create and manage a Quarkus application project using the new platform model.

NOTE: The `io.quarkus:quarkus-universe-bom` is still the default BOM in Quarkus 2.0.0.Final but in one of the subsequent Quarkus 2.x releases it will be deprecated
in favor of the member-specific BOMs.

The easiest way to play with it would be using the new https://quarkus.io/guides/cli-tooling[Quarkus CLI], which can be installed using e.g.

```shell
curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
```

Once installed you can create a project by executing

```shell
quarkus create app --registry-client
```

NOTE: Without the `--registry-client` argument the created project will be importing the default `io.quarkus:quarkus-universe-bom:2.0.0.Final`.

The generated `pom.xml` will be importing the following BOM:
```xml
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.0.0.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

which is an equivalent of the `io.quarkus:quarkus-bom` that does not include any of the other platform members, such as Camel, Kogito, OptaPlanner, etc.

However, if we did want to create a new project including a Kogito extension, it could be done like this:

```shell
quarkus create kogito-quarkus-rules --registry-client
```

And the generated project would now import two BOMs (i.e. two fragments of the `io.quarkus:quarkus-universe-bom` that are relevant to the project):

```xml
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.0.0.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-kogito-bom</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-quarkus-rules</artifactId>
    </dependency>
```

= Wider Quarkus Ecosystem Support in the Dev Tools

https://quarkus.io/guides/platform[Quarkus platform] does not represent the whole Quarkus extension ecosystem, aka Quarkiverse, but rather a set of extensions that target
the primary use-cases of Quarkus as a development stack. Which means that there are still plenty of Quarkus extensions that aren't present in a Quarkus platform (BOM),
e.g. most of the extensions hosted on the https://github.com/quarkiverse[Quarkiverse Hub]. These non-platform extensions could still be added
to Quarkus applications as usual application dependencies. The Quarkus 2.0.0.Final dev tools make it very easy, e.g.

```shell
quarkus create prettytime --registry-client
```

will create a new Quarkus project with a non-platform https://github.com/quarkiverse/quarkus-prettytime[Quarkus Pretty Time extension].

```xml
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.0.0.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkiverse.prettytime</groupId>
      <artifactId>quarkus-prettytime</artifactId>
      <version>0.1.0</version>
    </dependency>
```

== Registry Client Support in the Maven and Gradle Plugins

The Quarkus Maven and Gradle plugins could still be used to manage Quarkus projects. The equivalent of the CLI's `--registry-client` argument using the plugins would be
`-DquarkusRegistryClient` or environment variable `QUARKUS_REGISTRY_CLIENT` set to `true`, e.g.

```shell
mvn io.quarkus:quarkus-maven-plugin:2.0.0.Final:create \
    -Dextensions=kogito-quarkus-rules,prettytime \
    -DprojectGroupId=org.acme -DprojectArtifactId=quarkus-app -DprojectVersion=1.0 \
    -DquarkusRegistryClient
```
