---
layout: post
title: 'Quarkus 1.13.7.Final released - Maintenance release'
date: 2021-06-09
tags: release
synopsis: 1.13.7.Final is a maintenance release for our 1.13 release train.
author: gsmet
---

And here comes 1.13.7.Final, our (most probably!) last round of bugfixes for the 1.13 release.

If you are not using 1.13 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13[1.13 migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/1.13.7.Final[the full changelog of 1.13.7.Final on GitHub].

== 2.0 coming soon

We will soon start a new chapter with Quarkus 2.0.0.Final.
It should be released by the end of this month.

You can find more information in https://groups.google.com/g/quarkus-dev/c/18Ocz1wtKjo/m/tuRVB97aAAAJ[the announcement].

Please test your applications with our latest 2.0.0.CR3 and report back!

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

