---
layout: post
title: 'Quarkus 2.1.0.Final released - Dev Service for Keycloak, Reactive SQL Server extension, Kotlin 1.5'
date: 2021-07-29
tags: release
synopsis: 'On top of the shoulders of 2.0, 2.1 includes a lot of refinements and improvements all over the place.'
author: gsmet
---

Today, we release Quarkus 2.1.0.Final which includes a lot of refinements and improvements and a couple of new features:

* Dev Service for Keycloak
* Reactive Microsoft SQL Server extension
* Upgrade to Kotlin 1.5

== Migration Guide

To migrate from 2.0, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.1[our migration guide].

== What's new?

=== Dev Service for Keycloak

Dev Services start the required containers automatically when you are developing or testing your application.

A lot of Quarkus extensions are already covered and, in 2.1, we added link:/guides/security-openid-connect-dev-services[a Dev Service for Keycloak].

=== Reactive Microsoft SQL Server extension

2.1 adds a reactive driver extension for Microsoft SQL Server - `quarkus-reactive-mssql-client`.

=== Kotlin 1.5

We upgraded our Kotlin extension and tooling to 1.5, namely 1.5.21.

=== Full Changelog

You can get the full changelogs of https://github.com/quarkusio/quarkus/releases/tag/2.1.0.CR1[2.1.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/2.1.0.Final[2.1.0.Final] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[511 contributors].
Many many thanks to each and everyone of them.

In particular for the 2.1 release, thanks to Alexey Loubyansky, Amos Feng, André Gonçalves, Andy Damevin, Andy Fedotov, antoniodvr, axblu, Bernhard Lutzmann, Bill Burke, Bobby Alex Philip, Bryan Varner, chetankokil, Chris Laprun, Christian Morin, Christopher, Clement Escoffier, Cyrille Le Clerc, Dan Heidinga, Davide, Dirk Van Haerenborgh, Dominika Vagnerova, Eric Deandrea, Erin Schnabel, essobedo, Falko Modler, Foivos Zakkak, GavinRay97, George Gastaldi, Georgios Andrianakis, Guillaume Le Floch, Guillaume Smet, Gustavo Luszczynski, Gytis Trikleris, Heiko W. Rupp, Ilya Leoshkevich, Ioannis Canellos, Ivan Greguric Ortolan, James R. Perkins, Jan Martiška, Janez Pintar, JiriOndrusek, Jose, Joshua Roys, Julien Ponge, Justin Lee, Katia Aresti, Kay Ulbrich, Ken Finnigan, Kjetil Nygård, Knut Wannheden, Kyrylo Shpak, Ladislav Thon, Leonardo, Loïc Mathieu, luneo7, Maciej Swiderski, Maciej Walkowiak, manusa, Manyanda Chitimbo, Marc Nuri, Marcel Hanser, Marco Bungart, Martin Kouba, Martin Panzer, Matej Novotny, Michał Szynkiewicz, Mingyuan Wu, Nicolas Filotto, Ozan Gunalp, Patryk Najda, Paul Carter-Brown, Paul Robinson, Phillip Krüger, Renato Pereira Back, Roberto Cortez, Ron Sigal, Rostislav Svoboda, Sanne Grinovero, Sebastien Dionne, Sergey Beryozkin, Stephane Epardaud, Stuart Douglas, Sven Kattelans, Thomas Segismont, Tomas Hofman, xstefank and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
