---
layout: post
title: 'Quarkus 2.14.0.Final released - Jandex 3, new Redis commands, caching annotations for Infinispan'
date: 2022-11-09
tags: release
synopsis: 'We released Quarkus 2.14.0.Final with a lot of both internal and user facing improvements.'
author: gsmet
---

Today, we released Quarkus 2.14.0.Final with a lot of new features and small improvements all over the place:

* Upgrade to Jandex 3
* Include `quarkus-opentelemetry-exporter-otlp` into `quarkus-opentelemetry`
* Additional Redis commands
* RESTEasy Reactive: multipart form improvements
* Support for caching annotations for Infinispan
* Improved Kotlin support for Hibernate Reactive with Panache
* Support embedding the H2 DB engine in native executables
* Bump GraalVM minimum version to 22.2.0

As usual, the documentation also got some love during this release cycle.

== Migration Guide

To migrate from 2.13, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.14[our migration guide].

== What's new?

=== Jandex 3

Jandex, our class and annotation indexer, is at the core of Quarkus.
With Quarkus 2.14, Jandex has been upgraded to the brand new Jandex 3.

The project has moved under the SmallRye umbrella and the `groupId` has been changed to `io.smallrye`.
The package name was kept identical.

It should be transparent for you, except if you have an explicit dependency to Jandex.
In this case, while a relocation has been put in place, it is recommended to adjust the `groupId` to `io.smallrye`.

Jandex 3 comes with a lot of improvements that will simplify the development of Quarkus extensions.

=== OpenTelemetry

`opentelemetry-exporter-otlp` is now the default exporter for OpenTelemetry and has been included into the `quarkus-opentelemetry` extension.

`opentelemetry-exporter-jaeger` has been moved to the Quarkiverse Hub: https://github.com/quarkiverse/quarkus-opentelemetry-exporter.

Relocations have been put in place to simplify migrations.

=== Redis

The work on implementing Redis commands in our Redis extension API continues.
In Quarkus 2.14, support for JSON commands, graph commands and probabilistic data structures has been added.

=== Infinispan

Support for caching annotations has been added to the Infinispan Client extension.
You can find more about it in the link:/guides/infinispan-client#infinispan-annotations-api[dedicated section of the guide].

=== H2

Until now, it was only possible to include the H2 client in native executables.
Starting with Quarkus 2.14, you can also embed the H2 server in native executables.

== GraalVM/Mandrel upgrade coming soon

Quarkus 2.14.0.Final is still targeting GraalVM/Mandrel 22.2 but an upgrade to 22.3 is planned for Quarkus 2.14.1.Final, which will be released next week.

In Quarkus 2.14, the minimum GraalVM/Mandrel version is now 22.2.0.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/2.14.0.CR1[2.14.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/2.14.0.Final[2.14.0.Final] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[719 contributors].
Many many thanks to each and everyone of them.

In particular for the 2.14 release, thanks to Aaron Rebak, Adler Fleurant, Alex Martel, Alexey Loubyansky, anavarr, Andreas Eberle, Andrii Maliuta, Andy Damevin, Auri Munoz, Bartosz Markowski, Bernardo Coferre, Bill Burke, brunobat, Cheng Fang, Clement Escoffier, cui fliter, damienb-opt, David Frickert, Davide D'Alto, Emanuel Alves, Erin Schnabel, Fedor Dudinskiy, Foivos Zakkak, Fouad Almalki, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, glefloch, Guillaume Smet, Gwenneg Lepage, Harald Albers, Heiko W. Rupp, Helber Belmiro, hmanwani-rh, Holly Cummins, Igor Regis, Ioannis Canellos, Jan Martiska, Joan Ruget, Jose Carvajal, Justin Lee, Katia Aresti, kdnakt, Knut Wannheden, Ladislav Thon, Liuigi, Loïc Mathieu, Lucy Linder, Manyanda Chitimbo, Marc Nuri, Marco Bungart, Martin Kouba, Marvin B. Lillehaug, Matej Novotny, Matej Vasek, Max Gabrielsson, Max Rydahl Andersen, Michael Edgar, Michal Karm Babacek, Michal Vavřík, Michelle Purcell, mtrefcon, Nathan Erwin, Ozan Gunalp, Phillip Krüger, Rakhmad Azhari, Robbie Gemmell, Roberto Cortez, Rostislav Svoboda, Réda Housni Alaoui, Sanne Grinovero, Sergey Beryozkin, Severin Gehwolf, shjones, Stephane Epardaud, Stuart Douglas, Vincent Sevel, Vincent van Dam, xstefank, yesunch9, Yoann Rodière, Yubao Liu, zedbeit, Zheng Feng.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
