---
layout: post
title: 'Quarkus 2.10.3.Final released - Fixes CVE-2022-2466'
date: 2022-07-19
tags: release
synopsis: 2.10.3.Final fixes CVE-2022-2466 and is a mandatory upgrade for anyone exposing GraphQL services with Quarkus 2.10.x.
author: gsmet
---

2.10.0.CR1 introduced a major security issue known as CVE-2022-2466 in the SmallRye GraphQL server extension and all the 2.10.x releases are affected (together with 2.11.0.CR1).
2.10.3.Final fixes it and the fix will also be included in the upcoming 2.11.0.Final.
You are only affected by this issue if you are exposing GraphQL services.

The context of the requests was not properly terminated and, for a given thread, all further requests would use the context of the first request the thread treated.
The context includes authentication if your GraphQL services require authentication.

This is an extremely serious issue so we urge anyone who has already upgraded to 2.10.x and is exposing GraphQL services to upgrade to 2.10.3.Final.

Note that 2.9 and earlier are not affected by the issue.

This version also contains some minor additional fixes.

If you are not using 2.10 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.10[2.10 migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.10.3.Final[the full changelog of 2.10.3.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

