---
layout: post
title: 'Quarkus 2.11.2.Final released - CVE-2022-2466 is still ongoing'
date: 2022-08-08
tags: release
synopsis: 'Quarkus 2.11.2.Final fixes several issues but still does not completely fix CVE-2022-2466.'
author: gsmet
---

We thought we got to the bottom of CVE-2022-2466, a security issue we have with GraphQL services since 2.10 was released, but this one keeps on giving.

This issue is only of importance to you if you are exposing GraphQL services using the `quarkus-smallrye-graphql` extension.
Consuming GraphQL services is fine.

If you are in this case, we recommend to stay on the latest 2.9 for the time being, which is 2.9.2.Final.

If you are not using `quarkus-smallrye-graphql`, you are safe to go with the latest and greatest Quarkus that is 2.11.2.Final.

We are working hard to fully circumvent CVE-2022-2466 and will hopefully release a 2.11.3.Final soon that fully fixes the issue.

== Migration Guide

If you are not already using 2.11, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.11[our migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.11.2.Final[the full changelog of 2.11.2.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
