---
layout: post
title: 'Quarkus 2.15.1.Final released - Maintenance release'
date: 2022-12-21
tags: release
synopsis: 'Quarkus 2.15.1.Final is the first maintenance release of our 2.15 release train.'
author: gsmet
---

It is the end of the year (again) and here comes our last release of the year, 2.15.1.Final.
We had 9 minor releases this year (starting with 2.7 in February) and so many micros.
We made tremendous progress on Quarkus itself and the activity in the ecosystem of extensions has been extremely prolific.

This version contains bugfixes and documentation improvements on top of our 2.15.0.Final release.
It is a recommended upgrade for anyone already using 2.15.

If you are not already using 2.15, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.15[our migration guide].

Happy holidays and see you next year for more Quarkus goodness!

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.15.1.Final[the full changelog of 2.15.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
