---
layout: post
title: 'Quarkus 2.7.1.Final released - Maintenance release'
date: 2022-02-08
tags: release
synopsis: 2.7.1.Final is the first maintenance release for our 2.7 release train.
author: gsmet
---

Today, we released Quarkus 2.7.1.Final, our first maintenance release for our 2.7 release train.
It contains bugfixes and documentation improvements, but also a couple of new features, filling a few gaps.

It is a safe upgrade for anyone already using 2.7.

If you are not using 2.7 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7[2.7 migration guide].

== What's new

=== Kogito extensions are back

2.7.1.Final reintroduces the Kogito extensions that were disabled for 2.7.0.Final due to an incompatibility.
So if you are using Kogito, you can now upgrade your applications to 2.7.

=== gRPC

Our gRPC extension only generated code for the application classes.
Starting with 2.7.1.Final, it also generates code from the dependencies.

=== OIDC token propagation

We introduced a reactive counterpart to the OIDC token propagation extension,
that you can use with RESTEasy Reactive.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.7.1.Final[the full changelog of 2.7.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

