---
layout: post
title: 'Quarkus 2.7.1.Final released - Maintenance release'
date: 2022-02-08
tags: release
synopsis: 2.7.1.Final is the first maintenance release for our 2.7 release train.
author: gsmet
---

Today, we released Quarkus 2.7.1.Final, our first maintenance release for our 2.7 release train.
It contains bugfixes and documentation improvements.

It also reintroduces the Kogito extensions.
So if you are using Kogito, you can now upgrade your applications to 2.7.

It is a safe upgrade for anyone already using 2.7.

If you are not using 2.7 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7[2.7 migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.7.1.Final[the full changelog of 2.7.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

