---
layout: post
title: 'Quarkus 2.6.2.Final released - Maintenance release'
date: 2022-01-10
tags: release
synopsis: 2.6.2.Final is a maintenance release for our 2.6 release train. It brings back Kogito.
author: gsmet
---

We just released Quarkus 2.6.2.Final, our second maintenance release for our 2.6 release train.

It is a safe upgrade for anyone already using 2.6 and contains small bugfixes, tweaks and documentation improvements.
It also brings back a working Kogito stack.
Due to some infrastructure problems, the Kogito team wasn't able to deliver a Kogito version working with Quarkus 2.6 before the holiday break
but that's ancient history.

If you are not using 2.6 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6[2.6 migration guide].

== Kogito

Working Kogito and OptaPlanner are back in Quarkus 2.6.2.Final.

There is one change though: if you aren't doing so already,
you will need to explicitly add the `quarkus-resteasy-jackson` extension to your Kogito and OptaPlanner applications.

We are working on supporting both RESTEasy Classic and RESTEasy Reactive with Kogito and OptaPlanner,
this is the first step in this direction and this task will come to completion with Quarkus 2.7.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.6.2.Final[the full changelog of 2.6.2.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

