---
layout: post
title: 'Quarkus 3.3.1 released - Maintenance release'
date: 2023-08-29
tags: release
synopsis: 'We released Quarkus 3.3.1, our first maintenance release for our 3.3 release train.'
author: gsmet
---

We released Quarkus 3.3.1, our first maintenance release for our 3.3 release train.

It includes a bunch of bugfixes, together with documentation improvements.

We are aware of a https://github.com/quarkusio/quarkus/issues/35406[startup performance/memory regression introduced in 3.3] and are working hard on fixing it.
This issue *is* not solved in 3.3.1 but should be solved in the upcoming 3.3.2 that will be released next week.

== Update

To update to Quarkus 3.3.1, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

To migrate from 3.2, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[our migration guide].

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1] and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2] migration guides.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.3.1[the full changelog of 3.3.1 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
