---
layout: post
title: 'Quarkus 3.0.0.CR2 released'
date: 2023-04-05
tags: release
synopsis: 'Today, we released Quarkus 3.0.0.CR2, our last step before building the 3.0.0.Final bits.'
author: gsmet
---

Today, we released Quarkus 3.0.0.CR2, our last step before building the 3.0.0.Final bits.

Please try it with your applications, the update is easy in a lot of cases,
and report any problem to us by https://github.com/quarkusio/quarkus/issues[creating a GitHub issue].

To upgrade your application to Quarkus 3.0, see <<upgrading,the instructions below>>.

Among a lot of bugfixes and small enhancements, the highlights of this release are:

- Dev UI 2 is the default Dev UI
- Gradle project update

== What's new

=== Dev UI 2 by default

Dev UI 2 is our brand new shiny Dev UI.
It is now the default you obtain when going to `/q/dev`
(but it's actually hosted at `/q/dev-ui`).

The old Dev UI is still accessible at `/q/dev-v1`
and will be retired once we have ported all its features to Dev UI 2.

Yes, Dev UI 2 is not complete yet but it's already awesome so go test it and https://github.com/quarkusio/quarkus/issues[report back].

=== Gradle project update

The `quarkus update` command now supports the update of Gradle projects to Quarkus 3.

Have a Gradle project around? Give it a try and tell us https://github.com/quarkusio/quarkus/issues[how it works].

== Trying out Quarkus 3

For now the easiest way to get started is using https://code.quarkus.io/?S=io.quarkus.platform%3A3.0[code.quarkus.io] or use the Quarkus CLI:

[source,bash]
----
quarkus create app --stream=3.0
----

Mind you that at this stage, while all the core extensions are available, only parts of the Quarkus platform is present.
Not all extensions have yet migrated to Jakarta packages.

[[upgrading]]
== Upgrading to Quarkus 3

=== Migration guide

As usual, we wrote a https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0[migration guide].
As expected for a new major, it is more dense than for our usual minors.

[TIP]
====
The first step in a migration to Quarkus 3 is to run the migration script presented below.

It doesn't take care of everything but it should take care of most of the heavy-lifting.
====

If you are using Hibernate ORM or Hibernate Reactive,
please make sure you have a look to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration[dedicated migration guide].

[[automated-migration]]
=== Automated migration

For existing applications where all extensions are available, we have an OpenRewrite recipe that you can try.

If you are the Quarkus CLI (which we recommend),
update your Quarkus CLI to 3.0.0.CR2 and run the following command:

[source,bash]
----
quarkus update --stream=3.0
----

This command will update your Maven and Gradle projects to the latest Quarkus 3.0.

If you are not using the CLI, you can update your Maven projects with a Maven command directly:

[source,bash]
----
./mvnw io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR2:update -N -Dstream=3.0
----

If the `update` command is not working for you, please https://github.com/quarkusio/quarkus/issues[open a bug report].

And if you can't wait for the fix, you can try the following JBang script.

If you have JBang installed:

[source,bash]
----
jbang --fresh upgrade-to-quarkus3@quarkusio
----

If not, for Linux and macOS:

[source,bash]
----
curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio
----

and for Windows:

[source,bash]
----
iex "& { $(iwr https://ps.jbang.dev) } --fresh upgrade-to-quarkus3@quarkusio"
----

Once this has been run your project should have its dependencies, source code and documentation updated to use Quarkus 3.

If it does not work for you, it could be we missed something or you are using extensions not yet supporting Quarkus 3.

https://github.com/quarkusio/quarkus/issues[Let us know] in either case so we can together improve the migration script.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
