---
layout: post
title: 'Quarkus 3.2.9.Final released - Maintenance LTS release'
date: 2023-11-08
tags: release
synopsis: 'Quarkus 3.2.9.Final is the ninth maintenance release of the 3.2 LTS release train. It fixes a few critical bug fixes and documentation updates.'
author: alexeyloubyansky
---

Quarkus 3.2.9.Final, the ninth maintenance release of the 3.2 LTS release train has been released.

This release fixes the following regressions reported by the community:

- https://github.com/quarkusio/quarkus/issues/36992[Gradle plugin: quarkus.container-image.push=true not working in 3.2.8]
- https://github.com/quarkusio/quarkus/issues/37045[Regression with ForwardedParser setting an empty host header]

And the following critical bug fixes:

- https://github.com/quarkusio/quarkus/pull/37077[Handle duplicated context in the CacheResultInterceptor]
- https://github.com/quarkusio/quarkus/issues/20092[GraphQL authenticated subscription]

It should be a safe upgrade for anyone already using a 3.2 release.

If you are not already using a 3.2 release, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[our migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.2.9.Final[the full changelog of 3.2.9.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
