---
layout: post
title: 'Quarkus 2.16.0.Final released - Redis time series and preloading, support for XDS in gRPC'
date: 2023-01-25
tags: release
synopsis: 'We released Quarkus 2.16.0.Final with improvements to the Redis and gRPC extensions, among other things.'
author: gsmet
---

Today we released Quarkus 2.16.0.Final with several improvements, bugfixes and documentation refinements.

Major changes are:

- Support for time series operations and preloading data in the Redis extension
- Support for custom exception handling and XDS in the gRPC extension
- More flexibility for the Cache extension configuration
- Several security-related improvements focused on improving the developer experience

== Migration Guide

To migrate from 2.15, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16[our migration guide].

== What's new?

=== Redis

We continue to extend the set of operations supported by the Redis extension, this time with time series operations.

Similarly to what exists with Hibernate ORM and the `import.sql` file,
you can import data to your Redis instance on startup using an `import.redis` file.
More information about this feature is available in the link:/guides/redis-reference#preload-data-into-redis[Redis reference guide].

=== gRPC

The gRPC extension now offers custom exception handling and support for XDS.

=== Cache

Most of the Cache extension configuration has been made runtime,
allowing you to define the cache configuration at runtime.

=== Security

Security-related annotations such as `@TestSecurity` or `@OidcSecurity` can be defined on meta-annotations:
you can define a particular security configuration in a meta-annotation and apply it on several methods.

Configuration properties are now expanded in `@RolesAllowed` annotations' value.

The `OidcClientFilter` has been improved to be able to select named OIDC clients.

=== Improvements to @IfBuildProfile and @UnlessBuildProfile

Support for `allOf` and `anyOf` has been added to `@IfBuildProfile` and `@UnlessBuildProfile`,
giving you more flexibility.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/2.16.0.CR1[2.16.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/2.16.0.Final[2.16.0.Final] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[746 contributors].
Many many thanks to each and everyone of them.

In particular for the 2.16 release, thanks to Ales Justin, Alexandre Dutra, Alexei Bratuhin, Alexey Loubyansky, Andy Damevin, Àngel Ollé Blázquez, Antonio Costa, Antonio Goncalves, Antonio Jacob Costa, arik-dig, Ashish Ranjan, benstone, Bill Burke, Brad Hards, Bruno Leonardo Gonçalves, brunobat, Chexpir, Chris Laprun, Christian von Atzigen, Clement Escoffier, Damon Sutherland, David Arnold, David M. Lloyd, Eric Deandrea, Erin Schnabel, Falko Modler, Fikru  Mengesha, Foivos Zakkak, franz1981, George Gastaldi, Georgios Andrianakis, Guillaume Le Floch, Guillaume Smet, Gwenneg Lepage, Holly Cummins, imperatorx, Ioannis Canellos, Jan Martiska, Jose Carvajal, Josef Andersson, jtama, Julien Ponge, Katia Aresti, Kevin Dubois, Ladislav Thon, Loïc Mathieu, Manyanda Chitimbo, Marc Nuri, Marcel Lohmann, Marco Bungart, Marco Schaub, Martin Kouba, Matej Novotny, Max Rydahl Andersen, Michael Edgar, Michal Vavřík, Michelle Purcell, Mihai.Poenaru, oliv37, Orbifoldt, Ozan Gunalp, pablo gonzalez granados, Pedro Igor, Roberto Cortez, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Severin Gehwolf, Stuart Douglas, sturdy5, Stéphane Épardaud, Vaclav Svejcar, Yoann Rodière, Yubao Liu, and zedbeit.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
