---
layout: post
title: 'Release Plans for Quarkus 3.7, 3.8 and 3.9'
date: 2023-12-19
tags: release
synopsis: 'As some of you asked what were our plans regarding the next LTS, this blog post presents our plans for Quarkus 3.7, 3.8 and 3.9.'
author: gsmet
---

Quarkus 3.2 was the first LTS (Long Term Support) release of Quarkus,
and we learned a lot from it.

Choosing which version will be an LTS version is crucial,
as people expect predictability and stability from the LTS versions.

Thus why we came up with a plan for our next minor releases,
including the next LTS version.

[IMPORTANT]
====
**tl;dr**

Quarkus 3.8 will be our next LTS release.
It will be the direct continuation of the `3.7` branch.

If you contribute to Quarkus or the Quarkus Platform and need a feature in the next Quarkus LTS,
make sure it has been merged in the https://github.com/quarkusio/quarkus[Quarkus repository] before January 16th included
(the day before the `3.7.0.CR1` release).
====

== Quarkus 3.7

Quarkus 3.7 will be released on January 31st.
It will contain new features, as usual for our minor releases.

As previously announced, the minimum Java version for Quarkus 3.7 will be Java 17.

The CR1 is planned for January 17th so all the new features need to be merged by then.

See our https://github.com/quarkusio/quarkus/wiki/Release-Planning[release schedule] for all the details.

There will be a slight change though: from January 17th and the build of `3.7.0.CR1`, our `main` branch will target 3.9 development
(yes, you read it correctly, it will target 3.9).

== Quarkus 3.8

You might ask "where has Quarkus 3.8 gone?".
Thanks for asking!

Quarkus 3.8 will be our next LTS version.
It will be released at the end of February
(our current plan is to release it on February 28th, but things might be refined as we approach the release date).

This release will be the continuation of the 3.7 cycle and will be started from the `3.7` branch.
The focus will be on hardening 3.7 and fixing bugs.
It won't contain any new features.
It might contain some additional component upgrades to fix CVEs or important bugs.

**Consequently, and this is important:
if you contribute to Quarkus or the Quarkus Platform and need a feature in the next Quarkus LTS,
make sure it has been merged in the https://github.com/quarkusio/quarkus[Quarkus repository] before January 16th included
(the day before the `3.7.0.CR1` release).**

== Quarkus 3.9

Quarkus 3.9 will be released at the end of March.

It will be packed with new features as it will contain 2 months of work,
whereas our usual minors contain 1 month of work.

== Questions?

If you have any questions about this plan, feel free to ask in the comments of this blog post or on https://github.com/quarkusio/quarkus/discussions/categories/community[GitHub Discussions].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
