---
layout: post
title: 'Quarkus 3.2.2.Final released - Maintenance release'
date: 2023-07-24
tags: release
synopsis: 'Quarkus 3.2.2.Final is the second maintenance release of our 3.2 release train.'
author: gsmet
---

Today, we released Quarkus 3.2.2.Final, the second maintenance release of our 3.2 release train.

We released 3.2.1.Final a few days ago but two annoying regressions were spotted before we announced it so we decided to not announce it and release a 3.2.2.Final right away.

These two releases contains mostly bugfixes and documentation improvements.

It should be a safe upgrade for anyone already using 3.2,
but if you are using the management network interfance and OpenAPI/Swagger UI, please have look below.

If you are not already using 3.2, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[Quarkus 3.2 migration guide].

And if you are not already using 3.0, please refer to https://quarkus.io/blog/quarkus-3-0-final-released/[the Quarkus 3.0 announcement] and in particular the section about the https://quarkus.io/blog/quarkus-3-0-final-released/#upgrading[upgrade path to 3.0] together with the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1 migration guide] and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[Quarkus 3.2 migration guide].

== OpenAPI, Swagger UI, and the management network interface

We recently introduced the management network interface which allows to serve management endpoints (typically the health endpoint) on a different network interface.

Until now, Open API and Swagger UI were not served on the management network interface when enabled.
It was an oversight and we decided to fix it for 3.2.1.Final,
even if we don't usually introduce this type of behavioral change in micro releases.

From 3.2.1.Final, when the management network interface is enabled,
Open API and Swagger UI endpoints will be served from the management network interface by default.

You can disable this behavior by setting the `quarkus.smallrye-openapi.management.enabled=false` configuration property to `false`.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.2.1.Final[the full changelog of 3.2.1.Final] and https://github.com/quarkusio/quarkus/releases/tag/3.2.2.Final[the full changelog of 3.2.2.Final] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
