---
layout: post
title: 'Quarkus 2.16.8.Final released - Maintenance release'
date: 2023-07-05
tags: release
synopsis: 'Quarkus 2.16.8.Final is the eighth maintenance release of our 2.16 release train.'
author: gsmet
---

As mentioned in previous blog posts, we encourage all our users to upgrade to Quarkus 3.
However we understand the migration can require some time so we will continue to maintain 2.16.x for a while.
Today, we released Quarkus 2.16.8.Final, the eighth maintenance release of our 2.16 release train.

As usual, it contains bugfixes and documentation improvements,
most notably the upgrade to Netty 4.1.94.Final, which fixes a CVE.

It should be a safe upgrade for anyone already using 2.16.

If you are not already using 2.16, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16[our migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.16.8.Final[the full changelog of 2.16.8.Final on GitHub] (minus what was already backported to 2.13.x).

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
