---
layout: post
title: 'Quarkus 3.0 released'
date: 2023-04-26
tags: release
synopsis: 'It is our great pleasure to announce our new major release of Quarkus: Quarkus 3.0.'
author: gsmet
---

Quarkus 3.0 is the result of a lot of work and dedication from the community. Quarkus continues to be an Open Source stack to write Java applications offering unparalleled startup time, memory footprint and developer experience. 

The development of Quarkus 3 started last year on March 18 2022 with the crazy idea
that we could rewrite the whole tree to migrate to the new `jakarta.*` packages
while continuing the development of Quarkus 2.

Quarkus 3 is now based on Jakarta EE 10 and, as you can expect,
it is not the only change, this version comes packed with new features and enhancements
that we implemented during this period.

This announcement contains a lot of information about the new features and how to upgrade
so we recommend to read it fully before upgrading to Quarkus 3.

== What's new?

=== Java 11 deprecated

Quarkus 3.0 deprecates Java 11 support. Java 11 is now considered as a legacy version and will be removed in a future Quarkus version. We recommend that you upgrade to Java 17.

=== Jakarta EE 10

Quarkus 2 was based on Jakarta EE 8, Quarkus 3 is based on Jakarta EE 10.

The most visible change is that the `javax.*` packages from Jakarta EE has been moved to `jakarta.*`. This change requires changing any source code and dependency and its transitive dependencies that rely on the `javax.*` packages.

See the Upgrade Guide section for more info on how `quarkus update` helps you migrate.

The change to target Jakarta EE 10 brings two major improvements:

- The broader Java ecosystem are moving to Jakarta dependencies; allowing for easier sharing and compatible implementations.
- CDI introduces notion of CDI Lite and Build Compatible Extensions (BCE) which enables to make standard extensions that are compatible across CDI implementations and also reaps the benefits of Quarkus build time optimizations.

[NOTE]
====
Only the `javax.*` packages from Jakarta EE have changed.
The ones from the JDK are still under `javax.*`.
====

=== Eclipse MicroProfile 6

TODO

=== Hibernate ORM 6

This is one of the biggest changes in Quarkus 3: we upgraded to Hibernate ORM 6, version 6.2 to be more precise.

Hibernate ORM 6 is a major new version of Hibernate ORM and it comes with a lot of changes,
some of them being breaking changes.

To learn more about the changes in Hibernate ORM 6, particular from a Quarkus user perspective see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration[Hibernate ORM 5 to migration].

The Hibernate release blogs has a lot of information about the changes/improvements in Hibernate ORM 6:

- https://in.relation.to/2022/03/31/orm-60-final/[Hibernate ORM 6.0]
- https://in.relation.to/2022/06/14/orm-61-final/[Hibernate ORM 6.1]
- https://in.relation.to/2023/03/30/orm-62-final/[Hibernate ORM 6.2]

Upgrading to Hibernate ORM 6 will require some efforts and testing, make sure you have a look at the <<upgrading>> section below.

Some improvements have also been made to the Quarkus Hibernate extension itself such as:

- The support of `StatementInspector` as `@PersistenceUnitExtension` managed bean
- The ability to inject a https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#_statelesssession[`StatelessSession`] via CDI

=== Hibernate Reactive 2

Hibernate Reactive has been upgraded to version 2 to be compatible with Hibernate ORM 6.

It is still in Beta for now but should be promoted to Final in the coming months.

=== New Dev UI

Quarkus 2 introduced the Dev UI which provides a web ui to use during development.
Extensions could provide their own Dev UI pages to provide additional functionality.

Quarkus 3 now has a new Dev UI which is more extensible and easier to use.
It also has a new and much improved look and feel.

The new Dev UI is the default but,
given all the extensions have not yet migrated to the new one,
you can still access the old one at `/q/dev-v1` but it will be dropped in a future version.

We have a https://www.youtube.com/watch?v=sz5ihmA4gaE&list=PLsM3ZE5tGAVbyncLm7ue2V25cwFck7ew9[playlist] on Quarkus YouTube channel that shows off the new Dev UI, explains the new features and how to use and extend it.

=== Mutiny 2 and Java Flow

Quarkus was upgraded to https://smallrye.io/smallrye-mutiny/2.0.0/reference/migrating-to-mutiny-2/[Mutiny 2]
and now uses the Java Flow API instead of Reactive Streams.

=== Development Tools

Developer experience is a key aspect of Quarkus and we are constantly improving it.

==== CLI plugins

The Quarkus CLI is now extensible with plugins. See details in the https://quarkus.io/version/main/guides/cli-tooling#extending-the-cli[CLI guide].

Expect a lot of new features in the Quarkus CLI in the form of plugins in the near future.

==== Upgrade tool

Quarkus 3 comes with an upgrade tool that will radically simplify the upgrades from one version to another.

You can learn more about it in the <<upgrading>> section.

=== `quarkus deploy` in all dev tools

Quarkus CLI and the Maven and Gradle plugins now have the ability to `deploy` Quarkus applications.

[source,bash]
----
quarkus deploy
mvn quarkus:deploy
gradle deploy
----

This enables the deployment of Quarkus applications to platforms like Kubernetes, Knative and OpenShift.
All without requiring changes to the project dependencies or configuration and therefore simplifying developer experience.


==== Support for Maven 3.9

Maven 3.9 brught some breaking changes and the integration with Quarkus was not working properly.
It is now fixed and you can use Maven 3.9 to build your Quarkus 3 applications.

==== Gradle 8

Our Gradle support has been upgraded to Gradle 8.

=== Management network interface

Until now, all the Quarkus endpoints were exposed on the same network interface.

It is now possible to expose technical endpoints such as the health and metrics ones on a different interface thanks to link:/guides/management-interface-reference[a specific management interface].

=== /q/info

To expose information about your application (such as the git hash), add the `quarkus-info` extension to your project.

The endpoint is available on `/q/info` and will be exposed on the management network interface if you enable it.

=== RESTEasy Reactive

A lot of usability enhancements have come into RESTEasy Reactive such as the ability to retrieve all the Multipart parts.

Remember that RESTEasy Reactive is our REST layer covering both reactive and blocking workloads.

=== OpenTelemetry

The OpenTelemetry extension has been rewritten to support the SDK autoconfiguration and went under a lot of changes.

The configuration namespace has changed to `quarkus.otel.*` and it is recommended to switch to the new configuration properties, even if the old ones are still supported for now.

Enabling OpenTelemetry for JDBC is now as simple as setting `quarkus.datasource.jdbc.telemetry` to `true`.
You don't have to modify your JDBC connection URL anymore.

=== Multiple mailers

Sending emails via several SMTP servers is supported in Quarkus 3.

Have a look at the https://quarkus.io/version/main/guides/mailer-reference#multiple-mailer-configurations[updated documentation].

=== Qute

Qute, our templating engine, also got a lot of love with several new features such as the ability to cache a section of the template that rarely changes thanks to link:/guides/qute-reference#cached-section[cached sections].

=== Cache

It is now possible to use a Redis backend with the Cache extension.

More information in the https://quarkus.io/version/main/guides/cache-redis-reference[dedicated guide].

The cache extension now allows you to define global defaults cache configuration that will be applied to all your caches.

=== Database migrations

Your database migrations with Flyway and Liquibase are now run as init containers in manifests.

The Flyway extension supports custom credentials/URL to connect to the database
and you can more easily customize the configuration of the Flyway instance.

The notion of migration/setup work being done in init cotainers is available for other extensions to implement and su[pport.]

=== MongoDB

`CredentialsProvider`s are now supported for MongoDB connections.

=== Elasticsearch Java Client extension

The new Elasticsearch Java Client is supported as a brand new extension.
This solves the licensing problems that prevented us to update the deprecated High Level REST Client.

To use this new client, have a look at the updated link:/guides/elasticsearch[Elasticsearch guide].

=== gRPC

Several enhancements have been made to the gRPC extensions such as the support of `InProcess`.

=== Scheduler API

You can now schedule jobs programmatically by using the Scheduler programmatic API,
described in the link:/guides/scheduler-reference#programmatic_scheduling[Scheduler reference guide].

=== Kubernetes Client

The Kubernetes Client has been upgraded to version 6.5.

=== Azure Functions extension

The development of Azure functions is easier than ever thanks to the new Azure Functions extension.

Learn more about it in the link:/guides/azure-functions[dedicated guide]

[[upgrading]]

== Upgrading to Quarkus 3

TODO

== I use Quarkus 2, do I need to migrate right away?

We are aware that the migration to Quarkus 3 will require some work and testing on your side, especially if you are using Hibernate ORM.

That's why we will maintain Quarkus 2.16 with bugfixes and important CVE fixes for a few months so that you have the time to upgrade your applications to Quarkus 3.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/2.16.0.CR1[2.16.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/2.16.0.Final[2.16.0.Final] on GitHub.

== Release cadence and Long Term Support

With Quarkus 3 finally out we will be returning to have our regular continuous release cadence of approximate every 5 weeks. This provides a delivery train of small incremental changes that are easy to adopt and upgrade to.

We do know some of you are looking for a more stable release cadence and we are working on a new long term support (LTS) policy starting from Quarkus 3.2. We will provide details on this as we get closer to the 3.2 release.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[746 contributors].
Many many thanks to each and everyone of them.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
