---
layout: post
title: 'Quarkus 3.4.1 released - Redis 7.2 and Flyway changes'
date: 2023-09-20
tags: release
synopsis: 'We released Quarkus 3.4.1 which comes with support for Redis 7.2 and changes to the Flyway extension.'
author: gsmet
---

It is our pleasure to announce the release of Quarkus 3.4.1.
We skipped 3.4.0 as we needed a fix for CVE-2023-4853 in 3.4 too.

Major changes are:

  * Support for Redis 7.2
  * Adjustments on how to enable/activate Flyway

This version also comes with bugfixes, performance improvements and documentation improvements.

We currently maintain 3 version streams in the community:

- 3.4: it is the latest and greatest and it introduces new features
- 3.2: it is our current link:/blog/lts-releases/[LTS release]
- 2.16: we plan to release a few more releases but we recommend you to migrate your applications before the end of October, as there is little chance we will release new 2.16 releases after this date

== Update

To update to Quarkus 3.4, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

To migrate from 3.3, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[our migration guide].

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1] and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2] migration guides.

== What's new?

=== Redis 7.2

Our Redis extension now supports Redis 7.2.

=== Flyway

The Flyway extension has seen significant changes in 3.3 and some of these changes introduced some regressions in corner cases,
typically when you had several datasources, one of which is not supported by Flyway.

It is now possible to entirely disable the automatic setup of the Flyway extension by setting `quarkus.flyway.enabled=false`.

You can also make Flyway inactive for a specific datasource by setting `quarkus.flyway.active=false` for the default datasource or `quarkus.flyway."datasource name".active=false` for a named datasource.

=== OpenSearch Dev Services

Dev Services can now start an OpenSearch container,
either automatically when using Hibernate Search with OpenSearch or manually by setting the distribution with `quarkus.elasticsearch.devservices.distribution=opensearch`.

More information in https://quarkus.io/guides/elasticsearch-dev-services#configuring-the-image[our documentation].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.4.0.CR1[3.4.0.CR1], https://github.com/quarkusio/quarkus/releases/tag/3.4.0[3.4.0], and https://github.com/quarkusio/quarkus/releases/tag/3.4.1[3.4.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[846 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.4 release, thanks to Ales Justin, Alexander Schwartz, Alexey Loubyansky, Andy Damevin, Bill Burke, Bony, brunobat, chrischiedo, Clement Escoffier, Daniel Kraus, David M. Lloyd, Dennis Kieselhorst, domkun, Erin Schnabel, Falko Modler, Foivos Zakkak, Fouad Almalki, Gasper Kojek, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Ioannis Canellos, Jan Martiska, Jonathan Kolberg, Jose, Katia Aresti, Ladislav Thon, Laurent SCHOELENS, Loïc Hermann, Loïc Mathieu, Marc Nuri, Marc Savy, Marco Schaub, Marek Skacelik, marko-bekhta, Martin Bartoš, Martin Kouba, Martin Zuber, Matej Novotny, Max Rydahl Andersen, Michal Karm Babacek, Michal Maléř, Michal Vavřík, Michelle Purcell, Monhemius,  B. (Bart), mrizzi, Ozan Gunalp, Phillip Krüger, Rene Grob, Robert Stupp, Roberto Cortez, Rolfe Dlugy-Hegwer, Romain LE BARO, Rostislav Svoboda, Sanne Grinovero, seepine, Sergey Beryozkin, Shivam Sharma, shjones, Stéphane Épardaud, suchwerk, xstefank, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
