---
layout: post
title: 'Quarkus 3.2.7.Final released - Maintenance release'
date: 2023-10-19
tags: release
synopsis: 'Quarkus 3.2.7.Final is the seventh maintenance release of our 3.2 LTS release train. It fixes CVE-2023-43642, CVE-2023-34454, CVE-2023-44487 and CVE-2023-39410'
author: aloubyansky
---

Today, we released Quarkus 3.2.7.Final, the seventh maintenance release of our 3.2 LTS release train.

This release fixes several CVEs:

- https://nvd.nist.gov/vuln/detail/CVE-2023-43642[CVE-2023-43642], https://nvd.nist.gov/vuln/detail/CVE-2023-34454[CVE-2023-34454] upgrading Snappy Java library version to 1.1.10.5
- https://nvd.nist.gov/vuln/detail/CVE-2023-39410[CVE-2023-39410] upgrading Apache Avro version to 1.11.3
- https://nvd.nist.gov/vuln/detail/CVE-2023-44487[CVE-2023-44487] upgrading Netty version to Netty to 4.1.100

And one bug:

- https://github.com/quarkusio/quarkus/issues/35774[RESTEasy Reactive fails to handle collections of parameterized types as parameter]

It should be a safe upgrade for anyone already using 3.2.

If you are not already using 3.2, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[our migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.2.7.Final[the full changelog of 3.2.7.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
