---
layout: post
title: 'Quarkus 3.2.3.Final released - Maintenance release'
date: 2023-08-02
tags: release
synopsis: 'Quarkus 3.2.3.Final is the third maintenance release of our 3.2 release train.'
author: gsmet
---

August is upon us but we are still steadily publishing new Quarkus releases.
Today, we released Quarkus 3.2.3.Final, the third maintenance release of our 3.2 release train.

It should be a safe upgrade for anyone already using 3.2.

Note that this version upgrades Hibernate Search to 6.2
as we wanted to offer full support for Elasticsearch 8 in Quarkus 3.2.
If you are using Hibernate Search, have another look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2#hibernate-search[dedicated section of the 3.2 migration guide].

If you are not already using 3.2, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[Quarkus 3.2 migration guide].

And if you are not already using 3.0, please refer to https://quarkus.io/blog/quarkus-3-0-final-released/[the Quarkus 3.0 announcement] and in particular the section about the https://quarkus.io/blog/quarkus-3-0-final-released/#upgrading[upgrade path to 3.0] together with the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1 migration guide] and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[Quarkus 3.2 migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.2.3.Final[the full changelog of 3.2.3.Final] and https://github.com/quarkusio/quarkus/releases/tag/3.2.3.Final[the full changelog of 3.2.3.Final] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
