---
layout: post
title: 'Our next LTS will be Quarkus 3.15'
date: 2024-07-16
tags: release
synopsis: 'Our next LTS (Long Term Support) Quarkus release will be Quarkus 3.15 released at the end of September.'
author: gsmet
---

We started releasing Long Term Support (LTS) releases with Quarkus 3.2.
LTS releases are supported significantly longer than our regular Quarkus releases.

If you don't want to follow closely the development of Quarkus,
and if you don't want to update regularly your applications to the latest Quarkus,
LTS releases are the best choice for you.

Our second LTS was Quarkus 3.8, released in February 2024.

It is our pleasure to announce that the next LTS will be Quarkus 3.15,
that we plan to release at the end of September 2024.

For 3.15, we will follow the same strategy we inaugurated for 3.8,
strategy that makes sure the LTS release is rock solid from the start.

[IMPORTANT]
====
**tl;dr**

Quarkus 3.15 will be our next LTS release.
It will be the direct continuation of the `3.14` branch.

If you contribute to Quarkus or the Quarkus Platform and need a feature in the next Quarkus LTS,
make sure it has been merged in the https://github.com/quarkusio/quarkus[Quarkus repository] before August 13th included
(the day before the `3.14.0.CR1` release).
====

== Quarkus 3.13

Quarkus 3.13 will be a regular minor version of Quarkus.

It will be released on July 31st.

See our https://github.com/quarkusio/quarkus/wiki/Release-Planning[release schedule] for all the details.

== Quarkus 3.14

Quarkus 3.14 will be released on August 28th.

We will branch Quarkus 3.14 from `main` when we release 3.14.0.CR1 on August 14th.

After branching, `main` will host the development for Quarkus **3.16**.

== Quarkus 3.15

Quarkus 3.15 will be our next LTS version.
It will be released on September 25th.

This release will be the direct continuation of the 3.14 cycle and will actually get branched from the `3.14` branch.
The focus for the 3.15 cycle will be on hardening 3.14 and fixing issues.
It won't contain any new features.
It might contain some additional component upgrades to fix CVEs or important bugs.

**Consequently, and this is important:
if you contribute to Quarkus or the Quarkus Platform and need a feature in the next Quarkus LTS,
make sure it has been merged in the https://github.com/quarkusio/quarkus[Quarkus repository] before August 13th included
(the day before the `3.14.0.CR1` release).**

As this release will be maintained for 12 months, we will be recommending that extension maintainers and contributors consider bug fixes and enhancements for LTS releases.
This will ensure that LTS releases are as stable and robust as possible, while still offering the full breadth of the Quarkus ecosystem.

This means that extension maintainers and contributors will need to consider having branches and versioning in place to support 3.15 during the whole LTS cycle.

== Quarkus 3.16

Quarkus 3.16 will be released at the end of October.

It will be packed with new features as it will contain 2 months of work,
whereas our usual minors contain 1 month of work.

== Questions?

If you have any questions about this plan, feel free to ask in the comments of this blog post or on https://github.com/quarkusio/quarkus/discussions/categories/community[GitHub Discussions].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
