---
layout: post
title: 'Our next LTS will be Quarkus 3.20'
date: 2024-12-18
tags: release
synopsis: 'Our next LTS (Long Term Support) Quarkus release will be Quarkus 3.20 released at the end of March. Feature freeze is February 11th.'
author: gsmet
---

You are probably now familiar with our biannual (as in twice a year) LTS releases.

Every 6 months, we pick a Quarkus release that will be supported for a full year.

LTS releases are designed for users who want to keep a given version for a longer period of time
instead of following our monthly release pace.

We already released a few LTS (namely 3.2, 3.8, and 3.15 released at the end of September)
and we know that some of our users are now planning their work according to our LTS schedule.

Now is time to announce the schedule for our next LTS: Quarkus 3.20.

[IMPORTANT]
====
**tl;dr**

Quarkus 3.20 will be our next LTS release.
It will be the direct continuation of the `3.19` branch.

If you contribute to Quarkus or the Quarkus Platform and need a feature in the next Quarkus LTS,
make sure it has been merged in the https://github.com/quarkusio/quarkus[Quarkus repository] before February 11th included
(the day before the `3.19.0.CR1` release).

**February 11th is the date of the feature freeze for Quarkus 3.19 and 3.20 LTS.**
====

== Quarkus 3.18

Quarkus 3.18 will be a regular minor version of Quarkus.

It will be released on January 29th 2025.

See our https://github.com/quarkusio/quarkus/wiki/Release-Planning[release schedule] for all the details.

== Quarkus 3.19

Quarkus 3.19 will be released on February 26th.

We will branch Quarkus 3.19 from `main` when we release 3.14.0.CR1 on February 12th, as usual.

After branching, `main` will host the development for Quarkus **3.21**.

== Quarkus 3.20

Quarkus 3.20 will be our next LTS version.
It will be released on March 26th.

This release will be the direct continuation of the 3.19 cycle and will actually get branched from the `3.19` branch.
The focus for the 3.20 cycle will be on hardening 3.19 and fixing issues.
It won't contain any new features.
It might contain some additional component upgrades to fix CVEs or important bugs.

**Consequently, and this is important:
if you contribute to Quarkus or the Quarkus Platform and need a feature in the next Quarkus LTS,
make sure it has been merged in the https://github.com/quarkusio/quarkus[Quarkus repository] before February 11th included
(the day before the `3.19.0.CR1` release).**

**February 11th is the date of the feature freeze for Quarkus 3.19 and 3.20 LTS.**

As this release will be maintained for 12 months, we will be recommending that extension maintainers and contributors consider bug fixes and enhancements for LTS releases.
This will ensure that LTS releases are as stable and robust as possible, while still offering the full breadth of the Quarkus ecosystem.

This means that extension maintainers and contributors will need to consider having branches and versioning in place to support 3.20 during the whole LTS cycle.

== Quarkus 3.21

The plan is to release Quarkus 3.21 the same day as Quarkus 3.20 LTS.

It will contain the new features developed in the `main` branch during the 3.19 -> 3.20 cycle as Quarkus 3.20 LTS will be branched from the `3.19` branch.

== Questions?

If you have any questions about this plan, feel free to ask in the comments of this blog post or on https://github.com/quarkusio/quarkus/discussions/categories/community[GitHub Discussions].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
