---
layout: post
title: 'Quarkus 3.10.1 released - Maintenance release'
date: 2024-05-15
tags: release
synopsis: 'We released Quarkus 3.10.1, our first maintenance release for the 3.10 release train.'
author: gsmet
---

Today, we released Quarkus 3.10.1, our first maintenance release for the 3.10 release train.

This release contains bugfixes and documentation improvements.

It is a bit more involved than usual as we didn't release a micro last week but it should be a safe upgrade for anyone already using 3.10.

== Update

To update to Quarkus 3.10, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.10.

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[3.4], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5[3.5], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6[3.6], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7[3.7], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.8[3.8], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9[3.9], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10[3.10] migration guides.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.10.1[the full changelog of 3.10.1 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
