---
layout: post
title: 'Quarkus 3.10 - Hibernate Search standalone POJO mapper, Flyway 10, security enhancements'
date: 2024-04-30
tags: release
synopsis: 'We released Quarkus 3.10, which comes with what an extension for the Hibernate Search standalone POJO mapper, support for Flyway 10 and various security enhancements.'
author: gsmet
---

After some big changes in Quarkus 3.9, we have the pleasure to announce Quarkus 3.10.

Quarkus 3.10 is for developers who want the latest features,
if you are looking for an extended support cycle, you are encouraged to stay on 3.8 LTS.

Here are the main changes for 3.10:

* https://github.com/quarkusio/quarkus/pull/39415[#39415] - Extension for the Hibernate Search Standalone POJO Mapper with Elasticsearch
* https://github.com/quarkusio/quarkus/pull/39509[#39509] - Update Flyway to 10.10.0
* https://github.com/quarkusio/quarkus/pull/39295[#39295] - Move package config to an interface
* https://github.com/quarkusio/quarkus/pull/36504[#36504] - Allow authentication mechanism selection for a REST endpoint with annotation
* https://github.com/quarkusio/quarkus/pull/37816[#37816] - Optional support for the OIDC session cookie dir encryption
* https://github.com/quarkusio/quarkus/pull/39793[#39793] - Support for verifying OIDC JWT claims with custom Jose4j `Validator`
* https://github.com/quarkusio/quarkus/pull/39812[#39812] - Support resolving of static OIDC tenants based on token issuers
* https://github.com/quarkusio/quarkus/pull/40056[#40056] - Add OIDC TokenCertificateValidator

== Update

To update to Quarkus 3.10, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.10.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10[Quarkus 3.10 migration guide].

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[3.4], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5[3.5], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6[3.6], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7[3.7], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.8[3.8], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9[3.9], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10[3.10] migration guides.

== What's new?

=== Hibernate Search standalone POJO Mapper

Hibernate Search has been part of the Quarkus ecosystem for a long time but until now we only supported the Hibernate ORM integration.

Quarkus 3.10 adds a brand new extension to add support for the Hibernate Search standalone POJO Mapper,
which allows to index directly arbitrary POJOs.

If you want to index structured data coming from files, MongoDB entities, ... this new extension should make you happy.

Interested in this extension? We have a https://quarkus.io/guides/hibernate-search-standalone-elasticsearch[dedicated guide] for you,
which covers the Quarkus integration and the basics.

For more advanced information about the Hibernate Search standalone POJO mapper,
please consult the https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#mapper-pojo-standalone[Hibernate Search reference documentation] and the https://docs.jboss.org/hibernate/stable/search/getting-started/standalone/en-US/html_single/index.html#mapper-pojo-standalone-getting-started[Getting started] guide.

=== Flyway 10

We are a bit late to the party as we encountered some incompatibility with native executables and the new Flyway 10 but Quarkus 3.10 comes with an upgrade to Flyway 10, more precisely 10.10.

If you are not using `quarkus update`,
have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10[migration guide] as they split some more database supports out of Flyway core.

=== Changes to `quarkus.package.*` config

The `quarkus.package.*` config was refactored.

The configuration changes are handled by `quarkus update` but if you are upgrading manually, have a closer look at the dedicated section of the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10#packaging-configuration-gear-white_check_mark[migration guide].

Note that when using the previous configuration properties are deprecated but should still work
so you don't have to upgrade right away.
They will be dropped in a (relatively distant) future version.

=== Security enhancements

This new version comes with several improvements related to security:

* https://github.com/quarkusio/quarkus/pull/36504[#36504] - Allow authentication mechanism selection for a REST endpoint with annotation
* https://github.com/quarkusio/quarkus/pull/37816[#37816] - Optional support for the OIDC session cookie dir encryption
* https://github.com/quarkusio/quarkus/pull/39793[#39793] - Support for verifying OIDC JWT claims with custom Jose4j `Validator`
* https://github.com/quarkusio/quarkus/pull/39812[#39812] - Support resolving of static OIDC tenants based on token issuers
* https://github.com/quarkusio/quarkus/pull/40056[#40056] - Add OIDC TokenCertificateValidator

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.10.0.CR1[3.10.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/3.10.0[3.10.0] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[940 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.10 release, thanks to Ales Justin, Alexander Schwartz, Alexey Loubyansky, Andy Damevin, Antonio Musarra, asjervanasten, avivmu, Bas Passon, Bruno Baptista, Clement Escoffier, Damiano Renfer, David M. Lloyd, ennishol, Eric Deandrea, Erin Schnabel, fdlane, Foivos Zakkak, Fouad Almalki, Francesco Nigro, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Gwenneg Lepage, Holly Cummins, Ioannis Canellos, Jakub Jedlicka, James Netherton, Jan Martiska, Jason T. Greene, Jean Bisutti, Jerome Prinet, Jonas Jensen, Juan Jose Garcia, Julien Ponge, Jérémie Bresson, Katia Aresti, Klaus Nguetsa, Ladislav Thon, Laurent Broudoux, luneo7, Marc Nuri, Marco Sappé Griot, Marco Schaub, Marek Skacelik, marko-bekhta, Martin Kouba, Matej Novotny, Max Rydahl Andersen, Michal Maléř, Michal Vavřík, Michiel Thomassen, Monhemius,  B. (Bart), Ozan Gunalp, Peter Palaga, Phillip Krüger, Pierre Adam, Robbie Gemmell, Roberto Cortez, Sanne Grinovero, Sebastian Davids, Sergey Beryozkin, Stéphane Épardaud, Thomas Canava, Thomas Segismont, Vinicius A. Santos, xstefank, Yoann Rodière, Yoshikazu Nojima, Yukihiro Okada, and Žan Horvat.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
