---
layout: post
title: 'Quarkus 3.8 - Our new LTS version'
date: 2024-02-28
tags: release
synopsis: 'We released Quarkus 3.8, our new LTS release. It is built on the shoulders of 3.7 and comes with additional fixes.'
author: gsmet
---

It is with great pleasure that we are announcing the release of Quarkus 3.8,
our new LTS release (see https://quarkus.io/blog/lts-releases/[this blog post] for more information about our LTS releases).

LTS releases are maintained for a period of 12 months.

The previous LTS release was 3.2 and a lot of exciting new features have been added to Quarkus since then.

As we explained in https://quarkus.io/blog/our-plans-for-quarkus-3-7-3-8-3-9-released/[this blog post], 3.8 is the direct continuation of the 3.7 branch,
so it doesn't contain any new features compared to 3.7 (at least for core features, see below for new features in Quarkus CXF).

It contains several additional fixes though, including a CVE fix for https://nvd.nist.gov/vuln/detail/CVE-2024-1597[CVE-2024-1597 - PostgreSQL JDBC Driver]
(we skipped 3.8.0 to include this particular fix).

It is a recommended upgrade for everyone, including people using the previous 3.2 LTS.

== Update

To update to Quarkus 3.8, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.8.

To migrate from 3.7, you don't have anything to do except updating the version.

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[3.4], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5[3.5], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6[3.6], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7[3.7] migration guides.

== What's new?

=== Coming from 3.7?

Nothing much if you are coming from 3.7 as 3.8 is the direct continuation of 3.7.

It is a recommended upgrade though as 3.8 comes with bugfixes and security fixes.

=== Coming from 3.2 LTS?

If you are coming from our previous LTS, there is a lot to read and you should have a look at our announcements for:

- https://quarkus.io/blog/quarkus-3-3-0-released/[3.3] - OpenTelemetry improvements, Reactive Messaging Pulsar extension...
- https://quarkus.io/blog/quarkus-3-4-1-released/[3.4] - Redis 7.2 and Flyway changes...
- https://quarkus.io/blog/quarkus-3-5-0-released/[3.5] - Support for Java 21, OIDC enhancements...
- https://quarkus.io/blog/quarkus-3-6-0-released/[3.6] - SSE improvements, OIDC and security-related enhancements...
- https://quarkus.io/blog/quarkus-3-7-released/[3.7] - Java 17 as the baseline, Hibernate ORM 6.4, support for Micrometer `@MeterTag`

Make sure you have a look at the migration guides mentioned above when you update from 3.2 to 3.8.

=== Quarkus CXF

Quarkus CXF is part of the Quarkus Platform and has been updated for Quarkus 3.8.

This new version of Quarkus CXF includes the following changes:

- Keeping major.minor version in sync with Quarkus
- Logging extension removed from the documentation and code.quarkus.io
- Santuario XMLSec extension moved to Quarkus CXF
- Improved documentation

The detailed release notes can be found in the https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.8.0.html[Quarkus CXF documentation].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.8.1[3.8.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[912 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.8 release, thanks to Ales Justin, Alex Katlein, Alex Martel, Alexey Loubyansky, Andy Damevin, Bas Passon, Benedikt Werner, brunobat, Christian Thiel, Clement Escoffier, Davide D'Alto, Dimitris Kontokostas, Falko Modler, Foivos Zakkak, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Hendrik Schmitz, Holly Cummins, Ioannis Canellos, James Netherton, Jan Martiska, Jiří Locker, Julien Ponge, Katia Aresti, Ladislav Thon, Loïc Mathieu, Luke Morfill, luneo7, Marcel Stör, mariofusco, Martin Kouba, Matej Novotny, Matheus Cruz, Michael Edgar, Michal Vavřík, ObserverOfTime, Oliver Wiebeck, Ozan Gunalp, Peter Palaga, Phillip Kruger, Robert Stupp, Roberto Cortez, Romain BADINO, Sergey Beryozkin, SpaceFox, Steve Hawkins, stianst, The-Huginn, troosan, Waldemar Reusch, Yassin Hajaj, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
