---
layout: post
title: 'Quarkus 3.14.2 - Maintenance release and Micrometer 1.13'
date: 2024-09-04
tags: release
synopsis: 'We released Quarkus 3.14.2, a maintenance release for our 3.14 release train. Apart from bugfixes, it also contains an upgrade of Micrometer to 1.13.'
author: gsmet
---

We released Quarkus 3.14.2, a maintenance release for our 3.14 release train.

It contains several important bugfixes so we recommend the upgrade for anyone already using 3.14.

While our maintenance releases usually don't include important changes, we had to make an exception for the upgrade to Micrometer 1.13.

Our main issue was that Micrometer 1.12 would reach EOL in a few months, which wasn't in line with the upcoming 3.15 LTS release.
As previously explained, 3.15 will be based the continuation of the 3.14 branch,
thus why we included this update in 3.14.

The https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#micrometer[3.14 migration guide] has been updated to reflect that.

== Update

To update to Quarkus 3.14, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.14.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14[Quarkus 3.14 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.14.2[3.14.2] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
