---
layout: post
title: 'Quarkus 3.14.4 - Maintenance release'
date: 2024-09-14
tags: release
synopsis: 'We released Quarkus 3.14.4, which fixes an issue in Gradle + Kotlin support introduced in 3.4.3.'
author: gsmet
---

We released Quarkus 3.14.4, a maintenance release for our 3.14 release train.

It contains several important bugfixes so we recommend the upgrade for anyone already using 3.14.

It is especially important if you are using the combination of Gradle and Kotlin
as we reverted an enhancement that caused an important regression.

== Update

To update to Quarkus 3.14, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.14.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14[Quarkus 3.14 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.14.4[3.14.4] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
