---
layout: post
title: 'Quarkus 3.20 - new LTS version'
date: 2025-03-26
tags: release
synopsis: 'We released Quarkus 3.20, our new LTS version.'
author: gsmet
---

It is our pleasure to announce the release of Quarkus 3.20, which is our new LTS (Long Term Support) version.

This version is built on the top of Quarkus 3.19 with some additional bugfixes.
New features landed in https://quarkus.io/blog/quarkus-3-21-0-released/[Quarkus 3.21], which was also released today.

If you want to know more about our LTS policy, the https://quarkus.io/blog/lts-releases/[LTS announcement] is a must read.

LTS releases are supported for 12 months.

If you are coming from the previous LTS, Quarkus 3.15, there are a lot of exciting new features and we recommend reading the following announcements:

- https://quarkus.io/blog/quarkus-3-16-1-released/[Quarkus 3.16 - OpenTelemetry Logging, LGTM Quarkus dashboard and too many things to list here]
- https://quarkus.io/blog/quarkus-3-17-0-released/[Quarkus 3.17 - Observability improvements, programmatic permission checkers, MicroProfile REST Client 4.0]
- https://quarkus.io/blog/quarkus-3-18-1-released/[Quarkus 3.18 - Micrometer for WebSockets Next, Security WebAuthn based on WebAuthn4J, Kubernetes Client 7...]
- https://quarkus.io/blog/quarkus-3-19-1-released/[Quarkus 3.19 - UBI 9 images, Micrometer to OpenTelemetry bridge, JEP 483 new AOT cache...]

== Update

To update to Quarkus 3.20, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.20 LTS.

If you are upgrading from 3.19, there's nothing to do as 3.20 is the direct continuation of 3.19.

If you are upgrading from the previous LTS, Quarkus 3.15, please refer to the following migration guides:

- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.16[Migration guide for 3.16]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.17[Migration guide for 3.17]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.18[Migration guide for 3.18]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.19[Migration guide for 3.19]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.20[Migration guide for 3.20] - this one is empty as 3.20 is the continuation of 3.19

Note that `quarkus update` should handle most of the heavy lifting for you,
but there are still cases that should be handled manually and we recommend reading these migration guides carefully.

== What's new?

=== Platform component upgrades

==== Camel Quarkus

Camel Quarkus has been updated to 3.20.0.
You can find everything you need to know about it in the https://camel.apache.org/blog/camel-quarkus-release-3.20.0[release notes].

==== Quarkus CXF

Quarkus CXF 3.20 was released and is now available in https://code.quarkus.io/?extension-search=origin:platform%20quarkus-cxf[Quarkus Platform 3.20].
Check the https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.20.0.html[Quarkus CXF 3.20.0] release notes for more information about what is new in this release.

==== Amazon Services

The Amazon Services extensions have been upgraded to version 3.3.1.

== Full changelog

The core part of Quarkus 3.20.0 is a rebadged release of Quarkus 3.19.4 so nothing new here.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1068 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.20 release, thanks to Ales Justin, Alexey Loubyansky, Andreas Maechler, Andy Damevin, Auri Munoz, brunobat, Clement Escoffier, cmoulliard, David Cotton, Dennis Kronbügel, Fabian, Foivos Zakkak, Georg Leber, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Jakub Jedlicka, Jan Martiska, jcjveraa, Karm Michal Babacek, Katia Aresti, Ladislav Thon, Marco Belladelli, Martin Kouba, Martin Panzer, masecla22, Maximilian Zellhofer, melloware, Michal Maléř, Michal Vavřík, Ozan Gunalp, Peter Palaga, Phillip Kruger, Robert Stupp, Roberto Cortez, Rolfe Dlugy-Hegwer, Ryan Dens, Rüdiger zu Dohna, Sergey Beryozkin, shjones, Stephan Strate, Steve Hawkins, Stuart Douglas, Thomas Canava, w0pp, Welton Rodrigo Torres Nascimento, Willem Jan Glerum, xstefank, and Yoshikazu Nojima.

The list is a bit smaller than usual as 3.20 only contains bugfixes on top of 3.19.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
