---
layout: post
title: 'Quarkus 3.26.3 - Maintenance release'
date: 2025-09-10
tags: release
synopsis: 'We released Quarkus 3.26.3, a regular maintenance release.'
author: jmartisk
---

Today, we released Quarkus 3.26.3, a regular maintenance release.

It contains some bug fixes, CVE fixes and documentation improvements, as we continue strengthening Quarkus 3.26 to prepare for Quarkus 3.27 LTS. 3.27 LTS will be a continuation of the 3.26 branch. See the https://quarkus.io/blog/lts-releases/[blog] for more information about LTS releases.

== Update

To update to Quarkus 3.26, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.26.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.26[Quarkus 3.26 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.26.3[3.26.3] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

* provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
* craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
* discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
* ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
