---
layout: post
title: 'Quarkus 3.28 - More security features, custom Grafana dashboards, support for multiple clients in Liquibase MongoDB, and more'
date: 2025-09-24
tags: release
synopsis: 'Today, we released Quarkus 3.28. It comes with some additional configuration for our security extensions and LGTM Dev Services, and support for multiple clients in Liquibase MongoDB.'
author: gsmet
---

Today, we released both Quarkus 3.27 LTS and Quarkus 3.28.
While Quarkus 3.27 is a Long Term Support (LTS) release, branched from Quarkus 3.26 and maintained for 12 months, Quarkus 3.28 comes with some new features.

Quarkus 3.28 introduces the following notable changes:

* https://github.com/quarkusio/quarkus/pull/49618[#49618] - Provide a fluent API for CSRF programmatic set up
* https://github.com/quarkusio/quarkus/pull/49122[#49122] - Support flow-specific OIDC request and response filters
* https://github.com/quarkusio/quarkus/pull/49151[#49151] - Allow for custom Grafana dashboards
* https://github.com/quarkusio/quarkus/pull/49805[#49805] - Add support for multiple clients in Liquibase MongoDB extension

Building Quarkus applications should also be faster with this release, thanks to an effort to reduce memory allocations during the build, parallelize some more tasks such as Hibernate ORM proxy generation or building the Jar file, and various other improvements.

== Update

To update to Quarkus 3.28, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.28.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.28[Quarkus 3.28 migration guide].

== What's new?

=== Security

It is now possible to configure CSRF protection programmatically using a https://quarkus.io/guides/security-csrf-prevention#csrf-prevention-programmatic-set-up[fluent API].

You can restrict an `OidcRequestFilter` or an `OidcResponseFilter` to a specific authentication flow by using the `@BearerTokenAuthentication` and `@AuthorizationCodeFlow` annotations.
Find out more about this new feature in https://quarkus.io/guides/security-oidc-bearer-token-authentication#restrict-oidc-filter-to-bearer-auth-flow[OpenID Connect (OIDC) Bearer token authentication] and https://quarkus.io/guides/security-oidc-code-flow-authentication#restrict-oidc-filter-to-code-flow[OpenID Connect authorization code flow mechanism for protecting web applications] guides.

=== Custom Grafana dashboards

You can now provide custom Grafana dashboards by placing JSON descriptors in the `META-INF/grafana/` directory of your application.
You can find more information in the https://quarkus.io/guides/observability-devservices-lgtm#custom-dashboards[Observability Dev Services with Grafana OTel LGTM] guide.

=== Liquibase MongoDB

The MongoDB extension have supported multiple clients for a very long time.
The Liquibase MongoDB extension was only supporting a single client so far, but it now https://quarkus.io/guides/liquibase-mongodb#multiple-clients[supports multiple clients] as well.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.28.0.CR1[3.28.0.CR1], https://github.com/quarkusio/quarkus/releases/tag/3.28.0[3.28.0], and https://github.com/quarkusio/quarkus/releases/tag/3.28.1[3.28.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1122].
Many many thanks to each and everyone of them.

In particular for the 3.28 release, thanks to Akulov S V, Ales Justin, Alex Martel, Alexey Loubyansky, andreatp, Andy Damevin, Bhawna, Bruno Baptista, Chris Laprun, Christian Beikov, Clement Escoffier, Diego Fernandez Aceves, Eli Barbosa, Eric Deandrea, Florent Fourcade, Foivos Zakkak, Fouad Almalki, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Jakub Jedlicka, Jan Martiska, Jan Scheidegger, Jonas Rutishauser, Joseph Zhang, Julien Ponge, Justin Bertram, Karm Michal Babacek, Katia Aresti, Ladislav Thon, Lars Andringa, Luca Molteni, Luke Morfill, Marc Nuri, Marco Belladelli, marko-bekhta, Martin Bartoš, Martin Kouba, Matej Novotny, Melloware, Michael Edgar, Michal Maléř, Michal Vavřík, Mikhail Polivakha, Ozan Gunalp, Paulo Casaes, Peter Palaga, Phillip Krüger, Roberto Cortez, Rolfe Dlugy-Hegwer, Rostislav Svoboda, Rúben Garcia, Saee Saadat, Sanne Grinovero, Sergey Beryozkin, Stéphane Épardaud, Teymur Babayev, Unai Valle, xstefank, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
