---
layout: post
title: 'Quarkus 3.15.6 released - LTS maintenance release'
date: 2025-07-23
tags: release
synopsis: 'We released Quarkus 3.15.6, the next maintenance release for the 3.15 LTS stream.'
author: gsmet
---

Today, we released Quarkus 3.15.6, our next maintenance release for the 3.15 LTS stream.

This release contains bugfixes and documentation improvements.

It should be a safe upgrade for anyone already using 3.15.

== Update

To update to Quarkus 3.15, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update --stream=3.15
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.15.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.15.6[the full changelog of 3.15.6 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
