---
layout: post
title: 'Quarkus 3.23 - Named datasources for Hibernate Reactive, OIDC bearer step up authentication'
date: 2025-05-28
tags: release
synopsis: 'Today, we released Quarkus 3.23, which comes with a lot of small improvements and a couple of new features.'
author: gsmet
---

Today, we released Quarkus 3.23.

3.23 comes with a lot of small improvements and some bugfixes together with a couple of new features:

* https://github.com/quarkusio/quarkus/pull/47631[#47631] - Enable named data sources for Hibernate Reactive
* https://github.com/quarkusio/quarkus/pull/47445[#47445] - OIDC: Add bearer token step up authentication

== Update

To update to Quarkus 3.23, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.23.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.23[Quarkus 3.23 migration guide].

== What's new?

=== Named data sources for Hibernate Reactive

With 3.22, we started the journey of bringing the Hibernate Reactive extension up to par with the Hibernate ORM one.

In 3.23, it's now possible to point Hibernate Reactive to a named datasource.

The next step will be to have support for multiple named persistence units for Hibernate Reactive and hopefully it will arrive in 3.24.

=== OIDC bearer step up authentication

Quarkus 3.23 introduces support for the OAuth 2.0 Step Up Authentication Challenge Protocol.

You can learn more about it in the https://quarkus.io/guides/security-oidc-bearer-token-authentication#step-up-authentication[dedicated section] of the OIDC Bearer token authentication guide.

=== Platform component upgrades

==== Quarkus CXF

Quarkus CXF 3.23 was released and is now available in https://code.quarkus.io/?extension-search=origin:platform%20quarkus-cxf[Quarkus Platform 3.23].
Check the https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.23.0.html[Quarkus CXF 3.23.0] and https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.23.1.html[3.23.1] release notes for more information about what is new in these releases.

==== Camel Quarkus

Camel Quarkus has been upgraded to 3.23.0.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.23.0.CR1[3.23.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/3.23.0[3.23.0] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1083 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.23 release, thanks to Aditya Thakur, Alexandre Dutra, Alexey Loubyansky, Andrii Denysenko, Andy Damevin, appiepollo14, ayagmar, Bruno Baptista, Clement Escoffier, Fedor Dudinsky, Foivos Zakkak, Fouad Almalki, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, iedo, Ladislav Thon, Luca Molteni, luca-bassoricci, Lucien Brule, Magnus Gustafsson, Marc Nuri, mariofusco, marko-bekhta, Martin Bartoš, Martin Kouba, Martin Panzer, Matej Novotny, Matheus Cruz, Max Rydahl Andersen, melloware, Michael Edgar, Michal Vavřík, Michiel Dockx, Mikhail Polivakha, Olivier V, Ozan Gunalp, Peter Palaga, Phillip Krüger, Robert Stupp, Roberto Cortez, Rolfe Dlugy-Hegwer, Rostislav Svoboda, Sebastian Vogl, Sergey Beryozkin, Severin Gehwolf, shjones, Steve Hawkins, Stuart Douglas, Tamas Cservenak, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
