---
layout: post
title: 'Quarkus 3.29 - Multiple cache backends and Qute DAP debugger support'
date: 2025-10-29
tags: release
synopsis: 'Today, we released Quarkus 3.29. It supports multiple cache backends and provides Qute DAP debugger support.'
author: gsmet
---

Today, we released Quarkus 3.29.

Quarkus 3.29 introduces the following notable changes:

* https://github.com/quarkusio/quarkus/pull/50007[#50007] - Add support for multiple cache backends
* https://github.com/quarkusio/quarkus/pull/48962[#48962] - Provide Qute DAP debugger support
* https://github.com/quarkusio/quarkus/pull/48732[#48732] - Keep the Hibernate ORM and Reactive extensions enabled even when no entity is defined

As usual, this release also includes many bug fixes and improvements.

== Update

To update to Quarkus 3.29, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.29.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.29[Quarkus 3.29 migration guide].

== What's new?

=== Cache

Until now, the Cache extension only supported using one caching backend at a time.
For instance, it wasn't possible to use Caffeine for a given cache and Redis for another one.

With this release, you can now define multiple cache backends and associate each cache to a specific backend.
You can find more information in the https://quarkus.io/guides/cache#configuring-the-underlying-caching-provider[Configuring the underlying caching provider] section of the Cache guide.

=== Qute DAP debugger support

The Qute extension now provides support for the Debug Adapter Protocol (DAP),
which means that you can easily debug your Qute templates in your favorite IDE!

=== Hibernate ORM and Reactive

Both Hibernate ORM and Hibernate Reactive extensions are now enabled even when no entity is defined in your application.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.29.0.CR1[3.29.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/3.29.0[3.29.0] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1131].
Many many thanks to each and everyone of them.

In particular for the 3.29 release, thanks to Akulov S V, Ales Justin, Alex Martel, Alexey Loubyansky, Alon Gamliel, Andy Damevin, Aryant, Aurea Munoz, azerr, Bhawna, Bruno Baptista, Chris Laprun, Clement Escoffier, Daniel Cunha, Darko Janković, David M. Lloyd, Eli Barbosa, Eric Deandrea, Fedor Dudinsky, Foivos Zakkak, Fouad Almalki, Francesco Nigro, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Houssam El Mansouri, Ioannis Canellos, Jakub Jedlicka, Jan Martiska, Jan Pohlmeyer, joonseolee, Julien Ponge, Juliusz Ćwiąkalski, Karm Michal Babacek, Katia Aresti, Ladislav Thon, Lars Andringa, Luca Molteni, Maciej Swiderski, Manuel Müller, Marco Belladelli, marko-bekhta, Martin Kouba, Matej Novotny, Matheus Cruz, Maximilian Zellhofer, Melloware, Michael Edgar, Michal Jurc, Michal Vavřík, Nathan Erwin, Neil J. L. Benn, Ozan Gunalp, Peter Palaga, Phillip Krüger, Pierre Beitz, Piotr Płaczek, Robert Kühne, Robert Stupp, Roberto Cortez, Roman Lovakov, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Severin Gehwolf, Steve Hawkins, Stéphane Épardaud, Thomas Segismont, Tomas Hofman, xstefank, Yoann Rodière, Yukihiro Okada, yuokada, and zg-riband.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
