---
layout: post
title: 'Introducing Model Context Protocol servers project'
date: 2025-01-28
tags: ai
synopsis: Introducing the Model Context Protocol servers project which provides a set of MCP servers implemented using Quarkus and Java. Starting with JDBC, filesystem and JavaFX.
author: maxandersen
---
:imagesdir: /assets/images/posts/mcpservers
ifdef::env-github,env-browser,env-vscode[:imagesdir: ../assets/images/posts/mcpservers]

Today, I'm excited to introduce the Model Context Protocol (MCP) servers project.

Model Context Protocol is the recent approach to enable AI models to interact with your applications and services in a nice decoupled way.

There is already a lot of MCP servers implemented in other languages, but this project is as far as I know the first one to 
provide a set of MCP servers implemented using Java and at least uniquely Quarkus.

Intended to show-case the capabilities of the Model Context Protocol, and inspiration for what you can do with it - especially in Java.

== The Servers

At time of writing there are three servers implemented:

JDBC:: Let your AI app introspect and interact to any JDBC-compatible database

Filesystem:: Access the file system 

JavaFX:: Draw on a JavaFX canvas

Each server is implemented using Quarkus and Java, and each server is available to easily run using JBang.

== How to use the servers

The general setup is to install JBang (no need for Java, Quarkus or any other Java tool installed).

Then in your MCP client configure it with:

`jbang [server-name]@quarkiverse/quarkus-mcp-servers [arguments]`

Thus for example to run the JDBC server to connect to a MariaDB database you would do:

`jbang mcp-jdbc-server@quarkiverse/quarkus-mcp-servers jdbc:mariadb://localhost:3306/test --user root --password mysecretpassword`

and if you use a client that is compatible with Claude Desktop config this is how it would look for enabling all the servers:

```json
{
  "mcpServers": {
    "jdbc": {
      "command": "jbang",
      "args": [
        "jdbc@quarkiverse/quarkus-mcp-servers",
        "jdbc:sqlite:%{https://github.com/jpwhite3/northwind-SQLite3/raw/refs/heads/main/dist/northwind.db}"
      ]
    },
    "jfx": {
      "command": "jbang",
      "args": [
        "jfx@quarkiverse/quarkus-mcp-servers"
      ]
    },
    "files": {
      "command": "/jbang",
      "args": [
        "filesystem@quarkiverse/quarkus-mcp-servers",
        "~/code/quarkusio/quarkus",
        "~/code/jbangdev/jbang",
      ]
    }
  }
}
```

There are more examples for each server in their respective README files. 

== Conclusion

This project is a fun way to show-case the capabilities of the Model Context Protocol, and inspiration for what you can do with it - especially in Java.

I hope you will find it useful and fun to play with.

