---
layout: post
title: 'Quarkus 3.21 - TLS Registry support for MongoDB Client'
date: 2025-03-26
tags: release
synopsis: 'Quarkus 3.21 comes with a lot of small enhancements and TLS Registry support for the MongoDB Client extension'
author: gsmet
---

Today, together with Quarkus 3.20 LTS, we released Quarkus 3.21.

Whereas Quarkus 3.20 LTS is the direct continuation of Quarkus 3.19, Quarkus 3.21 comes with new features.

It comes with a lot of small enhancements and the support for the TLS Registry in the MongoDB Client extension.

== Update

To update to Quarkus 3.21, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.21.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.21[Quarkus 3.21 migration guide].

== What's new?

=== TLS registry support for MongoDB Client

We continue to deploy the TLS registry we included a while ago to centralize and simplify the TLS configuration.

In this version, we added TLS registry support to the MongoDB Client extension.

=== Platform component upgrades

==== Quarkus CXF

Quarkus CXF 3.21 was released and is now available in https://code.quarkus.io/?extension-search=origin:platform%20quarkus-cxf[Quarkus Platform 3.21].
Check the https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.21.0.html[Quarkus CXF 3.21.0] release notes for more information about what is new in this release.

==== Camel Quarkus

Camel Quarkus has been upgraded to 3.20.0.
You can consult the https://camel.apache.org/blog/camel-quarkus-release-3.20.0[release notes] for more information.

==== Amazon Services

The Amazon Services extensions have been upgraded to version 3.3.1.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.21.0.CR1[3.21.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/3.21.0[3.21.0] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1068 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.21 release, thanks to Ales Justin, Alexander Schwartz, Alexey Loubyansky, Andrea Boriero, Andreas Maechler, Andy Damevin, Auri Munoz, Bill Burke, Bruno Baptista, Clement Escoffier, cmoulliard, David Cotton, dc1248, Dennis Kronbügel, Fabian, Felix König, Foivos Zakkak, Francesco Nigro, Georg Leber, George Gastaldi, Georgios Andrianakis, Giancarlo Calderón Cárdenas, Guillaume Nodet, Guillaume Smet, Holly Cummins, i10320, Ioannis Canellos, Jakub Jedlicka, Jan Martiska, jcjveraa, Jose Carvajal, Karm Michal Babacek, Katia Aresti, Khosbilegt Bilegsaikhan, Ladislav Thon, Loïc Mathieu, Luis Rubiera, Marco Belladelli, marko-bekhta, Martin Kouba, Martin Panzer, masecla22, Matej Novotny, Matheus Cruz, Maximilian Zellhofer, Melloware, Michal Maléř, Michal Vavřík, Ozan Gunalp, Peter Palaga, PhilKes, Phillip Krüger, Robert Stupp, Robert Toyonaga, Roberto Cortez, Rolfe Dlugy-Hegwer, Ryan Dens, Rüdiger zu Dohna, Sanne Grinovero, Sergey Beryozkin, Severin Gehwolf, shjones, SpaceFox, Stephan Strate, Steve Hawkins, Stuart Douglas, Tamas Cservenak, Thom Castermans, Thomas Canava, Thomas Segismont, w0pp, Welton Rodrigo Torres Nascimento, Willem Jan Glerum, xstefank, Yoann Rodière, and Yoshikazu Nojima.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
