---
layout: post
title: 'Quarkus 3.26.1, 3.20.2.2 and 3.15.6.2 - Emergency releases'
date: 2025-08-29
tags: release
synopsis: 'We released Quarkus 3.26.1, 3.20.2.2 and 3.15.6.2 as emergency releases.'
author: gsmet
---

Today, we released Quarkus 3.26.1, 3.20.2.2 and 3.15.6.2 to fix an important regression introduced in Vert.x 4.5.18.

We recommend upgrading to these releases as soon as possible if you are using a Quarkus version using Vert.x 4.5.18 (i.e. 3.26.0, 3.25.4, 3.20.2.1, and 3.15.6.1).

Quarkus 3.26.1 also contains some other unrelated fixes.

== Update

To update to Quarkus 3.26, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.26.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.26[Quarkus 3.26 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.26.1[3.26.1] on GitHub.

3.20.2.2 and 3.15.6.2 only contain the Vert.x update to 4.5.20.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
