---
layout: post
title: 'Quarkus 3.20.5 released - LTS maintenance release'
date: 2026-01-21
tags: release
synopsis: 'We released Quarkus 3.20.5, the next maintenance release for the 3.20 LTS stream.'
author: jmartisk
---

Today, we released Quarkus 3.20.5, our next maintenance release for the 3.20 LTS stream.

This release contains bugfixes, documentation updates and fixes the following CVEs:

- https://nvd.nist.gov/vuln/detail/CVE-2025-66560[CVE-2025-66560]
- https://nvd.nist.gov/vuln/detail/CVE-2025-59432[CVE-2025-59432]
- https://nvd.nist.gov/vuln/detail/CVE-2025-67735[CVE-2025-67735]

It should be a safe upgrade for anyone already using 3.20.

== Update

To update to Quarkus 3.20, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update --stream=3.20
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.20.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.20.5[the full changelog of 3.20.5 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

* provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
* craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
* discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
* ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
