---
layout: post
title: 'Quarkus 3.38 - Weight-based eviction for Hibernate second level Caffeine cache, and more'
date: 2026-07-29
tags: release
synopsis: 'We released Quarkus 3.38, which comes with weight-based eviction for Hibernate second level Caffeine cache regions, and more.'
author: gsmet
---

We're pleased to announce the release of Quarkus 3.38.

As most of the development effort for new features and major upgrades is now focused on Quarkus 4, this release is lighter on features than usual.
It still comes with the following notable feature:

* https://github.com/quarkusio/quarkus/pull/55284[#55284] - Support weight-based eviction for Hibernate 2LC Caffeine cache regions

== Update

To update to Quarkus 3.38, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.38.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.38[Quarkus 3.38 migration guide].

== What's new?

=== Weight-based eviction for Hibernate second level Caffeine cache regions

Quarkus 3.38 introduces support for weight-based (memory) eviction for Hibernate second level cache Caffeine cache regions.

Previously, only count-based eviction was available, meaning you could only configure the maximum number of entries per cache region.
With weight-based eviction, you can now configure eviction based on the estimated memory footprint of cached entities, providing more precise control over cache memory usage.

=== Platform updates

Various Platform components were upgraded including:

- Camel Quarkus to 3.38.0
- Quarkus Amazon Services to 3.21.1
- Quarkus Blaze-Persistence to 1.6.19
- Quarkus Debezium to 3.6.0.Final
- Quarkus Flow to 0.14.0
- Quarkus Google Cloud Services to 2.23.1
- Quarkus LangChain4j to 1.12.1
- Quarkus MCP Server to 1.13.1
- Quarkus Vault to 4.9.0

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.38.0.CR1[3.38.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/3.38.0[3.38.0] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1213] contributors.
Many many thanks to each and everyone of them.

In particular for the 3.38 release, thanks to Ahmed El amraouiyine, Alexander Schwartz, Alexey Loubyansky, amirdeljouyi, Andreas Maechler, Andy Damevin, Arthur Navarro, Ashish Thakur, Atharv Hatwar, Aurea Munoz, Ben Rose, Bruno Baptista, Clement Escoffier, David Kjerrumgaard, David M. Lloyd, Davide D'Alto, Domenico Briganti, Foivos Zakkak, Fouad Almalki, Gaelle Fournier, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Jan Martiska, Julien Ponge, Kamil Krzywanski, Katia Aresti, Kristian Rickert, Ladislav Thon, Luca Molteni, Lukas Lowinger, luneo7, Marco Belladelli, Marek Skacelik, mariofusco, marko-bekhta, Martin Kouba, Matheus Cruz, MdTanwer, Michal Vavřík, Ozan Gunalp, Phillip Krüger, Robert Stupp, Roberto Cortez, Rolfe Dlugy-Hegwer, Sergey Beryozkin, Ståle Pedersen, Stéphane Épardaud, Teymur Babayev, Thomas Segismont, Vojin Jovanovic, Willem Jan Glerum, xstefank, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
