---
layout: post
title: 'Quarkus 3.31 - Full Java 25 support, Quarkus Maven packaging, Panache Next, and more!'
date: 2026-01-28
tags: release
synopsis: 'This release is packed with new features and improvements, including full Java 25 support, a new Quarkus Maven packaging type, Panache Next, Hibernate upgrades, JUnit 6 and Testcontainers 2 upgrades, and numerous enhancements to our Security extensions.'
author: gsmet
---

It has been two months since our last feature release, and we are excited to announce the availability of Quarkus 3.31!

Quarkus 3.31 comes with a LOT of new features and improvements:

* Full Java 25 support
* https://github.com/quarkusio/quarkus/pull/51587[#51587] - Introduce a quarkus Maven packaging and an assorted lifecycle
* https://github.com/quarkusio/quarkus/pull/50058[#50058] - Introduce Panache Next, our next generation of Panache with improved developer experience and new features for both Hibernate ORM and Hibernate Reactive
* https://github.com/quarkusio/quarkus/pull/50519[#50519] - Upgrade to Hibernate ORM 7.2, Reactive 3.2, Search 8.2, Elasticsearch 9.2 / OpenSearch 3.3 for clients / server (dev services)
* https://github.com/quarkusio/quarkus/pull/51586[#51586] - Hibernate Spatial support
* https://github.com/quarkusio/quarkus/pull/51314[#51314] - Upgrade to Testcontainers 2
* https://github.com/quarkusio/quarkus/pull/51412[#51412] - Upgrade to JUnit 6
* https://github.com/quarkusio/quarkus/pull/50987[#50987] - Support security annotations on Jakarta Data repositories
* https://github.com/quarkusio/quarkus/pull/51188[#51188] - Support `@PermissionsAllowed` security annotation on REST Data Panache endpoints
* https://github.com/quarkusio/quarkus/pull/51220[#51220] - Encrypt OIDC tokens for custom TokenStateManager implementations
* https://github.com/quarkusio/quarkus/pull/51383[#51383] - Allow to configure OIDC DB token state manager column sizes for tokens
* https://github.com/quarkusio/quarkus/pull/51743[#51743] - Allow to select OIDC client for individual dynamic GraphQL clients
* https://github.com/quarkusio/quarkus/pull/51679[#51679] - Allow to assign a user and roles to a scheduled task
* https://github.com/quarkusio/quarkus/pull/51799[#51799] - Add support for OAuth 2.0 Pushed Authorization Requests to OIDC extension
* https://github.com/quarkusio/quarkus/pull/50603[#50603] - Enable headless AWT on Windows for native images
* https://github.com/quarkusio/quarkus/pull/51736[#51736] - Require Maven 3.9.0+ for Quarkus projects
* https://github.com/quarkusio/quarkus/pull/51049[#51049] - Add i18n to Dev UI

As usual, this release also includes many bug fixes, including fixes for some https://github.com/quarkusio/quarkus/pull/51891[very old issues created in 2020], thanks to our amazing community!

We highly recommend to have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.31[migration guide] as this version comes with some important changes.

== Update

To update to Quarkus 3.31, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.31.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.31[Quarkus 3.31 migration guide].

== What's new?

=== Full support for Java 25

Quarkus 3.31 adds full support for Java 25, including Java 25 runtime images and native image builds with Mandrel.

If you create new projects with Java 25, the projects will fully target Java 25 by default.

We were hard at work to ensure compatibility and avoid as many warnings as possible when running Quarkus applications on Java 25.
If you encounter any issues, including warnings that shouldn't be there, please report them on our https://github.com/quarkusio/quarkus/issues[bug tracker].

=== New quarkus Maven packaging and lifecycle

A few months ago, we started working on making our builds faster (see this https://quarkus.io/blog/building-large-applications/[blog post] for all the gory details).
With Quarkus 3.31, we are introducing a new Maven packaging type called `quarkus`, designed to provide a more integrated and significantly more efficient build lifecycle.

In other words, we move away from the default Maven `jar` lifecycle and introduce a Quarkus-specific lifecycle optimized for Quarkus applications, avoiding the execution of goals that are unnecessary in most cases.

It is the default for newly created Quarkus projects and it can also be used for existing projects (see the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.31#new-quarkus-packaging-and-maven-lifecycle[migration guide] for more details).

=== Larger applications

This "faster builds" effort is particularly beneficial for larger applications and we alleviated one of the latest bottleneck for creating VERY large applications:
the number of CDI beans in the application could hit some class file limits during the build.

With Quarkus 3.31, you shouldn't be limited by the number of CDI beans anymore.

=== Panache Next

If you use Hibernate ORM with Quarkus, you are probably already familiar with Hibernate ORM with Panache.

Panache Next is our next generation of Panache that brings a better developer experience and new features.
While relying on the same underlying concepts as the current Panache implementation, Panache Next introduces a more intuitive API, improved type safety, and enhanced query capabilities.
It also unifies the programming model between Hibernate ORM and Hibernate Reactive, stateful and stateless sessions, making it easier for developers to switch between them.
Finally, it integrates seamlessly with Jakarta Data.

There would be a lot more to say but the best is to have a look at the https://quarkus.io/guides/hibernate-panache-next[documentation], and give it a try.

It is still experimental and we are very looking forward to your feedback.

=== Hibernate

Quarkus 3.31 upgrades Hibernate ORM to 7.2, Hibernate Reactive to 3.2, Hibernate Search to 8.2, and the Elasticsearch/OpenSearch clients and servers to 9.2/3.3 respectively.

It also brings support for Hibernate Spatial, allowing developers to work with spatial data types and perform spatial queries in their Quarkus applications.

=== JUnit 6 and Testcontainers 2

We upgraded to JUnit 6 (the update is relatively straightforward) and Testcontainers 2 (which comes with a lot more breaking changes).

The `-junit5` extensions have been renamed to `-junit`, with relocations in place to avoid breaking existing projects.
Use `quarkus update` to get them updated automatically.

=== Security

What would be a Quarkus release without security improvements?

This release comes with a lot of improvements to our security extensions, including:

* https://github.com/quarkusio/quarkus/pull/50987[#50987] - Support security annotations on Jakarta Data repositories
* https://github.com/quarkusio/quarkus/pull/51188[#51188] - Support `@PermissionsAllowed` security annotation on REST Data Panache endpoints
* https://github.com/quarkusio/quarkus/pull/51220[#51220] - Encrypt OIDC tokens for custom TokenStateManager implementations
* https://github.com/quarkusio/quarkus/pull/51383[#51383] - Allow to configure OIDC DB token state manager column sizes for tokens
* https://github.com/quarkusio/quarkus/pull/51743[#51743] - Allow to select OIDC client for individual dynamic GraphQL clients
* https://github.com/quarkusio/quarkus/pull/51679[#51679] - Allow to assign a user and roles to a scheduled task
* https://github.com/quarkusio/quarkus/pull/51799[#51799] - Add support for OAuth 2.0 Pushed Authorization Requests to OIDC extension

=== Maven 3.9 required

Maven 3.9 is now required to build Quarkus applications.

=== Headless AWT on Windows for native images

We added support for headless AWT on Windows for native images to our AWT extension.

=== I18N for Dev UI

The Dev UI is now internationalized.

Contributions are welcome to improve the translations and add new languages.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.31.0.CR1[3.31.0.CR1], https://github.com/quarkusio/quarkus/releases/tag/3.31.0[3.31.0], and https://github.com/quarkusio/quarkus/releases/tag/3.31.1[3.31.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1153 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.31 release, thanks to Ales Justin, Alexandre Dutra, Alexey Loubyansky, Andrea Boriero, Andy Damevin, Anis Da Silva Campos, Aurea Munoz, Aurélien Pupier, Bastian, Brian Setz, Bruno Baptista, cfitzw, Chihiro Ito, Chris Laprun, Christian Pieczewski, Clement Escoffier, dancer13, David M. Lloyd, Dione de Souza Silva, Evgeny Potapov, Fedor Dudinsky, Foivos Zakkak, Fouad Almalki, Francesco Nigro, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Jakub Pietrzak, James Netherton, Jan Martiska, Jan Schatteman, Jeff Mesnil, Jens Teglhus Møller, Jiri Ondrusek, Julien Ponge, Karm Michal Babacek, Katia Aresti, Ladislav Thon, Lars, Lars Andringa, lloydmeta, Luca Molteni, Lucas, Lucas Pottersky, Lukas Lowinger, Maciej Lisowski, Marco Belladelli, Marco Sappé Griot, mariofusco, marko-bekhta, Martin Bartoš, Martin Kouba, Martin Ocenas, Martin Panzer, Matheus Cruz, matthaios.stavrou, Melloware, Michael Edgar, Michal Vavřík, Nicolo Pietro Belcastro, Olivier V, Ozan Gunalp, Phillip Krüger, Quark, Roberto Cortez, Rolf Thorup, Rolfe Dlugy-Hegwer, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Severin Gehwolf, shjones, sNiXx, staillebois, Stefan Oehme, Steve Hawkins, Stéphane Épardaud, Teymur Babayev, Thomas Segismont, Thorsten Meinl, Victor Dalosto, Wei Huang, Willem Jan Glerum, xstefank, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
