---
layout: post
title: 'Quarkus 3.39.2, 3.33.3.2 LTS, 3.27.5.2 LTS - Maintenance releases'
date: 2026-09-07
tags: release
synopsis: 'We released Quarkus 3.39.2, a regular maintenance release.'
author: gsmet
---

Today, we released Quarkus 3.39.2, a maintenance release for our 3.39 release train.

This release fixes the following CVEs:

- https://nvd.nist.gov/vuln/detail/CVE-2026-12894[CVE-2026-12894]
- https://nvd.nist.gov/vuln/detail/CVE-2026-17615[CVE-2026-17615]
- https://nvd.nist.gov/vuln/detail/CVE-2026-19625[CVE-2026-19625]
- https://nvd.nist.gov/vuln/detail/CVE-2026-19651[CVE-2026-19651]
- https://nvd.nist.gov/vuln/detail/CVE-2026-76763[CVE-2026-76763]

This release also contains bugfixes and documentation improvements.
It should be a safe upgrade for anyone already using 3.39.

We also released 3.33.3.2 LTS and 3.27.5.2 LTS to fix these CVEs in the LTS branches.

== Update

To update to Quarkus 3.39, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.39.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.39[Quarkus 3.39 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.39.2[3.39.2] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
