---
layout: post
title: 'Quarkus 3.40 LTS - new LTS version'
date: 2026-09-30
tags: release lts
synopsis: 'We released Quarkus 3.40 LTS, our new LTS version.'
author: gsmet
---

It is our pleasure to announce the release of Quarkus 3.40, which is our new LTS (Long Term Support) version.

This version is built on the top of Quarkus 3.39.
We are also hard at work on the first Beta for Quarkus 4, stay tuned!

If you want to know more about our LTS policy, the https://quarkus.io/blog/lts-releases/[LTS announcement] is a must read.

LTS releases are supported for 12 months.

If you are coming from the previous LTS, Quarkus 3.33 LTS, there are a lot of exciting new features and we recommend reading the following announcements:

- https://quarkus.io/blog/quarkus-3-34-released/[Quarkus 3.34 - Enhancements all around]
- https://quarkus.io/blog/quarkus-3-35-released/[Quarkus 3.35 - JAR tree-shaking, PGO for native, Semeru AOT, @Transactional for Hibernate Reactive, and more]
- https://quarkus.io/blog/quarkus-3-36-released/[Quarkus 3.36 - Quarkus Signals, embedded SBOMs, OIDC SPIFFE authentication, and more]
- https://quarkus.io/blog/quarkus-3-37-released/[Quarkus 3.37 - Extension-based modularity, Hibernate ORM 7.4, Jackson reflection-free serializers, and more]
- https://quarkus.io/blog/quarkus-3-38-released/[Quarkus 3.38 - Weight-based eviction for Hibernate second level Caffeine cache, and more]
- https://quarkus.io/blog/quarkus-3-39-released/[Quarkus 3.39 - Post-quantum cryptography support in TLS registry]

== Update

To update to Quarkus 3.40 LTS, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.40 LTS.

If you are upgrading from 3.39, there's nothing to do as 3.40 LTS is the direct continuation of 3.39.

If you are upgrading from the previous LTS, Quarkus 3.33 LTS, please refer to the following migration guides:

- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.34[Migration guide for 3.34]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.35[Migration guide for 3.35]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.36[Migration guide for 3.36]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.37[Migration guide for 3.37]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.38[Migration guide for 3.38]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.39[Migration guide for 3.39]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.40[Migration guide for 3.40] - this one is empty as 3.40 is the continuation of 3.39

Note that `quarkus update` should handle most of the heavy lifting for you,
but there are still cases that should be handled manually and we recommend reading these migration guides carefully.

== What's new?

=== Platform component upgrades

Various Platform components were upgraded including:

- Camel Quarkus to 3.40.0
- Quarkus CXF to 3.40.0
- Quarkus LangChain4j to 1.13.3
- Quarkus MCP Server to 2.0.1
- Quarkus Amazon Services to 3.22.1
- Debezium to 3.6.3.Final
- Quarkus Google Cloud Services to 2.24.0
- Quarkus Operator SDK to 7.8.0
- Quarkus Vault to 4.10.0
- Quarkus Qpid JMS to 2.14.0

Also worth mentioning, https://www.jobrunr.io/en/blog/v9-release/[JobRunr 9] was released with day-one support for Quarkus 3.40 LTS. Great to see the ecosystem keeping up!

== Full changelog

The core part of Quarkus 3.40 LTS is based on Quarkus 3.39 with some additional fixes included in 3.40.1.

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.40.1[3.40.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1250 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.40 release, thanks to aarti-1108, Adam Kiss, Adrian Pauli, Ahmed El amraouiyine, Ales Justin, Alex Martel, Alexander Schwartz, Alexandre Dutra, Alexey Loubyansky, amirdeljouyi, Andreas Maechler, andreatp, Andy Damevin, anuragg-saxenaa, Arend von Reinersdorff, Arnab Nandy, Arseni Buinitski, Arthur Navarro, Asger Askov Blekinge, Ashish Thakur, Atharv Hatwar, Aurea Munoz, Aurélien Pupier, Ben Rose, Beutlin, Bruno Baptista, Carles Arnal, Cesar M. Romero-Pedraza, cfitzw, Char, Charles Moulliard, Chintu Kumar, Chris Laprun, Chris Ruffalo, Christian Navolskyi, Clement Escoffier, Clément de Tastes, cnbehr, Cristiano Nicolai, Daan Hoogenboezem, Daniel Vergien, David Kjerrumgaard, David M. Lloyd, Davide D'Alto, Dennis Kniep, DerFrZocker, Dmitri Bourlatchkov, Domenico Briganti, Dorothy Cheng, Enoque Duarte, Eric Deandrea, Erwin Oegema, Faisal Dilawar, Finn Petersen, Foivos Zakkak, Foobartender, Fouad Almalki, Francesco Nigro, Frank Eichfelder, Frody, Gaelle Fournier, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, Gorre Surya, Guillaume Smet, Holly Cummins, Inaki Villar, Jakub Jedlicka, Jamal Dabari, James R. Perkins, Jan Martiska, Jan Schatteman, jcarranzan, JeffersonSantos29, Jens Teglhus Møller, Jesse White, Jiri Ondrusek, jnbdz, Julien Ponge, Kamil Krzywanski, Karm Michal Babacek, Katia Aresti, Keshav Deshpande, Kristian Rickert, kyooosukedn, Ladislav Thon, Laurent Goujon, lberrymage, lloydmeta, loiclefevre, lu1tr0n, Luca Molteni, Lucien Reboul, Lukas Lowinger, luneo7, Marco Belladelli, Marco Sappe Griot, Marek Skacelik, mariofusco, marko-bekhta, Martin Kouba, Martin Panzer, María Arias de Reyna Domínguez, Matej Novotny, Matej Vašek, Matheus André, Matheus Cruz, Matheus Oliveira, Matthias Keckl, Max Rydahl Andersen, Maximilian Zellhofer, MdTanwer, Melloware, Michael Edgar, Michael Hertel, Michal Maléř, Michal Vavřík, Mihajlo Veljković, Mohammedthowfiq, Mora, Moritz Heine, mrchatam, Nick Robison, Nico Hinrichs, Nikolas Schmidt-Voigt, Ozan Gunalp, Ozzy Osborne, pandareen, Pantazis Vouzaxakis, Paramvir Jindal, Patrick Schaub, Paulo Casaes, Peter Levart, Peter Zaoral, Phillip Krüger, PrabinDevkota, PreetiYadav, PulkitBxtra, Robert Stupp, Robert Toyonaga, Roberto Cortez, Rolfe Dlugy-Hegwer, Roman Huber, Rostislav Svoboda, Ruslan Ibrahimau, Sakshi Chitnis, Samuel Ferreira, Sanne Grinovero, SAY-5, Sergey Beryozkin, Severin Gehwolf, Sheila Jones, Shivam Srivastav, Simon Scatton, Simon Scholz, Simon Wick, simrankhanna, Steve Hawkins, Ståle Pedersen, Stéphane Épardaud, Sven Zbinden, Tamas Cservenak, tanw9004167, Teymur Babayev, Thomas McWork, Thomas Segismont, Timur Rakhmatullin, tiwari91, Tiziano Basile, Tom Fenwick, Tom Jenkinson, Tom Schindl, Vaibhav Srivastava, Victor Queiroz, Vincent Sevel, Vishal Kumar Singh, Vojin Jovanovic, Václav Muzikář, Willem Jan Glerum, xstefank, Yoann Rodière, Yoshikazu Nojima, and Zahanturel.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
