quarkus.asciidoc.attributes."!showtitle"=true
quarkus.asciidoc.attributes.add-copy-button-to-config-props=true
quarkus.asciidoc.attributes.add-copy-button-to-env-var=true
quarkus.asciidoc.attributes.icons=font
quarkus.asciidoc.attributes.source-highlighter=highlightjs
quarkus.qute.alt-expr-syntax=true
quarkus.qute.property-not-found-strategy=NOOP
quarkus.qute.strict-rendering=false
quarkus.qute.type-check-excludes=java.lang.Object.*,io.quarkiverse.roq.frontmatter.runtime.model.Page.paginator,io.quarkiverse.roq.frontmatter.runtime.model.Page.tags,io.quarkiverse.roq.frontmatter.runtime.model.Page.tagsCount,io.quarkiverse.roq.frontmatter.runtime.model.DocumentPage.*
quarkus.web-bundler.bundling.external=/assets/*
site.collections.author.from-data.id-key=_key
site.collections.author.from-data.name=authors
site.collections.author.layout=author
site.collections.guides=true
site.collections.guides.layout=guides
site.collections.guides.link=/guides/:name
site.collections.posts.link=/blog/:name/
site.collections.redirects=true
site.collections.redirects.layout=redirect
site.collections.versions=true
site.collections.versions.layout=guides
site.collections.versions.link=/version/:dir[1]/:name
site.date-format=yyyy-MM-dd['T'HH:mm:ss][X]
site.escaped-pages=guides/**,versions/**
site.url=https://quarkus.io
quarkusio.search.script-mode=cached
quarkusio.search.host=https://search.quarkus.io
quarkusio.search.script-path=/static/bundle/app.js
quarkusio.search.cached-script-file=assets/javascript/search-wc.js
quarkusio.search.initial-timeout=1500
quarkusio.search.more-timeout=2500
quarkusio.search.min-chars=2
%dev.quarkusio.search.script-mode=direct
%dev.quarkusio.search.host=https://search-quarkus-io-dev-search-quarkus-io.apps.ospo-osci.z3b1.p1.openshiftapps.com
quarkus.roq.tagging.lowercase=true
quarkus.roq.data.dir=_data
quarkus.roq.generator.timeout=600
