<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.quarkiverse.roq</groupId>
        <artifactId>quarkus-roq-plugin-toc-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>quarkus-roq-plugin-toc-deployment</artifactId>
    <name>Quarkus Roq - Plugin - Toc - Deployment</name>

    <dependencies>
        <dependency>
            <groupId>io.quarkiverse.roq</groupId>
            <artifactId>quarkus-roq-frontmatter-deployment</artifactId>
            <version>${roq.version}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.roq</groupId>
            <artifactId>quarkus-roq-plugin-toc</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-extension-processor</artifactId>
                            <version>${quarkus.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
