---
layout: post
title: 'Quarkus 1.0.0.CR2 released - Last stop before Final'
date: 2019-11-20
tags: release
synopsis: We just released Quarkus 1.0.0.CR2 which is our last candidate release before Final. We plan to release Final on Monday 25th.
author: gsmet
---

We have been busy bees fixing the reported issues, improving the documentation and the global developer experience. And we felt that a second candidate release was in order due to some of the changes we made.

**Please, update your applications as soon as possible and, if you encounter any issues, report them quickly so that we can fix them before the Final.**

We plan to release 1.0.0.Final in just a few days on **Monday 25th**.

== What's new?

Well, it's mostly bugfixes and documentation improvements all over the place. Nothing really major here.

You can get https://github.com/quarkusio/quarkus/releases/tag/1.0.0.CR2[the full changelog of 1.0.0.CR2 on GitHub].

== Contributors

Quarkus has now https://github.com/quarkusio/quarkus/graphs/contributors[185 contributors].
Many many thanks to each and everyone of them.

In particular for the CR1 and CR2 releases, thanks to Alessio Soldano, Alex Kochnev, Alexey Loubyansky, Anamarija Talijanac, Andrew Guibert, Clement Escoffier, Emmanuel Bernard, Erin Schnabel, Fabian Martinez, Fabio Heer, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Hantsy Bai, Jaikiran Pai, Jan Martiska, John O'Hara, John Oliver, Ken Finnigan, Logan Hauspie, Maciej Swiderski, Manyanda Chitimbo, Marcin Czeczko, Martin Kouba, Matej Novotny, Max Rydahl Andersen, Michael Musgrove, Michal Szynkiewicz, Moncef Aoudia, Ondra Chaloupka, Pedro Igor, Rostislav Svoboda, Sanne Grinovero, Sebastien Blanc, Sergey Beryozkin, Stephane Epardaud, Stuart Douglas, Tiago Dolphine, Timothy Power, William Burns and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

