---
layout: post
title: 'Quarkus 1.8.3.Final released - Bugfixes'
date: 2020-10-09
tags: release
synopsis: 1.8.3.Final downgrades slf4j-jboss-logging to fix a regression.
author: gsmet
---

Today, we released Quarkus 1.8.3.Final which contains a fix for an annoying regression and some other fixes.

It is a safe upgrade for everyone using Quarkus 1.8.

== What's new?

This release is a maintenance release that fixes various bugs found in 1.8.2.Final and provides some documentation updates.

The main change we made is a downgrade of `slf4j-jboss-logging` motivated by a regression in `slf4j-jboss-logging`: https://github.com/quarkusio/quarkus/issues/12615 .

You can get https://github.com/quarkusio/quarkus/releases/tag/1.8.3.Final[the full changelog of 1.8.3.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

