---
layout: post
title: 'Quarkus 1.5 released - fast-jar packaging format, Picocli, gRPC, GraphQL and more'
date: 2020-06-03
tags: release
synopsis: Quarkus 1.5 adds support for Picocli, gRPC, GraphQL and introduces more Amazon Services extensions. It also includes a new fast-jar packaging format.
author: gsmet
---

Quarkus 1.5.0.Final is finally here with all sorts of bells and whistles:

 * New fast-jar packaging format
 * Picocli extension
 * gRPC extension
 * Eclipse MicroProfile GraphQL extension
 * Amazon Services extensions
 * Hibernate ORM REST Data with Panache extension
 * Spring Cache compatibility layer

It also includes a lot of bugfixes and small improvements all over the place.

== Migration Guide

Eager to migrate your existing applications? Here is https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.5[our migration guide for 1.5].

== What's new?

=== Fast-jar packaging format

The fast-jar packaging format is introduced as an alternative to the default jar packaging format.
The main goal of this new format is to bring faster startup times.

It is very likely that future versions will adopt this format as the default so your feedback is highly welcome on real life applications.

You can test it by adding the following lines to your `application.properties`:

[source, properties]
----
quarkus.package.type=fast-jar
----

or passing `-Dquarkus.package.type=fast-jar` when you build.

=== New extensions

==== Picocli

1.4 introduced command mode and we now have a Picocli extension relying on it to simplify the creation of rich command line applications.

Eager to learn more about it? Read the link:/guides/picocli[Picocli guide].

==== gRPC

gRPC support in Quarkus was a popular request: we now have a set of gRPC extensions that allows to write clients and servers:

 * link:/guides/grpc-getting-started[Getting started with gRPC]
 * link:/guides/grpc-service-implementation[Implementing a gRPC Service]
 * link:/guides/grpc-service-consumption[Consuming a gRPC Service]

==== MicroProfile GraphQL

Speaking of popular requests, Quarkus 1.5 introduces a GraphQL extension implementing Eclipse MicroProfile GraphQL.

How to create and consume GraphQL services is explained in details in the link:/guides/microprofile-graphql[MicroProfile GraphQL guide].

==== Amazon Services

We had Amazon DynamoDB support for quite a while, this has been generalized to support more Amazon services:

 * link:/guides/amazon-dynamodb[Amazon DynamoDB] - NoSQL database
 * link:/guides/amazon-kms[Amazon KMS] - Key Management Service
 * link:/guides/amazon-s3[Amazon S3] - Object storage service
 * link:/guides/amazon-ses[Amazon SES] - Email service
 * link:/guides/amazon-sns[Amazon SNS] - Notification service
 * link:/guides/amazon-sqs[Amazon SQS] - Queue service

==== Hibernate ORM REST Data with Panache

The purpose of the `with Panache` extensions is to simplify a set of features and bring back developer joy.

In Quarkus 1.5, we introduce Hibernate ORM REST Data with Panache which simplifies the creation of CRUD REST APIs based on JAX-RS and Hibernate ORM.

Discover this feature with link:/guides/rest-data-panache[this new dedicated guide].

==== Spring Cache annotations

Our Spring compatibility layer has one more feature: the support of the Spring Cache extensions.

We do not support every feature but you will be able to use most of them backed by the preexisting Cache extension based on Caffeine.

==== Blaze Persistence

An extension for Blaze Persistence is now available in the Quarkus Platform.

A guide is coming soon.

=== Important adjustments in existing extensions

==== Hibernate ORM

The Hibernate ORM extension now supports multitenancy.
Refer to our link:/guides/hibernate-orm#multitenancy[Hibernate ORM guide] to learn more about it.

==== Agroal

The Agroal extension includes support for external pooling solutions e.g. pgagroal or Pgpool.

=== Full changelog

You can get the full changelogs of https://github.com/quarkusio/quarkus/releases/tag/1.5.0.CR1[1.5.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/1.5.0.Final[1.5.0.Final] on GitHub.

== ADOPTERS.md

To share stories about Quarkus usage, we added https://github.com/quarkusio/quarkus/blob/master/ADOPTERS.md[an `ADOPTERS.md` file] at the root of the repository.

If you are using Quarkus and would like to be interviewed on our blog or simply added to this file, please contact us and we will be happy to oblige.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[290 contributors].
Many many thanks to each and everyone of them.

In particular for the 1.5 release, thanks to Aaron Rogers, Adrian Fiedler, Akito Kidani, Alex Soto, Alexey Loubyansky, Andrea Cosentino, Anh Le (Andy), Aurea Munoz, Luis Barreiro, Bill Burke, bobbyphilip, Bogdan Sukonnov, Cem Nura, Chris Laprun, Christoffer Rumohr, Christopher Chianelli, Claus Ibsen, Clement Escoffier, Daniel Petisme, David M. Lloyd, Dennis Baerten, Diogo Carleto, Diogo Quintela, Emmanuel Bernard, Erin Schnabel, Falko Modler, Ferran Puig, Galder Zamarreño, Geoffrey De Smet, George Gastaldi, George Sapountzis, Georgios Andrianakis, Greg. A, Guillaume Le Floch, Guillaume Nodet, Guillaume Smet, Gwenneg Lepage, Gytis Trikleris, Harald Reinmueller, Harsha R, Ioannis Canellos, Irena Kezic, Jacob Middag, Jaikiran Pai, Jan Martiska, Jan Martiška, Jason T. Greene, John O'Hara, Julian Cui, Justin Lee, Ken Finnigan, Ladislav Thon, Lovekesh Garg, Loïc Mathieu, Luka Lodrant, Manyanda Chitimbo, Marat Gubaidullin, Marcin Czeczko, Mario Fusco, Martin Kouba, Martin Panzer, Matthias Andreas Benkard, Matthias Harter, Mattia, Max Rydahl Andersen, Michael Schnell, Michal Szynkiewicz, Michał Górniewski, mklueh90, Oscar, oscarfh, Paul K Moore, Pavel.Vervenko, Pedro Igor, penehyba, Peter Palaga, Phillip Kruger, Robert Marcano, Romain Quinio, Rostislav Svoboda, Ruben R, Sanne Grinovero, schulzp, Sergey Beryozkin, ShubhamRwt, Stef Klaassen, Stephane Epardaud, Stuart Douglas, Stéphane Épardaud, Survi, Thomas Segismont, tibordigana, Timothy Power, Vincent Sevel and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
