---
layout: post
title: 'Quarkus 1.5.2.Final released - Bugfixes'
date: 2020-06-18
tags: release
synopsis: 1.5.2.Final fixes some regressions and bugs. 
author: gsmet
---

Today, we released Quarkus 1.5.2.Final with some bugfixes and documentation improvements.

It is a safe upgrade for everyone using 1.5.0.Final or 1.5.1.Final.

== What's new?

We fixed two important regressions:

 * The IDE launcher is back on track.
 * In 1.5, we tweaked how the Hibernate ORM Panache enhancement works and that might cause some issues when used in conjunction with the JPA modelgen annotation processor.
   We documented how to properly configure the annotation processors in link:/guides/hibernate-orm-panache#defining-entities-in-external-projects-or-jars[Hibernate ORM with Panache guide].

You can get https://github.com/quarkusio/quarkus/releases/tag/1.5.2.Final[the full changelog of 1.5.2.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

