---
layout: post
title: 'Quarkus 1.8.1.Final released - Bugfixes, RESTEasy Multipart extension'
date: 2020-09-18
tags: release
synopsis: 1.8.1.Final fixes some regressions and bugs and introduces the RESTEasy Multipart extension.
author: gsmet
---

Today, we released Quarkus 1.8.1.Final with some bugfixes and documentation improvements.

We also introduced a new RESTEasy Multipart extension to fix an recurring encoding issues with multipart.

It is a safe upgrade for everyone using 1.8.0.Final.

== What's new?

This release is a maintenance release that fixes various bugs found in 1.8.0.Final and provides some documentation updates.

You can get https://github.com/quarkusio/quarkus/releases/tag/1.8.1.Final[the full changelog of 1.8.1.Final on GitHub].

=== RESTEasy Multipart

The default encoding for multipart requests in RESTEasy is US-ASCII which is not very convenient in 2020.

Thanks to the `quarkus-resteasy-multipart` extension, the default encoding is now UTF-8 and it can be configured if needed.
If working with multipart, make sure you use this extension.

More on this in the link:/guides/rest-json#multipart-support[Writing JSON REST Services guide].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

