---
layout: post
title: 'Quarkus 1.13.5.Final released - Maintenance release'
date: 2021-05-26
tags: release
synopsis: 1.13.5.Final is a maintenance release for our 1.13 release train.
author: gsmet
---

We released 1.13.5.Final today with a new set of bugfixes for our 1.13 release.

1.13.5.Final is a safe upgrade for everyone using Quarkus 1.13.

If you are not using 1.13 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.13[1.13 migration guide].

== What's new?

=== Maven 3.8.1

Given there are a couple of CVEs in Maven 3.6, we upgraded the Maven version included in the generated projects to 3.8.1 (the one from the Maven wrapper).

We also upgraded our Maven internal dependencies to 3.8.1.

You can still use Maven 3.6 if you are so inclined.

=== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/1.13.5.Final[the full changelog of 1.13.5.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

