---
layout: post
title: 'Quarkus 2.0.0.Alpha2 released - Continuous Testing improvements'
date: 2021-05-06
tags: release
synopsis: Thanks to the community feedback, this new Alpha comes with a lot of bugfixes and improvements, especially for Continuous Testing.
author: gsmet
---

We just released our second Alpha for Quarkus 2.0.

We had a lot of feedback and Continuous Testing got a lot of fixes and improvements.

Please keep the feedback coming!

If you have missed our Alpha1 announcement: here are link:/blog/quarkus-2-0-0-alpha1-released/[the main new features of Quarkus 2.0].

== Migration Guide

We will keep the Migration Guide up to date here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0.

== Documentation

For now, the documentation for our `main` branch is not available on the website yet.
It will be available soon.

== What's new?

=== Continuous Testing

The most visible being a far improvement integration in the Dev UI.

Another notable one is the addition of `quarkus.test.type` which can be used to define which tests are run in continuous testing, `unit`, `quarkus-test` or `all`.

=== Full Changelog

You can get the full changelogs of https://github.com/quarkusio/quarkus/releases/tag/2.0.0.Alpha2[2.0.0.Alpha2] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
