---
layout: post
title: 'Quarkus 2.6.1.Final released - Maintenance release'
date: 2021-12-24
tags: release
synopsis: 2.6.1.Final is the first maintenance release for our 2.6 release train and the last Quarkus release of the year!
author: gsmet
---

2021 has been a tremendous year for Quarkus and today we officially close our 2021 release season with the last maintenance release of the year:
2.6.1.Final is available on Maven Central and ready for consumption!

It is a safe upgrade for anyone already using 2.6 and contains dozens of small bugfixes, tweaks and documentation improvements.

Thank you all for taking the time to report issues, build reproducers... it is immensely helpful and instrumental in making Quarkus better every day.

Have a nice holiday break if you take one, and happy coding/experimenting if you don't, and see you all next year.

== Full changelog

If you are not using 2.6 already, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6[2.6 migration guide].

You can get https://github.com/quarkusio/quarkus/releases/tag/2.6.1.Final[the full changelog of 2.6.1.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].

