---
layout: post
title: 'Quarkus 2.7.0.Final released - Quarkus CLI maturing, Interactive terminal, Oracle Reactive SQL Client...'
date: 2022-02-02
tags: release
synopsis: 'Quarkus 2.7.0.Final comes with an even better Quarkus CLI, an interactive terminal for dev mode, SmallRye Stork 1.0.0, an Oracle Reactive SQL Client extension and a ton of other things.'
author: gsmet
---

`2-2-2022` would have been a perfect day to release a 2.2.2.Final version of Quarkus but we didn't get that lucky.
Today we announce the release of *Quarkus 2.7.0.Final*.

2.7.0.Final comes with a lot of refinements and new features:

* Lots of improvements for the Quarkus CLI, that has now been published to Homebrew, SDMAN!...
* An interactive terminal for dev mode
* SmallRye Stork 1.0.0
* An Oracle Reactive SQL Client extension
* Kotlin serialization support for RESTEasy Reactive
* Hibernate Search 6.1
* `mongo+srv://` support in native executables

And much more!

== Migration Guide

To migrate from 2.6, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7[our migration guide].

== What's new?

=== Quarkus CLI

The Quarkus CLI is maturing and we are now publishing it in more places:

* Homebrew
* JBang
* SDKMAN!

More will come soon.

For all the instructions to install the Quarkus CLI, please refer to the https://quarkus.io/guides/cli-tooling[dedicated guide].

We have also started to refine our documentation with instructions for the CLI, Maven and Gradle.
This is a work in progress so not all guides are updated, it will get to completion in the following weeks.

If you make use of the CLI, please provide us your feedback either in https://github.com/quarkusio/quarkus/issues[our tracker] or in https://github.com/quarkusio/quarkus/issues[the discussions area].

Slightly related, you can now define the Java version you want to use in your generated projects.
For instance with:

* `--java=17` for the CLI
* `-DjavaVersion="17"` for Maven

=== Interactive terminal

Dev mode now comes with an interactive terminal.
Press `:` when in dev mode to open it.

This feature is very extensible so if you have ideas to enhance it, don't hesitate to open feature (or pull) requests.

=== Native Reference Guide

We don't generally add a release note entry for new guides but this one is well worth it.
If you want to understand better how native executables are built and how you can work with them, read link:/guides/native-reference[our new Native Reference Guide].

=== SmallRye Stork

SmallRye Stork, our service discovery and client-side load-balancing framework has been bumped to 1.0.0.
It comes with many improvements and a refined documentation:

* link:/guides/stork[The Stork guide]
* link:/guides/stork-reference[The Stork Reference]

=== OpenId Connect

We simplified the configuration for well-known OIDC providers such as GitHub, Google, Apple...
More information can be found in link:/guides/security-openid-connect-web-authentication[the guide].

=== Hibernate ORM

`quarkus.hibernate-orm.database.default-catalog` and `quarkus.hibernate-orm.database.default-schema` can now be set at runtime (they were fixed at build time until now).

=== Hibernate Search

The Hibernate Search extension now uses Hibernate Search 6.1:

* Hibernate Search is now tested to work up to and including Elasticsearch 7.16
* Hibernate Search is now able to work with OpenSearch 1.0 to 1.2, with https://quarkus.io/guides/hibernate-search-orm-elasticsearch#opensearch[just a single change in your configuration properties].
* Hibernate Search can now push entity change events to an outbox table in the database and coordinate between multiple instances of the application to process these events and reindex entities. This opt-in, **preview** feature allows for safer concurrent index updates with lower overhead on commit. Learn more in link:/guides/hibernate-search-orm-elasticsearch#coordination[this section of the guide].
* Hibernate Search 6.1 also includes many smaller improvements, such as new search predicates or the ability to provide Elasticsearch index settings or mappings as JSON; see https://hibernate.org/search/releases/6.1/[the official Hibernate Search 6.1 webpage] for more details.

=== MongoDB

We added experimental support for `mongo+srv://` in native executables (it was only working in JVM mode pre-2.7).

=== Reactive REST Client

The Reactive REST Client now supports proxy authentication and global proxy settings.

=== Oracle Reactive SQL Client

Until now, we were only supporting Oracle with JDBC.
2.7 introduces a new reactive SQL client for Oracle.

=== Kotlin serialization

Support for Kotlin serialization has been added to RESTEasy Reactive.

=== Cache

Metrics for the Cache extension are now recorded with Micrometer.

=== JNDI disabled by default

Except when an extension actually requires it to function properly, we are now disabling JNDI by default.

=== Containers

* The image chosen for JIB now depends on the Java version you target.
* We have a new extension for buildpacks: `quarkus-container-image-buildpack`.

=== Where is Kogito?

Due to some infra issues, the Kogito extensions are not part of the 2.7.0.Final.
If you are using Kogito, stay on 2.6.3.Final until we release Quarkus 2.7.1.Final, which will bring back the Kogito extensions.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[586 contributors].
Many many thanks to each and everyone of them.

In particular for the 2.7 release, thanks to adrien, Alexey Loubyansky, andreaTP, Andres Almiray, Apostolos Samaras, Ashwin S. Nair, BarDweller, Bill Burke, Carles Arnal, Christian Beikov, Christoph Hermann, Clement Escoffier, Daniel Petisme, danielmast, Davide, Dennis Kieselhorst, Digant Bhavsar, Duy Pham, Elias Norrby, Emmanuel Bernard, Erin Schnabel, Falko Modler, Foivos Zakkak, Freeman Fang, Fu Cheng, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, Guillaume Le Floch, Guillaume Smet, Gunnar Morling, Gwenneg Lepage, Hendrik S, Ioannis Canellos, Jacob Middag, Jacopo Rota, James Cobb, James Netherton, Jan Martiška, Jason Porter, Jorge Solórzano, Jose, Josh Purcell, Julien Ponge, Justin Lee, Jérôme TAMA, Katherine Stanley, Katia Aresti, Kevin Wooten, Ladislav Thon, Loïc Mathieu, Marc Nuri, Marc Schlegel, Markus Schwer, Martin Kouba, Martin Panzer, Matej Vasek, Max Rydahl Andersen, Michal Karm Babacek, Michał Szynkiewicz, Mike Weber, Ozan Gunalp, pablo gonzalez granados, Patryk Najda, Paul Robinson, Paulo Casaes, Phillip Kruger, Ricardo Rodrigues, Roberto Cortez, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Stefan Schoeffmann, Stephane Epardaud, Stuart Douglas, Summers Pittman, Sébastien CROCQUESEL, Thomas Segismont, Tomas Hofman, Vincent Sevel, Frank Wippermueller, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
