---
layout: post
title: 'Quarkus 2.15.0.Final released - AWS Lambda SnapStart, new gRPC extension, and a lot more'
date: 2022-12-14
tags: release
synopsis: 'We released Quarkus 2.15.0.Final which introduces a lot of new features such as support for AWS Lambda SnapStart, a new Vert.x-based gRPC extension, federation support for SmallRye GraphQL...'
author: gsmet
---

It is our pleasure to announce the release of Quarkus 2.15.0.Final, the last minor release of 2022.

As usual, it comes with bugfixes and small enhancements all over the place together with more important changes:

  * Support for AWS Lambda SnapStart
  * Move gRPC extension to new Vert.x gRPC implementation
  * Federation support for SmallRye GraphQL
  * Redis - Implement the search group
  * Add `@ClientQueryParam` to Reactive REST Client
  * Support filtering by named queries in REST Data with Panache extension
  * Support for OIDC FrontChannel logout
  * Hibernate ORM - IN clause parameter padding
  * Support continuous testing in CLI test command
  * Introduce image build / push commands
  * Use -XX:ArchiveClassesAtExit for AppCDS creation in Java 17+
  * Add Dev Services for Kubernetes
  * Google Cloud Functions test framework

We also spent some time polishing our documentation as is the custom.

== Migration Guide

To migrate from 2.14, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.15[our migration guide].

== What's new?

=== Support for AWS Lambda SnapStart

Quarkus 2.15 brings support for https://aws.amazon.com/blogs/aws/new-accelerate-your-lambda-functions-with-lambda-snapstart/[AWS Lambda SnapStart].

This has already been announced in details in https://quarkus.io/blog/quarkus-support-for-aws-lambda-snapstart/[a previous blog post].

See https://quarkus.io/guides/amazon-snapstart[the dedicated guide] for more information about how to use AWS Lambda SnapStart with Quarkus.

=== New gRPC implementation

The gRPC extension has been rewritten to use a new Vert.x-based gRPC implementation.

Moreover `@InjectMock` is now working for gRPC Mutiny clients.

=== Federation support for SmallRye GraphQL

The SmallRye GraphQL extension now supports enhancing your GraphQL API with metadata needed to be able to expose it via a Apollo Federation gateway.
This is achieved via annotations in the `io.smallrye.graphql.api.federation` package.
See https://www.apollographql.com/docs/federation/ for general information about Federation or https://smallrye.io/smallrye-graphql/2.0.0/federation/ for an example.

=== Redis - Search group

Since the introduction of the new Redis extension, a lot of new commands were added from version to version.

It is now commands for the search group which makes its apparition in Quarkus.

=== `@ClientQueryParam` for Reactive REST Client

Using the Reactive REST Client, it is possible to add query parameters to a request with the `@ClientQueryParam` annotation.

It is described in details in https://quarkus.io/guides/rest-client-reactive#using-clientqueryparam[the Reactive REST Client guide].

=== Filtering by named queries in REST Data with Panache extension

Filtering by named queries has been added to the REST Data with Panache extension.

You can find more information about it in https://quarkus.io/guides/rest-data-panache#complex-filtering-to-list-entities-using-namedquery[the REST Data with Panache guide].

=== OIDC FrontChannel logout

The OIDC extension adds support for OIDC FrontChannel logout.

=== Hibernate ORM - IN clause parameter padding enabled by default

Quarkus 2.15 adds the `quarkus.hibernate-orm.query.in-clause-parameter-padding` configuration property to the Hibernate ORM extension,
and enables it by default.

It improves the caching of queries containing IN clauses.

=== CLI improvements

Two major improvements for the Quarkus CLI in 2.15:

- Continuous testing is available in the Quarkus CLI with the `quarkus test` command.
- Building and pushing images is as simple as `quarkus image build` / `quarkus image push`.

=== -XX:ArchiveClassesAtExit for AppCDS creation

When using Java 17+ to create AppCDS archives, Quarkus automatically enables the `-XX:ArchiveClassesAtExit` option.

=== Dev Services for Kubernetes

Dev Services is one of the Dev Experience features that make Quarkus unique.
Quarkus 2.15 introduces Dev Services for Kubernetes so that you can easily test your applications using the Kubernetes Client extension.

=== Test framework for Google Cloud Functions

The Google Cloud Functions extensions now have a test framework utility in the form of the `quarkus-test-google-cloud-functions` artifact.

You can find more information about it in https://quarkus.io/guides/funqy-gcp-functions#testing-your-function[the Google Cloud Functions guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/2.15.0.CR1[2.15.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/2.15.0.Final[2.15.0.Final] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[728 contributors].
Many many thanks to each and everyone of them.

In particular for the 2.15 release, thanks to Adler Fleurant, Adrian Pauli, Ales Justin, Alexey Loubyansky, Andri Reveli, Andy Damevin, Bill Burke, brunobat, Clement Escoffier, Damon Sutherland, Davide D'Alto, Dmitri Bourlatchkov, Erin Schnabel, Falko Modler, Filippe Spolti, Foivos Zakkak, Fouad Almalki, franz1981, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, glefloch, Guillaume Smet, Gunnar Morling, Harald Albers, Helber Belmiro, Holly Cummins, imperatorx, Ioannis Canellos, Jan Martiska, Jasmin Suljic, Joe Siponen, Jorge Solórzano, Jose Carvajal, Josef Andersson, Julien Ponge, Katia Aresti, kdnakt, Ladislav Thon, Loïc Mathieu, Marcel Lohmann, Marco Bungart, Martin Kouba, Matej Novotny, Max Rydahl Andersen, Michael Musgrove, Michal Karm Babacek, Michal Vavřík, Michelle Purcell, mun711, Ozan Gunalp, Pablo Gonzalez Granados, Paulo Casaes, Radoslaw Adamiak, Roberto Cortez, Rolfe Dlugy-Hegwer, Rostislav Svoboda, Sanne Grinovero, Sergey Beryozkin, Stuart Douglas, Stéphane Épardaud, Sébastien CROCQUESEL, Theodor Mihalache, tom, Vincent Sevel, xstefank, Yoann Rodière, zedbeit, Žiga Deisinger.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
