---
layout: post
title: 'Quarkus 2.16.4.Final released - Maintenance release'
date: 2023-03-06
tags: release
synopsis: 'Quarkus 2.16.4.Final is the fourth maintenance release of our 2.16 release train.'
author: gsmet
---

While we are working hard on finalizing our 3.0 release,
we are still baking maintenance releases for 2.16,
and, today, here comes Quarkus 2.16.4.Final, our fourth maintenance release for the 2.16 release train.

As usual, it contains bugfixes and documentation improvements.

It should be a safe upgrade for anyone already using 2.16.

If you are not already using 2.16, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16[our migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.16.4.Final[the full changelog of 2.16.4.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
