---
layout: post
title: 'Quarkus 2.16.10.Final released - Maintenance release'
date: 2023-08-26
tags: release
synopsis: 'Quarkus 2.16.10.Final is the tenth maintenance release of our 2.16 release train.'
author: gsmet
---

As mentioned in previous blog posts, we encourage all our community users to upgrade to Quarkus 3.
Most of the heavy lifting can be done with https://quarkus.io/guides/update-quarkus[`quarkus update`]
but be aware that some components were updated to new major versions
and that migrating might require some time and careful testing if you are using these components.

We will continue to maintain 2.16.x until the end of October so we recommend that you start your migration process soon.
Today, we released Quarkus 2.16.10.Final, the tenth maintenance release of our 2.16 release train.

The only change is the upgrade of Snappy to fix:

- https://nvd.nist.gov/vuln/detail/CVE-2023-34453[CVE-2023-34453]
- https://nvd.nist.gov/vuln/detail/CVE-2023-34454[CVE-2023-34454]
- https://nvd.nist.gov/vuln/detail/CVE-2023-34455[CVE-2023-34455]

It should be a safe upgrade for anyone already using 2.16.

If you are not already using 2.16, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16[our migration guide].

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/2.16.10.Final[the full changelog of 2.16.10.Final on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
