---
layout: post
title: 'Quarkus 3.4.3 released - Maintenance release'
date: 2023-10-13
tags: release
synopsis: 'We released Quarkus 3.4.3, our second maintenance release for our 3.4 release train.'
author: gsmet
---

Today, we released Quarkus 3.4.3, our second maintenance release for our 3.4 release train (we skipped 3.4.0).

It upgrades Netty to 4.1.100.Final, fixing CVE-2023-44487.
It also includes a bunch of bugfixes, together with documentation improvements.

More releases are planned in the following days/weeks to address the issue in other maintained branches.

== Update

To update to Quarkus 3.4.3, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

To migrate from 3.3, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[our migration guide].

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3] migration guides.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.4.3[the full changelog of 3.4.3 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
