---
layout: post
title: 'Quarkus 3.0.0.Alpha6 released'
date: 2023-03-15
tags: release
synopsis: '3.0.0.Alpha5 came with big changes, 3.0.0.Alpha6 is a smaller release with bugfixes, enhancements, both to Quarkus and our upgrade process.'
author: gsmet
---

A week after Alpha5, we are releasing Quarkus 3.0.0.Alpha6.
While Alpha5 came with major changes such as the upgrade to Hibernate ORM 6,
Alpha6 is a smaller release packed with bugfixes, enhancements,
and improvements to our upgrade process.

== What's new

Among all the bugfixes and enhancements, two are worth mentioning in particular:

  * Enabling OpenTelemetry for JDBC is now as simple as setting `quarkus.datasource.jdbc.telemetry` to `true`
  * ``CredentialsProvider``s are now supported for MongoDB connections

The upgrade progress (presented below) was also improved and it will now:

- Upgrade your Quarkiverse extensions to versions supporting Quarkus 3 (when they are available)
- Replace more deprecated classes and annotations
- Replace some deprecated configuration properties with the new ones

If you encounter issues with this version or the upgrade, please open issues in https://github.com/quarkusio/quarkus/issues[our tracker]!

== Trying out Quarkus 3

For now the easiest way to get started is using https://code.quarkus.io/?S=io.quarkus.platform%3A3.0[code.quarkus.io] or use the Quarkus CLI:

[source,bash]
----
quarkus create app --stream=3.0
----

Mind you that at this stage, while all the core extensions are available, only parts of the Quarkus platform is present. Not all extensions have yet migrated to Jakarta packages (e.g. Camel Quarkus or Kogito are not yet available).

== Upgrading to Quarkus 3

For existing applications where all extensions are available, we have an OpenRewrite recipe that you can try.

There is a one-liner that attempts to do it automatically using a JBang script.

If you have JBang already installed, run:

[source,bash]
----
jbang --fresh upgrade-to-quarkus3@quarkusio
----

If not, for Linux and macOS:

[source,bash]
----
curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio
----

and for Windows:

[source,bash]
----
iex "& { $(iwr https://ps.jbang.dev) } --fresh upgrade-to-quarkus3@quarkusio"
----

Once this has been run your project should have its dependencies, source code and documentation updated to use Quarkus 3.

If it does not work for you, it could be we missed something or you are using extensions not yet supporting Quarkus 3.

https://github.com/quarkusio/quarkus/issues[Let us know] in either case so we can together improve the migration script.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
