---
layout: post
title: 'Quarkus 3.12.3 released - Maintenance release'
date: 2024-07-17
tags: release
synopsis: 'We released Quarkus 3.12.3, our third maintenance release for the 3.12 release train.'
author: gsmet
---

Today, we released Quarkus 3.12.3, our third maintenance release for the 3.12 release train.

This release contains bugfixes and documentation improvements.
It should be a safe upgrade for anyone already using 3.12.

== Update

To update to Quarkus 3.12, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.12.

If you are not already using 3.12, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.12[3.12] migration guide.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.12.3[the full changelog of 3.12.3 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
