---
layout: post
title: 'Quarkus 3.8.3 released - Maintenance release'
date: 2024-03-19
tags: release
synopsis: 'We released Quarkus 3.8.3, our second maintenance release for the 3.8 release train.'
author: gsmet
---

Today, we released Quarkus 3.8.3, our second (we skipped 3.8.0) maintenance release for the 3.8 release train.

This release contains bugfixes and documentation improvements.

It should be a safe upgrade for anyone already using 3.8.

== Update

To update to Quarkus 3.8, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.8.

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[3.4], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5[3.5], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6[3.6], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7[3.7], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.8[3.8] migration guides.

== GraalVM SDK update

In Quarkus 3.8.3, we updated the GraalVM SDK artifacts version to 23.1.2.
It was an oversight and should have been done long ago.

If you are developing extensions containing GraalVM substitutions,
it is highly recommended to replace the `org.graalvm.sdk:graal-sdk` dependency with `org.graalvm.sdk:nativeimage`,
that only contains the classes required to develop substitutions.

Also if you are using the Javascript polyglot features of GraalVM, `org.graalvm.js:js` should be replaced by:

- `org.graalvm.polyglot:js-community` if you are using the community version of GraalVM
- `org.graalvm.polyglot:js` if you are using the enterprise version of GraalVM

While the first change is handled by `quarkus update`, the second one has to be done manually depending on your GraalVM distribution of choice.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.8.3[the full changelog of 3.8.3 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
