---
layout: post
title: 'Quarkus 3.7.2 released - Maintenance release'
date: 2024-02-08
tags: release
synopsis: 'We released Quarkus 3.7.2, our first maintenance release for the 3.7 release train.'
author: gsmet
---

Today, we released Quarkus 3.7.2, our first (we skipped 3.7.0) maintenance release for the 3.7 release train.

This release contains bugfixes and documentation improvements together with an upgrade of Vert.x to fix CVE-2024-1300.

It should be a safe upgrade for anyone already using 3.7.

== Update

To update to Quarkus 3.7, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.7.

To migrate from 3.6, please refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7[our migration guide].

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[3.4], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5[3.5], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6[3.6] migration guides.

== Full changelog

You can get https://github.com/quarkusio/quarkus/releases/tag/3.7.2[the full changelog of 3.7.2 on GitHub].

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
