---
layout: post
title: 'Quarkus 3.11 - Dev Services for Observability, progress on WebSockets.next, Infinispan Cache extension and more'
date: 2024-05-29
tags: release
synopsis: 'We released Quarkus 3.11, which includes Dev Services for Observability, a lot of progress on the WebSockets.next extension, an Infinispan Cache extension, and more.'
author: gsmet
---

It is the end of the month,
a lot of us are in Slovenia for JCon (if you are there, come talk to us!)
and it is time for a Quarkus release:
here comes Quarkus 3.11!

Here are the main changes for this release:

* https://github.com/quarkusio/quarkus/pull/38448[#38448] - Observability extensions - Dev Services, Dev Resources, LGTM
* https://github.com/quarkusio/quarkus/pull/39836[#39836] - Infinispan Cache Extension
* https://github.com/quarkusio/quarkus/pull/40309[#40309] - WebSockets Next: client endpoints
* https://github.com/quarkusio/quarkus/pull/40534[#40534] - WebSockets Next: initial version of security integration
* https://github.com/quarkusio/quarkus/pull/40273[#40273] - Allow quarkus:run to launch Dev Services
* https://github.com/quarkusio/quarkus/pull/40539[#40539] - Support for OIDC session expired page
* https://github.com/quarkusio/quarkus/pull/40600[#40600] - Introduce `OidcRedirectFilter`

== Update

To update to Quarkus 3.11, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.11.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.11[Quarkus 3.11 migration guide].

If you are not already using 3.x, please refer to the https://quarkus.io/blog/quarkus-3-0-final-released/[3.0 announcement] for all the details.
You can also refer to https://quarkus.io/blog/quarkus-3-upgrade/[this blog post] for additional details.
Once you upgraded to 3.0, also have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1[3.1], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2[3.2], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3[3.3], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4[3.4], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5[3.5], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6[3.6], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7[3.7], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.8[3.8], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9[3.9], https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10[3.10], and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.11[3.11] migration guides.

== What's new?

=== Dev extensions for observability

A lot of efforts have been put into simplifying the setup of dev resources for observability.

This includes Dev Services for:

- Grafana
- Jaeger
- OTel
- VictoriaMetrics DB
- VictoriaMetrics Agent / scraper

Actually, they can be used in 3 different contexts:

- Re-usable Dev Services (default)
- Simple start/stop Dev Services
- Single / plain per QuarkusTestResource dev resource

You can find more information about this new feature in this https://quarkus.io/guides/observability-devservices[entry point to more detailed documentation].

=== Infinispan Cache extension

Quarkus has had a cache extension for a long time.
This cache extension is backed by Caffeine by default.

We also had an Infinispan Client extension.

With the new Infinispan Cache extension, you can now use the cache extension approach and use Infinispan as a backend.

And, you know us by now, we baked a https://quarkus.io/guides/cache-infinispan-reference[dedicated guide] just for you.

=== WebSockets.next

WebSockets.next is our... next (tadam!)-gen WebSockets extension (both client and server).

It is experimental at the moment and we are making steady progress on it with each release.

In Quarkus 3.11, we added:

- The ability to easily define WebSockets clients.
- An initial version of the security integration (we will add more features in future releases).

=== quarkus:run and Dev Services

`./mvnw quarkus:run` is a convenient way to start your Quarkus application.
It is now able to start Dev Services so that your favorite service can be started automatically as a container.

=== Security

As for each release, this release comes with several new security features including:

- Support for OIDC session expired page
- The introduction of `OidcRedirectFilter`, which allows to customize OIDC redirects

=== Quarkus CXF

Quarkus CXF 3.11.0 was released and is now available in https://code.quarkus.io/?extension-search=origin:platform%20quarkus-cxf[Quarkus Platform 3.11].
Check https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.11.0.html[Quarkus CXF 3.11.0 release notes] for more information about what is new in this release.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.11.0.CR1[3.11.0.CR1] and https://github.com/quarkusio/quarkus/releases/tag/3.11.0[3.11.0] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[946 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.11 release, thanks to Alasdair Preston, Aleksandr Nichiporuk, Ales Justin, Alexey Loubyansky, Andy Damevin, Antonio Musarra, antonwiens, Arcane418, asjervanasten, Bruno Baptista, Chris Laprun, cknoblauch, Clement Escoffier, Danny Gräf, David M. Lloyd, emile, Eric Deandrea, Foivos Zakkak, Fouad Almalki, George Gastaldi, Georgios Andrianakis, glefloch, Guillaume Smet, Gwenneg Lepage, Holly Cummins, Ivan Puntev, Jakub Jedlicka, Jan Martiska, Juan Zuriaga, Katia Aresti, Ladislav Thon, Lin Gao, Lorenzo Vannucchi, Loïc Mathieu, Marc Nuri, Marek Skacelik, mariofusco, Martin Kouba, Matej Novotny, Max Rydahl Andersen, Michal Maléř, Michal Vavřík, Nathan Erwin, Nithanim, Ozan Gunalp, Phillip Krüger, punkepa, Roberto Cortez, Rostislav Svoboda, Sanne Grinovero, Sauli Ketola, Selim, Sergey Beryozkin, Stuart Douglas, Stéphane Épardaud, Thomas Segismont, Vincent Sourin, Vinicius A. Santos, vkn, Yoann Rodière, and Zheng Feng.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
