---
layout: post
title: 'Quarkus 3.25.4 - Maintenance release'
date: 2025-08-20
tags: release
synopsis: 'We released Quarkus 3.25.4, a maintenance release for our 3.25 release train.'
author: gsmet
---

We released Quarkus 3.25.4, the fourth maintenance release for our 3.25 release train.

Amongst other fixes, this release addresses https://nvd.nist.gov/vuln/detail/CVE-2025-55163[CVE-2025-55163].

== Update

To update to Quarkus 3.25, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.25.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.25[Quarkus 3.25 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.25.4[3.25.4] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
