---
layout: post
title: 'Quarkus 3.29.2 - Maintenance release'
date: 2025-11-08
tags: release
synopsis: 'We released Quarkus 3.29.2, a regular maintenance release.'
author: gsmet
---

Today, we released Quarkus 3.29.2, a new maintenance release for our 3.29 stream.

We skipped the 3.29.1 announcement as we detected a regression shortly after the release and decided to release 3.29.2 right away.
The regression was caused by a problem in how binaries were detected in the `$PATH` specfically on Windows.

== Update

To update to Quarkus 3.29, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.29.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.29[Quarkus 3.29 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.29.1[3.29.1] and https://github.com/quarkusio/quarkus/releases/tag/3.29.2[3.29.2] on GitHub.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
