---
layout: post
title: 'Quarkus 3.18 - Micrometer for WebSockets Next, Security WebAuthn based on WebAuthn4J, Kubernetes Client 7...'
date: 2025-01-29
tags: release
synopsis: 'We released Quarkus 3.18, our first feature release for 2025. It comes with a lot of new features such as Micrometer integration for WebSockets Next, a new WebAuthn implementation, a lot of enhancements for our security extensions...'
author: gsmet
---

Today, we released Quarkus 3.18, with two months worth of new features and enhancements.

It comes with a lot of enhancements and the following new features:

* https://github.com/quarkusio/quarkus/pull/44379[#44379] - Integrate Micrometer with WebSockets Next
* https://github.com/quarkusio/quarkus/pull/44105[#44105] - Reimplement security-webauthn on top of webauthn4j
* https://github.com/quarkusio/quarkus/pull/45131[#45131] - OIDC and OIDC Client: Support JWT bearer client authentication using client assertion loaded from filesystem
* https://github.com/quarkusio/quarkus/pull/45121[#45121] - Support for OIDC mTLS binding
* https://github.com/quarkusio/quarkus/pull/44993[#44993] - Support OidcProviderClient injection and token revocation
* https://github.com/quarkusio/quarkus/pull/44546[#44546] - Add OIDC Redis Token State Manager extension
* https://github.com/quarkusio/quarkus/pull/45294[#45294] - Allow to create static OIDC tenants programmatically
* https://github.com/quarkusio/quarkus/pull/35324[#35324] - OIDC Dev Services and UI changes
* https://github.com/quarkusio/quarkus/pull/45117[#45117] - TLS - Enable policy configuration for expired or not yet valid certificates
* https://github.com/quarkusio/quarkus/pull/44549[#44549] - Add support for encrypted PKCS#8
* https://github.com/quarkusio/quarkus/pull/43885[#43885] - Exclude uri from OpenTelemetry Tracing
* https://github.com/quarkusio/quarkus/pull/45259[#45259] - Bump kubernetes-client-bom from 6.13.4 to 7.0.1
* https://github.com/quarkusio/quarkus/pull/32447[#32447] - Introduce `Report an Issue`  menu in DevUI
* https://github.com/quarkusio/quarkus/pull/43618[#43618] - Add a Dev UI screen for Agroal datasources
* https://github.com/quarkusio/quarkus/pull/44305[#44305] - Ability to configure extension dev mode JVM options
* https://github.com/quarkusio/quarkus/pull/44424[#44424] - Support for dev-mode-only conditional dependencies

We are already hard at work preparing 3.19 and the upcoming 3.20 LTS.

== Update

To update to Quarkus 3.18, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.18.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.18[Quarkus 3.18 migration guide].

== What's new?

=== WebSockets.Next

Our next-generation WebSockets extension continues to improve with each version.

In 3.18, it comes with Micrometer integration.

=== Security

You are used to it, each version comes with a lot of enhancements to our security layer, offering even more flexibility.

This time, it comes with the complete rewrite of our Security Webauthn extension to leverage the WebAuthn4J library (if you are using this extension, please have a look at the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.18#webauthn[dedicated section in the migration guide] as a lot of things have changed), a lot of new features for OIDC, and improvements to our TLS registry:

* https://github.com/quarkusio/quarkus/pull/44105[#44105] - Reimplement security-webauthn on top of webauthn4j
* https://github.com/quarkusio/quarkus/pull/45131[#45131] - OIDC and OIDC Client: Support JWT bearer client authentication using client assertion loaded from filesystem
* https://github.com/quarkusio/quarkus/pull/45121[#45121] - Support for OIDC mTLS binding
* https://github.com/quarkusio/quarkus/pull/44993[#44993] - Support OidcProviderClient injection and token revocation
* https://github.com/quarkusio/quarkus/pull/44546[#44546] - Add OIDC Redis Token State Manager extension
* https://github.com/quarkusio/quarkus/pull/45294[#45294] - Allow to create static OIDC tenants programmatically
* https://github.com/quarkusio/quarkus/pull/35324[#35324] - OIDC Dev Services and UI changes
* https://github.com/quarkusio/quarkus/pull/45117[#45117] - TLS - Enable policy configuration for expired or not yet valid certificates
* https://github.com/quarkusio/quarkus/pull/44549[#44549] - Add support for encrypted PKCS#8

=== OpenTelemetry Tracing

When using OpenTelemetry Tracing, it happens quite often that you don't want to collect any trace for a given URI.

3.18 comes with the `quarkus.otel.traces.suppress-application-uris` that allows to define URIs that are going to be ignored.

You can find more information about this new feature in the https://quarkus.io/guides/opentelemetry-tracing#disabling-traces-for-app-endpoints[OpenTelemetry Tracing guide].

=== Kubernetes Client

The Kubernetes Client was upgraded to a major new version: Kubernetes Client 7.

You can find more information about this upgrade in our https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.18#kubernetes-client-fabric8[migration guide].

=== Dev UI

We polished our Dev UI with two new features:

- A screen to browse the tables exposes by your datasources
- A quick link to report an issue to the Quarkus project on GitHub

=== Preparing our next LTS

We are also preparing our next LTS with various initiatives:

- A lot of extensions were migrated to the new `@ConfigMapping`-based configuration infrastructure (and this effort will continue in the next versions).
- We are making enhancements related to startup time and initial memory (RSS) usage.
- We are removing code that was deprecated for a long time.

Expect us to focus on polishing features and fixing issues for the upcoming 3.19 and 3.20.

=== Platform component upgrades

==== Quarkus CXF

Quarkus CXF 3.18 was released and is now available in https://code.quarkus.io/?extension-search=origin:platform%20quarkus-cxf[Quarkus Platform 3.18].
Check the https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.18.0.html[Quarkus CXF 3.18.0] release notes for more information about what is new in this release.

==== Camel Quarkus

Camel Quarkus has been upgraded to 3.18.0.

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.18.0.CR1[3.18.0.CR1], https://github.com/quarkusio/quarkus/releases/tag/3.18.0[3.18.0], and https://github.com/quarkusio/quarkus/releases/tag/3.18.1[3.18.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1048 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.18 release, thanks to Akulov S V, Ales Justin, Alex Martel, Alexander Pankin, Alexey Loubyansky, André Pantaleão, Andy Damevin, Ankush Saini, Antonio Musarra, Auri Munoz, Bassel Rachid, Blaz Mrak, Bruno Baptista, Bruno Marvin, Chris Laprun, Christian Ivanov, Christian Pieczewski, Clement Escoffier, Cristian Burlacu, Damien Clément d'Huart, Daniel Bobbert, Daniel Strobusch, Danilo Piazzalunga, David M. Lloyd, Davide D'Alto, Eduard Wagner, Emmanuel Ferdman, Eric Deandrea, Erik Mattheis, Fary Hurtado, Foivos Zakkak, Francesco Nigro, George Gastaldi, Georgios Andrianakis, Gianmarco Frangipane, Guillaume Smet, Gurubase.io, Harald Albers, HerrDerb, Holly Cummins, Inaki Villar, Ioannis Canellos, ivan.baricic, Jakub Jedlicka, Jan Martiska, Jeremie Bresson, Jochen Schalanda, Johnathan Gilday, Jorge Pinto, Jose, Julien Ponge, Katia Aresti, Ladislav Thon, Lars Andringa, Loïc Mathieu, luneo7, Maciej Lisowski, Marc Nuri, Marco Belladelli, Marco Bungart, Marco Collovati, Marek Skacelik, mariofusco, Martin Bartoš, Martin Kouba, Martin Panzer, Matej Novotny, Matheus Cruz, Max Rydahl Andersen, Michael Edgar, Michal Maléř, Michal Vavřík, Neon, Nuno Neto, ogomezdi, Ozan Gunalp, Ozzy Osborne, Peter Skopek, Phillip Krüger, rghara, Roberto Balarezo, Roberto Cortez, Rolfe Dlugy-Hegwer, Romain QUINIO, Rostislav Svoboda, row, Scott M Stark, Sergey Beryozkin, sergioruydev, Sola-ris, Stephan Strate, Stuart Douglas, Stéphane Épardaud, Thibault Meyer, Thomas Canava, tom, Trấn Nguyễn, vkn, xstefank, Yoann Rodière, Yoshikazu Nojima, zanmagerl, and Zheng Feng.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
