---
layout: post
title: 'Quarkus 3.27 - new LTS version'
date: 2025-09-24
tags: release
synopsis: 'We released Quarkus 3.27, our new LTS version.'
author: gsmet
---

It is our pleasure to announce the release of Quarkus 3.27, which is our new LTS (Long Term Support) version.

This version is built on the top of Quarkus 3.26.
New features landed in https://quarkus.io/blog/quarkus-3-28-released/[Quarkus 3.28], which was also released today.

If you want to know more about our LTS policy, the https://quarkus.io/blog/lts-releases/[LTS announcement] is a must read.

LTS releases are supported for 12 months.

If you are coming from the previous LTS, Quarkus 3.20, there are a lot of exciting new features and we recommend reading the following announcements:

- https://quarkus.io/blog/quarkus-3-21-0-released/[Quarkus 3.21 - TLS Registry support for MongoDB Client]
- https://quarkus.io/blog/quarkus-3-22-1-released/[Quarkus 3.22 - Compose Dev Services, improved test class loading infrastructure...]
- https://quarkus.io/blog/quarkus-3-23-0-released/[Quarkus 3.23 - Named datasources for Hibernate Reactive, OIDC bearer step up authentication]
- https://quarkus.io/blog/quarkus-3-24-released/[Quarkus 3.24 - Dev Assistant, Hibernate ORM 7, Hibernate Validator 9...]
- https://quarkus.io/blog/quarkus-3-25-released/[Quarkus 3.25 - Virtual threads for GraphQL, Micrometer update and various new security-related features]
- https://quarkus.io/blog/quarkus-3-26-released/[Quarkus 3.26 - Hibernate updates, named persistence units in Hibernate Reactive, Dev UI as MCP functions, and more.]

== Update

To update to Quarkus 3.27, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.27 LTS.

If you are upgrading from 3.26, there's nothing to do as 3.27 is the direct continuation of 3.26.

If you are upgrading from the previous LTS, Quarkus 3.15, please refer to the following migration guides:

- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.21[Migration guide for 3.21]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.22[Migration guide for 3.22]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.23[Migration guide for 3.23]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.24[Migration guide for 3.24]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.25[Migration guide for 3.25]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.26[Migration guide for 3.26]
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.27[Migration guide for 3.27] - this one is empty as 3.27 is the continuation of 3.26

Note that `quarkus update` should handle most of the heavy lifting for you,
but there are still cases that should be handled manually and we recommend reading these migration guides carefully.

== What's new?

=== Platform component upgrades

==== Camel Quarkus

Camel Quarkus has been updated to 3.27.0.
You can find everything you need to know about it in the https://camel.apache.org/blog/2025/09/camel-quarkus-3.27.0/[release notes].

==== Quarkus CXF

Quarkus CXF 3.27 was released and is now available in https://code.quarkus.io/?extension-search=origin:platform%20quarkus-cxf[Quarkus Platform 3.27].
Check the https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/3.27.0.html[Quarkus CXF 3.27.0] release notes for more information about what is new in this release.

==== Quarkus LangChain4j

The Quarkus LangChain4j extensions have been upgraded to version 1.2.0.
It relies on LangChain4j 1.5.

== Full changelog

The core part of Quarkus 3.27.0 is a rebadged release of Quarkus 3.26.4 so nothing new here.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1122 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.27 release, thanks to Akulov S V, Alexey Loubyansky, Bhawna, brunobat, Christian Beikov, Fouad Almalki, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Jan Martiska, Jan Scheidegger, Julien Ponge, Karm Michal Babacek, Luca Molteni, Marco Belladelli, marko-bekhta, Martin Kouba, Melloware, Michael Edgar, Michal Maléř, Michal Vavřík, Ozan Gunalp, Peter Palaga, Phillip Kruger, Roberto Cortez, Rolfe Dlugy-Hegwer, Rostislav Svoboda, Saee Saadat, Sergey Beryozkin, and Teymur Babayev.

The list is a bit smaller than usual as 3.27 only contains bugfixes on top of 3.26.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
