---
layout: post
title: 'Quarkus 3.34 - Enhancements all around'
date: 2026-03-25
tags: release
synopsis: 'We released Quarkus 3.34, which comes with a lot of enhancements across the board.'
author: gsmet
---

Today, we released both https://quarkus.io/blog/quarkus-3-33-released/[Quarkus 3.33 LTS] and Quarkus 3.34.

While Quarkus 3.33 is a Long Term Support (LTS) release, branched from Quarkus 3.32 and maintained for 12 months,
Quarkus 3.34 comes with a lot of enhancements across the board:
Dev UI, Panache Next, and a lot of other areas got improved.

This release also includes internal changes and refactorings that will bear fruits in future versions.

== Update

To update to Quarkus 3.34, we recommend updating to the latest version of the Quarkus CLI and run:

[source,bash]
----
quarkus update
----

Note that `quarkus update` can update your applications from any version of Quarkus (including 2.x) to Quarkus 3.34.

For more information about the adjustments you need to make to your applications, please refer to the https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.34[Quarkus 3.34 migration guide].

== Full changelog

You can get the full changelog of https://github.com/quarkusio/quarkus/releases/tag/3.34.0.CR1[3.34.0.CR1], https://github.com/quarkusio/quarkus/releases/tag/3.34.0[3.34.0], and https://github.com/quarkusio/quarkus/releases/tag/3.34.1[3.34.1] on GitHub.

== Contributors

The Quarkus community is growing and has now https://github.com/quarkusio/quarkus/graphs/contributors[1173 contributors].
Many many thanks to each and everyone of them.

In particular for the 3.34 release, thanks to Ales Justin, Alexey Loubyansky, Andy Damevin, Asger Askov Blekinge, Ashish Thakur, Aurea Munoz, Aurélien Pupier, Bruno Baptista, Carles Arnal, Char, Chris Ruffalo, Clement Escoffier, Clément de Tastes, Daniel Vergien, David M. Lloyd, Dennis Kniep, Dmitri Bourlatchkov, Erwin Oegema, Faisal Dilawar, Foivos Zakkak, Frank Eichfelder, g, Gaelle Fournier, Galder Zamarreño, George Gastaldi, Georgios Andrianakis, Guillaume Smet, Holly Cummins, Inaki Villar, Jakub Jedlicka, Jan Martiska, jcarranzan, JeffersonSantos29, Jens Teglhus Møller, Julien Ponge, Katia Aresti, Kristian Rickert, Ladislav Thon, Luca Molteni, Martin Kouba, Martin Panzer, María Arias de Reyna Domínguez, Matej Novotny, Matheus Andre, Matheus André, Michael Edgar, Michal Maléř, Michal Vavřík, Nico Hinrichs, Ozan Gunalp, Patrick Schaub, Peter Levart, Phillip Krüger, Roberto Cortez, Sanne Grinovero, Sergey Beryozkin, shjones, Stéphane Épardaud, Thomas McWork, tiwari91, Tom Jenkinson, Tom Schindl, Vincent Sevel, xstefank, and Yoann Rodière.

== Come Join Us

We value your feedback a lot so please report bugs, ask for improvements... Let's build something great together!

If you are a Quarkus user or just curious, don't be shy and join our welcoming community:

 * provide feedback on https://github.com/quarkusio/quarkus/issues[GitHub];
 * craft some code and https://github.com/quarkusio/quarkus/pulls[push a PR];
 * discuss with us on https://quarkusio.zulipchat.com/[Zulip] and on the https://groups.google.com/d/forum/quarkus-dev[mailing list];
 * ask your questions on https://stackoverflow.com/questions/tagged/quarkus[Stack Overflow].
