---
layout: post
title: 'Quarkus Hibernate with Panache Next renamed to Quarkus Data Hibernate'
date: 2026-05-28
tags: extension
synopsis: "We've renamed Quarkus Hibernate with Panache to Quarkus Data Hibernate, and are looking for feedback"
author: fromage
---

== Goodbye Hibernate with Panache Next… welcome Quarkus Data Hibernate 🥳

It's already been a while since we introduced
link:/blog/hibernate-panache-next[Quarkus Hibernate with Panache Next], and since then, we've decided to
move closer to the link:https://jakarta.ee/specifications/data/1.1/jakarta-data-1.1-m3[Jakarta Data] standard, as well
as rename the module to https://quarkus.io/version/main/guides/quarkus-data-hibernate[Quarkus Data Hibernate].

I'll repeat the original disclaimer: this is a new extension, which is experimental, which means everything
about it can (and probably will) change: the extension name, the package names, the class names
and even the API. We are releasing it because we feel it's in a good shape to be tested and discussed
by the community, and we hope to get better feedback before we commit to anything like names or
API.

Please report feedback either on link:https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/WG.20-.20Quarkus.20Data/with/598039033[Zulip]
or via link:https://github.com/orgs/quarkusio/projects/50/views/1[GitHub issues].

== What changed since last time?

- Pivoted from the Panache 1
  link:https://javadoc.io/doc/io.quarkus/quarkus-panache-common/latest/io/quarkus/panache/common/Sort.html[`Sort`] type
  to the Jakarta Data link:https://jakarta.ee/specifications/data/1.1/apidocs/jakarta.data/jakarta/data/order[`Order`]
  type for sorting: https://github.com/quarkusio/quarkus/issues/53429
- Supported link:https://quarkus.io/version/main/guides/hibernate-reactive-panache#transactions[`@Transactional`]
  for Hibernate Reactive transactions: https://github.com/quarkusio/quarkus/issues/47698
- Support non-blocking link:https://quarkus.io/guides/lifecycle#startup_annotation[`@Startup`] methods:
  https://github.com/quarkusio/quarkus/issues/50175
- The link:https://jakarta.ee/specifications/data/1.1/apidocs/jakarta.data/jakarta/data/repository/repository[`@Repository`]
  annotation is now optional on nested repositories: https://github.com/quarkusio/quarkus/issues/50178
- Added a codestart: https://github.com/quarkusio/quarkus/issues/51565
- Make sure the link:https://quarkus.io/guides/hibernate-reactive[Hibernate Reactive] dependency is optional:
  https://github.com/quarkusio/quarkus/pull/52265
- Deprecated the link:https://javadoc.io/doc/io.quarkus/quarkus-panache-common/latest/io/quarkus/panache/common/Parameters.html[`Parameters`]
  class in favour of link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Map.html#of()[`Map.of`]:
  https://github.com/quarkusio/quarkus/pull/52583
- Added link:https://javadoc.io/doc/io.quarkus/quarkus-hibernate-panache-next/latest/io/quarkus/hibernate/panache/stateless/PanacheStatelessEntityOperations.html#upsert()[`upsert`]
  operation: https://github.com/quarkusio/quarkus/pull/52574
- Make `StatelessSession` injectable for link:https://quarkus.io/guides/hibernate-reactive[Hibernate Reactive]
  https://github.com/quarkusio/quarkus/issues/47462
- Support link:https://quarkus.io/guides/security-overview#key-features-of-quarkus-security[security annotations]
  on repositories: https://github.com/quarkusio/quarkus/issues/53623
- Support link:https://quarkus.io/guides/getting-started-testing#further-simplification-with-injectmock[`@InjectMock`]
  on repositories: https://github.com/quarkusio/quarkus/issues/53873

And many other bug fixes.

== Need feedback

We're currently working on various issues, but we could especially use feedback on the following topics:

=== Paging

We're switching to Jakarta Data `Page` and `PageRequest` for paging, including using cursors. This one will introduce a new
API on `PanacheQuery` for paging: https://github.com/quarkusio/quarkus/issues/53431

```java
    @Transactional
    void offsetPage() {
        PanacheBlockingQuery<MyEntity> query = MyEntity_.managedBlocking().findAll();

        List<MyEntity> list = query.paging().offset(0, 10).list();
        while (query.paging().hasNext()) {
            list = query.paging().next().list();
        }
    }

    @Transactional
    void cursorPage() {
        PanacheBlockingQuery<MyEntity> query = MyEntity_.managedBlocking().findAll();

        List<MyEntity> list = query.paging().cursored(0, 10).list();
        while (query.paging().hasNext()) {
            list = query.paging().next().list();
        }
    }

    @Transactional
    void limitPage() {
        PanacheBlockingQuery<MyEntity> query = MyEntity_.managedBlocking().findAll();

        List<MyEntity> list = query.limiting().limit(10).list();
    }
```

=== Names

In https://github.com/quarkusio/quarkus/issues/53145 we are considering moving:

- Our package name from `io.quarkus.hibernate.panache` to `io.quarkus.data.hibernate` (this one is pretty obvious)
- The `PanacheEntity` name to `ManagedEntity` (for entities backed by a stateful session), and `RecordEntity` or
  `ActiveRecord` (for entities backed by a stateless session).
- The `PanacheRepository` name to… something that would go along with whatever names we pick for our entities 😬

Please comment on the issue if you like this or think of anything better. But please read all the discussion first :)

=== Automatic configuration of required annotation processor

On https://github.com/quarkusio/quarkus/pull/53901 we have a proof of concept that lets our Maven and Gradle builds
automatically configure the required Hibernate Processor annotation processor, so that you can't forget to add them
to your builds.

This raises questions about magic and compatibility with IDEs, so chime in if you have opinions about those.

== Let us know

We're still looking for feedback, and testers.

Give it a try, https://quarkus.io/version/main/guides/quarkus-data-hibernate[read the documentation], and give us feedback either on
link:https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/WG.20-.20Quarkus.20Data/with/598039033[Zulip]
or via link:https://github.com/orgs/quarkusio/projects/50/views/1[GitHub issues].
