= Glossary

include::./attributes.adoc[]

This is a collection of preferred term in the documentation and website.
Please stay within these terms for consistency.

* Live reload:: for our `quarkus:dev` capability
* GraalVM native images:: preferred term for the technology creating native executable. Exactly 2 spaces.
* SubstrateVM:: non-preferred. Only if you want to clarify the code name of the project in the GraalVM ecosystem that contains implementation of the runtime components (like GC) used in GraalVM native images.
* Native Executable:: platform dependent binary not requiring a runtime to be executed.
* Docker image:: for the actual `Dockerfile` definition and when the tool chain is involved
* Container:: when we discuss Quarkus running in... containers
* Supersonic Subatomic Java:: our tagline
* Kubernetes Native Java:: our preferred tagline to say that we rock for containers
* Developer Joy:: for everything going from live reload to the opinionated layer to a single config file
* Unify Imperative and Reactive:: imperative and reactive. 'Nuff said.
* Best of breed frameworks and standards:: when we explain our stack
