name: Build and deploy to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build TOC plugin
        run: ./roq-plugin-toc/build.sh

      - name: Build with Maven
        run: QUARKUS_ROQ_GENERATOR_BATCH=true mvn -B package quarkus:run -DskipTests

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v4.0.1
        with:
          path: ./target/roq
          include-hidden-files: true
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

      # search.quarkus.io expects that the rendered content is available in gh-pages branch
      - name: Sync gh-pages branch
        run: |
          SITE_DIR=$(mktemp -d)
          rsync -a ./target/roq/ "$SITE_DIR"
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git fetch origin gh-pages:gh-pages
          # TODO: Remove the -f Roq 2.1.8
          git checkout -f gh-pages

          rsync -a --delete --exclude='.git' --exclude='.nojekyll' "$SITE_DIR"/ .
          git add -A
          git rm -rf --cached --ignore-unmatch target/roq

          git commit --allow-empty -m "deploy: ${{ github.sha }}"
          git push origin gh-pages
